import React, { useState } from 'react';
import { CirclePause, CirclePlay, ExternalLink, RotateCcw, ShieldCheck, X } from 'lucide-react';
import { ModuleHeader } from '../../components/ModuleHeader';
import type { RoleId } from '../../types';
import { createRepairTaskContext, dynamicPlans, type DynamicPlan, type PlanDeviation } from './m09-data';
import './m09.css';

type View = 'digital' | 'human' | 'activity' | 'timeline' | 'variance';
type AgentCard = { icon: string; name: string; version: string; layer: string; department: string; task: string; progress: number; status: string; metrics: string[]; tone: string };
type HumanCard = { avatar: string; name: string; role: string; org: string; state: string; current: string; items: string[]; footer: string[] };

const canEdit = (role: RoleId) => ['trainer', 'admin', 'superadmin'].includes(role);
const agentCards: AgentCard[] = [
  { icon: '🤖', name: '客服应答 Agent', version: 'v2.3.1', layer: '执行层', department: '客服事业部', task: '处理品牌方 A 的购车咨询队列', progress: 62, status: '在线', metrics: ['平均响应 320ms', '准确率 96.2%', '已解决 178'], tone: 'green' },
  { icon: '🧹', name: '线索清洗 Agent', version: 'v1.8.0', layer: '执行层', department: '线索事业部', task: '清洗品牌方 C 的到店线索数据', progress: 62, status: '在线', metrics: ['平均耗时 480ms', '准确率 93.7%', '去重 86条'], tone: 'green' },
  { icon: '✍️', name: '内容生成 Agent', version: 'v3.0.2', layer: '执行层', department: '内容事业部', task: '批量生成 N7 车型朋友圈投放素材', progress: 63.5, status: '降级中', metrics: ['平均耗时 1.2s', '质量分 91.5', '127/200条'], tone: 'purple' },
  { icon: '📱', name: 'KOC运营 Agent', version: 'v1.5.2', layer: '执行层', department: '用户运营事业部', task: '匹配 KOC → 分发 N7 素材 → 追踪发帖', progress: 60, status: '在线', metrics: ['已发帖 12篇', '互动率 4.2%', '触达 48万'], tone: 'amber' },
  { icon: '🔍', name: '合规审核 Agent', version: 'v0.9.5', layer: '审核层', department: '法务部', task: '等待内容生成 Agent 产出并自动触发审核', progress: 41, status: '待命', metrics: ['平均耗时 650ms', '通过率 94.1%', '拦截 5条'], tone: 'amber' },
  { icon: '🧠', name: '营销策略 Agent', version: 'v1.2.0', layer: '策略层', department: '平台', task: '制定品牌方 B 本月线索提升策略方案', progress: 78, status: '在线', metrics: ['预计 11:30', '置信度 89.8%', '调用 4子Agent'], tone: 'blue' },
  { icon: '📊', name: 'VOC分析 Agent', version: 'v0.7.1', layer: '学习层', department: '平台', task: '空闲，等待数据更新或手动触发', progress: 0, status: '空闲', metrics: ['上次运行 2h前', '下次 14:00', '无异常'], tone: 'muted' },
  { icon: '🔧', name: '远程诊断 Agent', version: 'v0.9.5', layer: '执行层', department: '客服事业部', task: '增量训练中新故障模式标注数据 200条', progress: 30, status: '训练中', metrics: ['预计 14:30', '当前 loss 0.23', 'Epoch 3/10'], tone: 'cyan' },
];
const humanCards: HumanCard[] = [
  { avatar: '李', name: '李明远', role: '平台管理员', org: 'AI平台VP · 转型领导小组', state: '在线', current: '审批升级提案 #UP-2026-0042 + 审核灰度发布方案', items: ['待审批：Token商业化提前提案', '待审批：内容生成Agent v3.0.3 上线门禁', '审核中：Q3 Agent上线计划'], footer: ['待审批 5项', '管辖Agent 12个', '在线 3h12m'] },
  { avatar: '张', name: '张伟国', role: '超级管理员', org: 'CEO · AI-Native转型领导小组组长', state: '在线', current: '董事会汇报准备 — Q3转型预算 + RaaS试点进展', items: ['战略决策：M6 Go/No-Go评审', '审阅：品牌方C RaaS试点效果报告', '外部会议：数说故事对标交流 14:00'], footer: ['待决策 3项', '管辖Agent 24个', '在线 4h05m'] },
  { avatar: '王', name: '王晓芳', role: '业务负责人', org: '客服事业部 · 5人团队', state: '在线', current: '监控客服应答Agent运行 + 抽查对话质量', items: ['质检：客服Agent对话抽检 20/50条', '处理：升级工单 #TKT-2026-0705', '带教：新转岗AI训练师 2人'], footer: ['待处理 4项', '管辖Agent 5个', '在线 5h20m'] },
  { avatar: '赵', name: '赵志强', role: '业务负责人', org: '线索事业部 · 5人团队', state: '在线', current: '分析华东区域线索到店率连续3天低于全国均值15%', items: ['根因分析：华东线索转化率异常', '协调：与华东区域经理沟通门店承接能力'], footer: ['待处理 3项', '管辖Agent 5个', '在线 3h48m'] },
  { avatar: '陈', name: '陈思敏', role: 'AI训练师', org: '内容事业部 · 从设计师转岗', state: '在线', current: '标注内容生成Agent的Prompt注入防护训练数据', items: ['标注：对抗性Prompt样本 86/200条', '修复：内容Agent v3.0.3 8个失败用例'], footer: ['标注进度 43%', '对接Agent 3个', '在线 2h55m'] },
  { avatar: '刘', name: '刘建国', role: '只读观察者', org: '财务部 · 预算审核', state: '离开', current: '离开，预计 13:30 返回', items: ['待处理：阶段一预算审核'], footer: ['待处理 1项', '最后活跃 11:20'] },
  { avatar: '孙', name: '孙浩然', role: 'AI训练师', org: '客服事业部 · 外包团队转型', state: '休假', current: '休假中，预计 7月5日返岗', items: ['任务已自动流转至陈思敏'], footer: ['无待处理任务'] },
];
const activityGroups = [
  { name: '李明远', role: '平台管理员 · AI平台VP', rows: [['10:48','营销策略Agent','审批升级提案 #UP-2026-0042','8,200'],['10:30','内容生成Agent','审核灰度发布方案：批准10%→50%','5,400'],['09:45','A2A编排引擎','审批并发安全加固上线门禁','12,800'],['09:15','营销策略Agent','对话：先看Q3线索转化方案摘要','18,500']], total: '70,500', output: '决策 6次' },
  { name: '王晓芳', role: '业务负责人 · 客服事业部', rows: [['10:50','客服应答Agent','抽查对话质量：20条/50条目标','6,200'],['10:20','异常工单中心','处理升级工单 #TKT-2026-0705','2,800'],['09:30','知识库','审核更新购车咨询标准话术文档','4,500'],['08:45','客服应答Agent','抽查昨日高意向漏跟case','15,200']], total: '30,800', output: '决策 4次' },
  { name: '陈思敏', role: 'AI训练师 · 内容事业部', rows: [['10:35','训练数据工厂','标注对抗性Prompt样本 86/200条','8,400'],['09:40','Agent测试沙箱','修复内容Agent v3.0.3失败用例×8','12,600'],['08:50','Prompt工程','优化车型卖点文案模板评分 B+→A','5,200'],['08:20','知识库','新增N7城市NOA功能文档3篇','2,100']], total: '28,300', output: '产出：标注86条+3文档' },
  { name: '赵志强', role: '业务负责人 · 线索事业部', rows: [['10:52','线索诊断Agent','查看华东区域根因分析初步结果','6,800'],['10:15','线索培育Agent','调整华东区域培育策略参数','9,400'],['09:20','线索清洗Agent','审核昨日线索去重结果','4,200'],['08:40','线索诊断Agent','对话：华东到店率连续3天低于全国15%','16,800']], total: '37,200', output: '决策 3次' },
];
const gantt = [
  ['客服应答 Agent','全天持续 · 186/300会话',0,72,'blue'],['线索清洗 Agent','08:00–12:00 · 1240/2000条',0,65,'green'],['内容生成 Agent','08:00–11:30 · 127/200条',0,45,'purple'],['KOC运营 Agent','08:30–13:00 · 18/30人',5,40,'amber'],['营销策略 Agent','09:00–11:30 · 方案78%',15,30,'blue'],['合规审核 Agent','08:40–持续 · 82条已审',10,55,'amber'],['远程诊断 Agent','09:30–14:30 · 训练中',20,50,'cyan'],['舆情监控 Agent','14:00–15:00 · 待触发',55,20,'red'],
] as const;
const liveLogs = [
  ['10:50:45','INFO','用户洞察Agent 完成增换购人群画像分析 → 推送至策略Agent'],['10:50:02','OK','KOC运营Agent 接受任务，预计11:30前发帖'],['10:49:23','INFO','内容生成Agent 第130条素材生成完成，自动适配朋友圈规格'],['10:48:51','OK','线索评分日更处理完成，高意向新增1,240条'],['10:42:22','WARN','内容生成Agent 第125条素材质量84分，触发人工抽检'],['10:38:50','OK','客服应答Agent 识别高意向会话并推送线索培育Agent'],['10:30:00','INFO','调度中心触发线索评分日更批处理'],['10:22:10','WARN','合规审核Agent 拦截2条含竞品敏感词内容'],
];
const moments = [['08:00','系统启动','数据同步Agent完成品牌方A/B/C数据同步；客服应答Agent上线'],['08:30','定时触发','线索转化工作流启动；内容生成Agent开始日产素材'],['08:55','熔断事件','内容生成Agent质量分82/100，触发熔断，人工审核介入'],['09:15','任务链完成','8 Agent协同完成线索转化提升，耗时3分24秒'],['10:30','批处理启动','线索评分日更，全量线索重新评分中'],['10:48 现在','当前','12个Agent执行中、4个待命、1个训练中、1个降级'],['14:00','计划触发','VOC分析Agent周报与舆情监控Agent日报'],['15:30','计划触发','营销策略Agent输出N7试驾链路优化方案'],['16:00','交接','早班数字员工总结，晚班Agent接班']];
const planRows = [
  ['品牌方 A/B/C 数据同步','数据同步 Agent','08:00','2m','完成','2m10s','+10s'],['线索转化提升工作流','8 Agent协同','08:30','5m','完成','3m24s','−1m36s'],['日产N7投放素材 200条','内容生成 Agent','08:00–12:00','4h','执行中','127/200 · 63.5%','预计提前20m'],['KOC匹配+分发 30人','KOC运营 Agent','08:30–14:00','5.5h','执行中','18/30 · 60%','按计划'],['线索日清洗 2000条','线索清洗 Agent','08:00–12:00','4h','执行中','1240/2000 · 62%','按计划'],['客服全渠道应答 ≥300会话','客服应答 Agent','全天','8h','执行中','186/300 · 62%','按计划'],['营销策略方案产出','营销策略 Agent','09:00–11:30','2.5h','执行中','78%','预计提前15m'],
];

export function M09DynamicPlanPage({ role }: { role: RoleId }) {
  const [view, setView] = useState<View>('digital');
  const [plans, setPlans] = useState(dynamicPlans);
  const [detailId, setDetailId] = useState<string | null>(null);
  const [notice, setNotice] = useState('');
  if (['employee', 'client'].includes(role)) return <section className="m09-gate"><ShieldCheck /><h1>M09 动态计划不可访问</h1><p>{role === 'client' ? '客户管理员无权查看内部运行计划。' : '员工在工作空间查看本人任务，不进入全局执行监控。'}</p></section>;
  const plan = plans.find(item => item.id === detailId);
  const update = (next: DynamicPlan, action: string) => { setPlans(items => items.map(item => item.id === next.id ? { ...next, audit: [`刚刚 当前用户：${action}`, ...next.audit] } : item)); setNotice(action); };
  const jump = (item: DynamicPlan, taskId: string) => setNotice(`已定位 M05 任务 ${taskId}，携带 ${item.workflowId} / ${item.runId} 上下文`);
  const repair = (item: DynamicPlan, deviation: PlanDeviation) => { const context = createRepairTaskContext(item, deviation); update({ ...item, deviations: item.deviations.map(value => value.id === deviation.id ? { ...value, status: '处置中', taskId: `TASK-REPAIR-${Date.now().toString().slice(-4)}` } : value) }, `已创建 M05 修复任务「${context.title}」`); };
  const tabs: { id: View; label: string; icon: string }[] = [{ id:'digital',label:'数字员工',icon:'🤖'},{id:'human',label:'人类员工',icon:'👤'},{id:'activity',label:'人类动态',icon:'📊'},{id:'timeline',label:'执行时间线',icon:'⏱'},{id:'variance',label:'日计划 vs 实绩',icon:'◢'}];
  return <section className="m09"><ModuleHeader title="M09 动态计划" subtitle="监控数字员工与人类员工的计划执行、偏差和协同状态" /><main className="m09-content"><nav className="m09-tabs">{tabs.map(tab => <button key={tab.id} className={view===tab.id?'active':''} onClick={()=>setView(tab.id)}><span>{tab.icon}</span>{tab.label}</button>)}</nav>{view==='digital'&&<Digital open={setDetailId}/>} {view==='human'&&<Human open={setDetailId}/>} {view==='activity'&&<ActivityView/>} {view==='timeline'&&<Timeline/>} {view==='variance'&&<Variance plans={plans} open={setDetailId} jump={jump} repair={repair} editable={canEdit(role)}/>}</main>{plan&&<PlanDetail plan={plan} close={()=>setDetailId(null)} jump={jump} update={update} repair={repair} editable={canEdit(role)}/>} {notice&&<div className="m09-notice">{notice}<button onClick={()=>setNotice('')}>关闭</button></div>}</section>;
}

function Shift({ human=false }: { human?: boolean }) { return <section className="m09-shift"><b>☀️ 早班 08:00–16:00</b>{human?<><span>在岗 <em>14/18</em></span><span>忙碌 <strong>5</strong></span><span>空闲 <strong>6</strong></span><span>离线 <strong>4</strong></span></>:<><span>在岗数字员工 <em>18/24</em></span><span>执行中 <strong>12</strong></span><span>待命 <strong>4</strong></span><span>空闲 <strong>2</strong></span></>}<small>↻ 数据刷新于 2 秒前</small></section> }
function Digital({ open }: { open:(id:string)=>void }) { return <><Shift/><section className="m09-agent-grid">{agentCards.map((agent,index)=><button className={`m09-agent-card ${agent.tone}`} key={agent.name} onClick={()=>open(index%2?'PLAN-8818':'PLAN-8821')}><header><span>{agent.icon}</span><div><b>{agent.name} <small>{agent.version}</small></b><p>{agent.layer} · {agent.department}</p></div><i>{agent.status}</i></header><div className="m09-card-body"><strong>📌 当前任务：{agent.task}</strong><label><span>今日进度</span><span>{agent.progress||'—'}{agent.progress?'%':''}</span></label><progress value={agent.progress} max="100"/><footer>{agent.metrics.map(metric=><span key={metric}>{metric}</span>)}</footer></div></button>)}</section></> }
function Human({ open }: { open:(id:string)=>void }) { return <><Shift human/><section className="m09-workforce"><b>👷 今日战力构成</b><div><span>🤖 数字员工 18（56%）</span><span>👤 人类员工 14（44%）</span></div><small>数字员工处理标准化、重复性任务；人类员工负责策略决策、异常处理与关系管理</small></section><section className="m09-human-grid">{humanCards.map((person,index)=><button className="m09-human-card" key={person.name} onClick={()=>open(index%2?'PLAN-8818':'PLAN-8821')}><header><i>{person.avatar}</i><div><b>{person.name} <small>{person.role}</small></b><p>{person.org}</p></div><em className={person.state}>{person.state}</em></header><section><strong>📌 当前：{person.current}</strong>{person.items.map(item=><span key={item}>• {item}</span>)}</section><footer>{person.footer.map(item=><small key={item}>{item}</small>)}</footer></button>)}</section></> }
function ActivityView() { return <><section className="m09-section-title"><div><b>📊 人类员工今日使用动态</b><span>记录人机协作全过程 · Agent调用 · Token消耗 · 产出成果</span></div><select><option>全部员工</option><option>业务负责人</option><option>AI训练师</option></select></section><section className="m09-kpis"><Kpi label="今日人-Agent交互" value="186次" note="对话142 · 指令32 · 审批12"/><Kpi label="今日Token消耗" value="48.6万" note="占平台总量25.8%"/><Kpi label="人类决策次数" value="24次" note="审批12 · 驳回3 · 修改9"/><Kpi label="平均响应效率" value="4.2min" note="从Agent请求到人类决策"/></section><section className="m09-activity-grid">{activityGroups.map(group=><article key={group.name}><header><b>👤 {group.name} · 今日动态</b><span>{group.role}</span></header><table><thead><tr><th>时间</th><th>使用的Agent</th><th>操作内容</th><th>Token</th></tr></thead><tbody>{group.rows.map(row=><tr key={row.join('-')}>{row.map((cell,index)=><td key={`${row[0]}-${index}`}>{cell}</td>)}</tr>)}</tbody><tfoot><tr><td colSpan={2}>今日使用Agent：{group.rows.length}个</td><td>Token消耗：{group.total}</td><td>{group.output}</td></tr></tfoot></table></article>)}</section><section className="m09-summary"><h3>📊 今日人类员工总结</h3><table><thead><tr><th>员工</th><th>岗位</th><th>交互次数</th><th>使用Agent数</th><th>Token消耗</th><th>决策次数</th><th>核心产出</th></tr></thead><tbody>{[['李明远','AI平台VP','6','4','70,500','6','审批3项·策略指导2次'],['张伟国','CEO','3','2','24,800','2','董事会汇报准备·RaaS试点审阅'],['王晓芳','客服事业部负责人','5','3','30,800','4','质检20条·处理工单1项'],['赵志强','线索事业部负责人','4','3','37,200','3','根因分析·策略调整'],['陈思敏','AI训练师','4','4','28,300','—','标注86条·修复8用例·3文档']].map(row=><tr key={row[0]}>{row.map((cell,index)=><td key={`${row[0]}-${index}`}>{cell}</td>)}</tr>)}</tbody></table></section></> }
function Timeline() { return <><section className="m09-timeline-grid"><article className="m09-panel"><header><b>📊 今日 Agent 执行甘特图</b><span>08:00 — 18:00</span></header><div className="m09-gantt">{gantt.map(row=><div className="m09-gantt-row" key={row[0]}><label>{row[0]}</label><div><span className={row[4]} style={{left:`${row[2]}%`,width:`${row[3]}%`}}>{row[1]}</span></div></div>)}<i className="m09-now"/></div><footer className="m09-time-axis"><span>08:00</span><span>10:00</span><span className="now">现在 10:48</span><span>14:00</span><span>16:00</span><span>18:00</span></footer></article><article className="m09-panel"><header><b>📜 实时执行动态</b><span className="live">● 实时推送中</span></header><div className="m09-log">{liveLogs.map(log=><div key={log[0]}><time>{log[0]}</time><i className={log[1].toLowerCase()}>{log[1]}</i><span>{log[2]}</span></div>)}</div></article></section><section className="m09-panel m09-moments"><header><b>🕐 今日关键节点</b></header>{moments.map((item,index)=><div className={index<4?'done':index<6?'active':''} key={item[0]}><time>{item[0]}</time><span><b>{item[1]}</b> — {item[2]}</span></div>)}</section></> }
function Variance({ plans, open, jump, repair, editable }: { plans:DynamicPlan[]; open:(id:string)=>void; jump:(p:DynamicPlan,t:string)=>void; repair:(p:DynamicPlan,d:PlanDeviation)=>void; editable:boolean }) { return <><section className="m09-variance-head"><b>📐 2026-07-02 日计划执行对比</b><span>早班 08:00–16:00</span><em>☀️ 计划周期</em><small>截至 10:48</small></section><section className="m09-compare"><article><h3>📋 今日计划任务</h3><table><thead><tr><th>序号</th><th>任务</th><th>负责Agent</th><th>计划时间</th><th>预估耗时</th></tr></thead><tbody>{planRows.map((row,index)=><tr key={row[0]}><td>{index+1}</td>{row.slice(0,4).map(cell=><td key={cell}>{cell}</td>)}</tr>)}</tbody></table></article><article><h3>✅ 实绩完成情况</h3><table><thead><tr><th>序号</th><th>任务</th><th>状态</th><th>实际耗时</th><th>偏差</th></tr></thead><tbody>{planRows.map((row,index)=><tr key={row[0]}><td>{index+1}</td><td>{row[0]}</td><td><i className={row[4]==='完成'?'good':'running'}>{row[4]}</i></td><td>{row[5]}</td><td>{row[6]}</td></tr>)}</tbody></table></article></section><section className="m09-kpis"><Kpi label="计划任务总数" value="47" note="覆盖18个数字员工"/><Kpi label="已完成" value="22" note="46.8%完成率"/><Kpi label="执行中" value="17" note="36.2%进行中"/><Kpi label="计划达成率（时间加权）" value="94.5%" note="优于计划"/></section><section className="m09-deviations"><h3>偏差处置（任务本体仍由 M05 管理）</h3>{plans.flatMap(plan=>plan.deviations.map(deviation=><article key={deviation.id}><div><i className={deviation.level}>{deviation.level}</i><b>{deviation.title}</b><small>{plan.runId} · {deviation.status}</small></div><p>{deviation.impact}<br/>{deviation.evidence}</p><footer><button onClick={()=>open(plan.id)}>查看运行</button>{deviation.taskId?<button onClick={()=>jump(plan,deviation.taskId!)}>打开 M05 任务 {deviation.taskId}</button>:editable&&<button className="primary" onClick={()=>repair(plan,deviation)}>创建 M05 修复任务</button>}</footer></article>))}</section></> }
function PlanDetail({ plan, close, jump, update, repair, editable }: { plan:DynamicPlan; close:()=>void; jump:(p:DynamicPlan,t:string)=>void; update:(p:DynamicPlan,a:string)=>void; repair:(p:DynamicPlan,d:PlanDeviation)=>void; editable:boolean }) { return <div className="m09-mask"><section className="m09-detail"><header><div><h2>{plan.workflowName}</h2><p>{plan.runId} · {plan.status} · {plan.trigger}</p></div><button onClick={close}><X/></button></header><section className="m09-kpis"><Kpi label="执行进度" value={`${plan.progress}%`}/><Kpi label="预测完成" value={plan.forecastEnd}/><Kpi label="偏差" value={`${plan.deviations.length}`}/></section><h3>执行步骤与 Trace</h3>{plan.steps.map(step=><div className="m09-detail-step" key={step.id}><i className={step.status}>{step.status}</i><b>{step.name}</b><span>{step.planned} → {step.actual??'待执行'} · {step.owner} · {step.trace}</span></div>)}<h3>关联 M05 任务</h3>{plan.taskRefs.map(task=><button className="m09-task" key={task.id} onClick={()=>jump(plan,task.id)}><b>{task.title}</b><span>{task.status} · {task.id}<ExternalLink size={13}/></span></button>)}<h3>偏差处置</h3>{plan.deviations.map(deviation=><div className="m09-detail-deviation" key={deviation.id}><b>{deviation.title}</b><p>{deviation.evidence}</p>{editable&&deviation.status==='待处置'&&<button className="primary" onClick={()=>repair(plan,deviation)}>创建 M05 修复任务</button>}</div>)}{editable&&<footer className="m09-actions">{plan.status==='已暂停'?<button className="primary" onClick={()=>update({...plan,status:'运行中'},'已恢复运行计划')}><CirclePlay/>恢复运行</button>:<button onClick={()=>update({...plan,status:'已暂停'},'已暂停运行计划')}><CirclePause/>暂停运行</button>}<button onClick={()=>update(plan,'已创建失败节点重试尝试')}><RotateCcw/>重试失败节点</button></footer>}</section></div> }
function Kpi({ label, value, note }: { label:string; value:string; note?:string }) { return <div><small>{label}</small><strong>{value}</strong>{note&&<span>{note}</span>}</div> }
