import React, { useMemo, useState } from 'react';
import { Plus, Search, X } from 'lucide-react';
import { ModuleHeader } from '../../components/ModuleHeader';
import type { RoleId } from '../../types';
import { useDeliveryProjectRegistry } from './delivery-registry-store';
import type { ContractStatus, DeliveryContract, ProjectKind, ProjectRecord, ProjectStatus } from './delivery-types';
import { ProjectWizard } from './ProjectWizard';
import { ProjectWorkbench } from './ProjectWorkbench';
import './delivery.css';

type View='项目台账'|'合同与 SOW'|'AI 产品权益'|'验收与 SLA'|'变更与审计';
const views:View[]=['项目台账','合同与 SOW','AI 产品权益','验收与 SLA','变更与审计'];
const actors:Record<RoleId,string>={employee:'陈屿',business:'李沐',trainer:'周芮',admin:'赵岑',superadmin:'顾川',client:'王琳'};
const contractNext:Partial<Record<ContractStatus,ContractStatus[]>>={草稿:['待审核'],待审核:['草稿','生效'],生效:['暂停','已完成','已终止'],暂停:['生效','已终止'],已完成:['已归档'],已终止:['已归档']};

export function M10DeliveryManagementPage({role}:{role:RoleId}){
  const registry=useDeliveryProjectRegistry();
  const allowed=['business','trainer','admin','superadmin'].includes(role);
  const visibleViews=role==='trainer'?(['项目台账','变更与审计'] as View[]):views;
  const [view,setView]=useState<View>('项目台账');
  const [query,setQuery]=useState('');
  const [kind,setKind]=useState<'全部类型'|ProjectKind>('全部类型');
  const [status,setStatus]=useState<'全部状态'|ProjectStatus>('全部状态');
  const [organization,setOrganization]=useState('全部组织');
  const [contractFilter,setContractFilter]=useState('全部合同');
  const [selectedProject,setSelectedProject]=useState<string|null>(null);
  const [wizardOpen,setWizardOpen]=useState(false);
  const [contractOpen,setContractOpen]=useState(false);
  const [selectedContract,setSelectedContract]=useState<DeliveryContract|null>(null);
  const [notice,setNotice]=useState('');
  const visibleProjects=registry.getVisibleProjects(role,actors[role]);
  const filtered=useMemo(()=>visibleProjects.filter(project=>(!query||`${project.name}${project.id}${project.owner}`.toLowerCase().includes(query.toLowerCase()))&&(kind==='全部类型'||project.kind===kind)&&(status==='全部状态'||project.status===status)&&(organization==='全部组织'||project.organization===organization)&&(contractFilter==='全部合同'||(contractFilter==='未关联合同'?!project.contractId:project.contractId===contractFilter))),[visibleProjects,query,kind,status,organization,contractFilter]);
  const canCreateProject=['business','admin','superadmin'].includes(role);
  const canManageContracts=['admin','superadmin'].includes(role);
  const organizations=Array.from(new Set(registry.projects.map(item=>item.organization)));
  const showNotice=(message:string)=>setNotice(message);
  if(!allowed)return <section className="m10-gate"><h1>M10 交付与项目管理受限</h1><p>{role==='client'?'客户管理员后续通过 M17 客户门户查看本租户交付、验收和 SLA。':'员工通过 M04 工作空间查看本人参与项目，不进入项目主数据管理。'}</p></section>;
  if(selectedProject)return <ProjectWorkbench key={selectedProject} projectId={selectedProject} role={role} onBack={()=>setSelectedProject(null)} onOpenProject={setSelectedProject} notice={showNotice}/>;
  return <section className="m10" data-module="delivery-management">
    <ModuleHeader title="M10 交付与项目管理" subtitle="从合同与 SOW 建立项目，统一成员、能力、验收和 SLA 主数据" actions={canCreateProject?<button className="m10-primary" onClick={()=>setWizardOpen(true)}><Plus size={15}/>新建项目</button>:<span className="m10-readonly">当前身份仅查看参与项目</span>}/>
    {notice&&<div className="m10-notice" role="status"><span>{notice}</span><button onClick={()=>setNotice('')}>关闭</button></div>}
    <nav className="m10-tabs">{visibleViews.map(item=><button key={item} className={view===item?'active':''} onClick={()=>setView(item)}>{item}</button>)}</nav>
    <main className="m10-content">
      {view==='项目台账'&&<><section className="m10-toolbar"><label><Search size={15}/><input aria-label="搜索项目" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索项目名称、ID 或负责人"/></label><select aria-label="项目类型" value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option>全部类型</option><option>客户交付项目</option><option>内部运营项目</option><option>能力优化项目</option></select><select aria-label="项目状态" value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option>全部状态</option><option>草稿</option><option>待审批</option><option>进行中</option><option>已暂停</option><option>待验收</option><option>已完成</option><option>已归档</option></select><select aria-label="所属组织" value={organization} onChange={e=>setOrganization(e.target.value)}><option>全部组织</option>{organizations.map(item=><option key={item}>{item}</option>)}</select><select aria-label="合同关联" value={contractFilter} onChange={e=>setContractFilter(e.target.value)}><option>全部合同</option><option>未关联合同</option>{registry.contracts.map(item=><option value={item.id} key={item.id}>{item.id}</option>)}</select><small>共 {filtered.length} 个项目</small></section><ProjectTable projects={filtered} contracts={registry.contracts} open={setSelectedProject}/></>}
      {view==='合同与 SOW'&&<ContractsView contracts={registry.contracts} projects={registry.projects} canManage={canManageContracts} onCreate={()=>setContractOpen(true)} onOpen={setSelectedContract}/>} 
      {view==='AI 产品权益'&&<ProductsView products={registry.products} contracts={registry.contracts} projects={registry.projects} openProject={setSelectedProject}/>} 
      {view==='验收与 SLA'&&<AcceptanceView projects={visibleProjects} openProject={setSelectedProject}/>} 
      {view==='变更与审计'&&<AuditView projects={visibleProjects}/>} 
    </main>
    {wizardOpen&&<ProjectWizard role={role} onClose={()=>setWizardOpen(false)} onCreated={id=>{setWizardOpen(false);setSelectedProject(id);}} notice={showNotice}/>} 
    {contractOpen&&<ContractModal role={role} close={()=>setContractOpen(false)} notice={showNotice}/>}
    {selectedContract&&<ContractDetail contractId={selectedContract.id} role={role} canManage={canManageContracts} close={()=>setSelectedContract(null)} notice={showNotice}/>}
  </section>;
}

function ProjectTable({projects,contracts,open}:{projects:ProjectRecord[];contracts:DeliveryContract[];open:(id:string)=>void}){return <section className="m10-table project-table"><div><b>项目名称 / ID</b><b>类型</b><b>组织 / 负责人</b><b>合同 / SOW</b><b>阶段与进度</b><b>成员 / Agent</b><b>状态</b><b>操作</b></div>{projects.map(project=>{const contract=contracts.find(item=>item.id===project.contractId);return <div key={project.id} onClick={()=>open(project.id)}><span><strong>{project.name}</strong><small>{project.id}</small></span><span>{project.kind}</span><span><strong>{project.organization}</strong><small>{project.owner}</small></span><span><strong>{contract?.id||'内部立项'}</strong><small>{project.sowId||project.basis||'—'}</small></span><span><strong>{project.stage}</strong><small><i style={{width:`${project.progress}%`}}/>{project.progress}% · {project.milestones.filter(item=>item.status==='已完成').length}/{project.milestones.length} 里程碑</small></span><span>{project.members.length} 人 / {project.bindings.filter(item=>item.kind==='Agent').length} Agent</span><span><em className={`m10-status s-${project.status}`}>{project.status}</em></span><span><button onClick={event=>{event.stopPropagation();open(project.id);}}>进入工作台</button></span></div>})}{!projects.length&&<p className="m10-empty-row">没有符合筛选条件的项目。</p>}</section>}

function ContractsView({contracts,projects,canManage,onCreate,onOpen}:{contracts:DeliveryContract[];projects:ProjectRecord[];canManage:boolean;onCreate:()=>void;onOpen:(item:DeliveryContract)=>void}){return <section className="m10-panel"><header><div><h3>合同与 SOW</h3><p>维护交付范围、租户和产品权益；财务收付继续由外部合同系统处理。</p></div>{canManage&&<button className="m10-primary" onClick={onCreate}><Plus size={14}/>新建合同</button>}</header><div className="m10-table contracts"><div><b>合同 / ID</b><b>客户 / 租户</b><b>SOW</b><b>周期</b><b>产品权益</b><b>关联项目</b><b>状态</b><b>操作</b></div>{contracts.map(item=><div key={item.id} onClick={()=>onOpen(item)}><span><strong>{item.name}</strong><small>{item.id}</small></span><span><strong>{item.customer}</strong><small>{item.tenantId}</small></span><span><strong>{item.sowId}</strong><small>{item.sowScope}</small></span><span>{item.period}</span><span>{item.productIds.length} 项</span><span>{projects.filter(project=>project.contractId===item.id).length} 个项目</span><span><em className={`m10-status s-${item.status}`}>{item.status}</em></span><span><button onClick={event=>{event.stopPropagation();onOpen(item);}}>查看详情</button></span></div>)}</div></section>}

function ProductsView({products,contracts,projects,openProject}:{products:ReturnType<typeof useDeliveryProjectRegistry>['products'];contracts:DeliveryContract[];projects:ProjectRecord[];openProject:(id:string)=>void}){return <section className="m10-panel"><header><div><h3>AI 产品权益</h3><p>引用已发布产品目录，展示合同授权和项目消费关系。</p></div></header><div className="m10-product-grid large">{products.map(product=>{const related=projects.filter(item=>item.productIds.includes(product.id));return <article key={product.id}><header><div><strong>{product.name}</strong><small>{product.id} · {product.version}</small></div><em>{product.status}</em></header><p>{product.capabilityScope}</p><dl><dt>授权租户</dt><dd>{product.tenantIds.join('、')}</dd><dt>关联合同</dt><dd>{contracts.filter(item=>item.productIds.includes(product.id)).length}</dd><dt>消费项目</dt><dd>{related.length}</dd></dl>{related.length?<button onClick={()=>openProject(related[0].id)}>查看项目：{related[0].name}</button>:<span className="m10-hint">暂无项目消费</span>}</article>})}</div></section>}

function AcceptanceView({projects,openProject}:{projects:ProjectRecord[];openProject:(id:string)=>void}){const rows=projects.flatMap(project=>project.acceptance.map(item=>({project,item})));const slas=projects.flatMap(project=>project.slas.map(item=>({project,item})));return <div className="m10-two-col"><section className="m10-panel"><header><div><h3>项目验收</h3><p>验收结论回写项目状态和结项门禁。</p></div></header><div className="m10-list">{rows.map(({project,item})=><button key={item.id} onClick={()=>openProject(project.id)}><div><strong>{item.item}</strong><small>{project.name} · {item.id}</small><p>{item.evidence}</p></div><span className={`m10-status s-${item.status}`}>{item.status}</span></button>)}</div></section><section className="m10-panel"><header><div><h3>SLA 履约</h3><p>指标异常与 M12 工单形成处置闭环。</p></div></header><div className="m10-list">{slas.map(({project,item})=><button key={item.id} onClick={()=>openProject(project.id)}><div><strong>{item.metric}</strong><small>{project.name} · {item.id}</small><p>目标 {item.target} · 实际 {item.actual}</p></div><span className={`m10-status s-${item.status}`}>{item.status}</span></button>)}</div></section></div>}

function AuditView({projects}:{projects:ProjectRecord[]}){const events=projects.flatMap(project=>project.audit.map(item=>({project,item}))).sort((a,b)=>a.item.time.localeCompare(b.item.time));return <section className="m10-panel"><header><div><h3>交付与项目变更审计</h3><p>状态、成员、资产绑定、验收和结项记录不可修改或删除。</p></div></header><div className="m10-table audit"><div><b>时间</b><b>项目</b><b>操作</b><b>摘要</b><b>操作人</b><b>审计 ID</b></div>{events.map(({project,item})=><div key={item.id}><span>{item.time}</span><span><strong>{project.name}</strong><small>{project.id}</small></span><span>{item.action}</span><span>{item.summary}</span><span>{item.actor}</span><span>{item.id}</span></div>)}</div></section>}

function ContractModal({role,close,notice}:{role:RoleId;close:()=>void;notice:(message:string)=>void}){const registry=useDeliveryProjectRegistry();const [draft,setDraft]=useState<Omit<DeliveryContract,'id'>>({name:'',customer:'',tenantId:'',productIds:[registry.products[0].id],sowId:'',sowScope:'',period:'2026-08-10 ～ 2027-08-09',billingRef:'',owner:actors[role],status:'草稿'});const save=()=>{const result=registry.createContract(draft,actors[role]);notice(result.message);if(result.ok)close();};return <div className="m10-mask" onMouseDown={close}><section className="m10-modal" onMouseDown={event=>event.stopPropagation()}><header><div><h2>新建交付合同</h2><p>创建草稿后进入审核与生效流程</p></div><button onClick={close}><X size={18}/></button></header><main><div className="m10-form-grid"><label>合同名称 *<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>客户名称 *<input value={draft.customer} onChange={e=>setDraft({...draft,customer:e.target.value})}/></label><label>租户 ID *<input value={draft.tenantId} onChange={e=>setDraft({...draft,tenantId:e.target.value})}/></label><label>AI 产品<select value={draft.productIds[0]} onChange={e=>setDraft({...draft,productIds:[e.target.value]})}>{registry.products.map(item=><option key={item.id} value={item.id}>{item.name} · {item.version}</option>)}</select></label><label>SOW ID *<input value={draft.sowId} onChange={e=>setDraft({...draft,sowId:e.target.value})}/></label><label>合同周期 *<input value={draft.period} onChange={e=>setDraft({...draft,period:e.target.value})}/></label><label className="wide">SOW 交付范围 *<textarea value={draft.sowScope} onChange={e=>setDraft({...draft,sowScope:e.target.value})}/></label><label>计费关联 ID<input value={draft.billingRef} onChange={e=>setDraft({...draft,billingRef:e.target.value})}/></label><label>合同负责人<input value={draft.owner} onChange={e=>setDraft({...draft,owner:e.target.value})}/></label></div><footer><button onClick={close}>取消</button><button className="m10-primary" onClick={save}>保存合同草稿</button></footer></main></section></div>}

function ContractDetail({contractId,role,canManage,close,notice}:{contractId:string;role:RoleId;canManage:boolean;close:()=>void;notice:(message:string)=>void}){const registry=useDeliveryProjectRegistry();const contract=registry.contracts.find(item=>item.id===contractId);const [editing,setEditing]=useState(false);const [draft,setDraft]=useState<DeliveryContract|undefined>(contract);if(!contract||!draft)return null;const save=()=>{const result=registry.updateContract(contract.id,draft,actors[role]);notice(result.message);if(result.ok)setEditing(false);};const transition=(status:ContractStatus)=>{const result=registry.transitionContract(contract.id,status,actors[role]);notice(result.message);};const remove=()=>{const result=registry.deleteContract(contract.id);notice(result.message);if(result.ok)close();};return <div className="m10-mask" onMouseDown={close}><section className="m10-contract-detail" onMouseDown={event=>event.stopPropagation()}><header><div><h2>{contract.name}</h2><p>{contract.id} · {contract.customer} · {contract.status}</p></div><button onClick={close}><X size={18}/></button></header><main>{editing?<div className="m10-form-grid"><label>合同名称<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>负责人<input value={draft.owner} onChange={e=>setDraft({...draft,owner:e.target.value})}/></label><label className="wide">SOW 范围<textarea value={draft.sowScope} onChange={e=>setDraft({...draft,sowScope:e.target.value})}/></label></div>:<dl className="m10-detail-grid"><dt>客户 / 租户</dt><dd>{contract.customer} / {contract.tenantId}</dd><dt>SOW</dt><dd>{contract.sowId}</dd><dt>交付范围</dt><dd>{contract.sowScope}</dd><dt>合同周期</dt><dd>{contract.period}</dd><dt>计费关联</dt><dd>{contract.billingRef}</dd><dt>负责人</dt><dd>{contract.owner}</dd><dt>产品权益</dt><dd>{contract.productIds.map(id=>registry.products.find(item=>item.id===id)?.name||id).join('、')}</dd><dt>关联项目</dt><dd>{registry.projects.filter(item=>item.contractId===contract.id).map(item=>item.name).join('、')||'暂无'}</dd></dl>}<footer>{editing?<><button onClick={()=>{setDraft(contract);setEditing(false);}}>取消</button><button className="m10-primary" onClick={save}>保存修改</button></>:<>{canManage&&contract.status==='草稿'&&<button onClick={()=>{setDraft(contract);setEditing(true);}}>编辑草稿</button>}{canManage&&(contractNext[contract.status]||[]).map(status=><button key={status} className={status==='生效'?'m10-primary':status==='已终止'?'danger':''} onClick={()=>transition(status)}>{status}</button>)}{canManage&&contract.status==='草稿'&&<button className="danger" onClick={remove}>删除草稿</button>}</>}</footer></main></section></div>}
