import React, { useMemo, useState } from 'react';
import { ArrowLeft, Plus, X } from 'lucide-react';
import type { RoleId } from '../../types';
import { bindableAssets } from './delivery-data';
import { useDeliveryProjectRegistry } from './delivery-registry-store';
import type { ProjectEvent, ProjectMember, ProjectMilestone, ProjectRecord } from './delivery-types';
import { M10TermHelp } from './M10TermHelp';

type Tab='项目概览'|'合同与范围'|'里程碑'|'成员与职责'|'Agent 与能力'|'知识、数据与内容'|'验收与 SLA'|'动态与审计';
const tabs:Tab[]=['项目概览','合同与范围','里程碑','成员与职责','Agent 与能力','知识、数据与内容','验收与 SLA','动态与审计'];
const actor:Record<RoleId,string>={employee:'陈屿',business:'李沐',trainer:'周芮',admin:'赵岑',superadmin:'顾川',client:'王琳'};
const eventLabels:Partial<Record<ProjectEvent,string>>={submit:'提交审批',withdraw:'撤回',approve:'审批通过并启动',reject:'驳回',pause:'暂停项目',resume:'恢复项目', 'request-acceptance':'提交验收',complete:'确认结项',archive:'归档项目','restore-draft':'恢复为新草稿'};

function projectEvents(project:ProjectRecord,role:RoleId):ProjectEvent[]{
  if(role==='trainer')return [];
  if(project.status==='草稿')return role==='business'||role==='admin'||role==='superadmin'?['submit']:[];
  if(project.status==='待审批')return role==='admin'||role==='superadmin'?['approve','reject']:['withdraw'];
  if(project.status==='进行中')return role==='business'||role==='admin'||role==='superadmin'?['pause','request-acceptance']:[];
  if(project.status==='已暂停')return ['resume'];
  if(project.status==='待验收')return role==='business'||role==='admin'||role==='superadmin'?['complete','reject']:[];
  if(project.status==='已完成')return role==='admin'||role==='superadmin'?['archive']:[];
  if(project.status==='已归档')return role==='superadmin'?['restore-draft']:[];
  return [];
}

export function ProjectWorkbench({projectId,role,onBack,onOpenProject,notice}:{projectId:string;role:RoleId;onBack:()=>void;onOpenProject:(id:string)=>void;notice:(message:string)=>void}){
  const registry=useDeliveryProjectRegistry();
  const project=registry.getProject(projectId);
  const [tab,setTab]=useState<Tab>('项目概览');
  const [editOpen,setEditOpen]=useState(false);
  const [memberOpen,setMemberOpen]=useState(false);
  const [bindingOpen,setBindingOpen]=useState(false);
  const [milestoneOpen,setMilestoneOpen]=useState(false);
  const [selectedAsset,setSelectedAsset]=useState(bindableAssets[0].id);
  const [memberDraft,setMemberDraft]=useState<ProjectMember>({id:'',name:'',role:'项目成员',organization:'DNDC线索中心',responsibility:'项目协作',dataScope:'项目只读',validTo:'2026-12-31'});
  const [milestoneDraft,setMilestoneDraft]=useState<ProjectMilestone>({id:'',name:'',owner:project?.owner||'',dueAt:'2026-09-30',status:'未开始',acceptance:'',result:''});
  const [patch,setPatch]=useState({name:project?.name||'',goal:project?.goal||'',owner:project?.owner||'',organization:project?.organization||'',period:project?.period||'',stage:project?.stage||''});
  const contract=registry.contracts.find(item=>item.id===project?.contractId);
  const products=useMemo(()=>project?.productIds.map(id=>registry.products.find(item=>item.id===id)).filter(Boolean)||[],[project,registry.products]);
  if(!project)return <section className="m10-empty"><h2>项目不存在</h2><button onClick={onBack}>返回项目台账</button></section>;
  const canManageProject=['business','admin','superadmin'].includes(role);
  const canManageBindings=['trainer','admin','superadmin'].includes(role);
  const run=(event:ProjectEvent)=>{const result=registry.transitionProject(project.id,event,actor[role]);notice(result.message);if(result.id&&event==='restore-draft')onOpenProject(result.id);};
  const saveEdit=()=>{const result=registry.updateProject(project.id,patch,actor[role]);notice(result.message);if(result.ok)setEditOpen(false);};
  const addMember=()=>{if(!memberDraft.name.trim()){notice('请输入成员姓名。');return;}const result=registry.addMember(project.id,{...memberDraft,id:memberDraft.id||`USR-${Date.now()}`},actor[role]);notice(result.message);if(result.ok)setMemberOpen(false);};
  const addBinding=()=>{const asset=bindableAssets.find(item=>item.id===selectedAsset);if(!asset)return;const result=registry.bindAsset(project.id,{...asset,status:'已绑定',purpose:'项目授权能力',scope:'项目成员范围'},actor[role]);notice(result.message);if(result.ok)setBindingOpen(false);};
  const addMilestone=()=>{const result=registry.addMilestone(project.id,{...milestoneDraft,id:milestoneDraft.id||`MS-${project.milestones.length+1}`},actor[role]);notice(result.message);if(result.ok){setMilestoneOpen(false);setMilestoneDraft({id:'',name:'',owner:project.owner,dueAt:'2026-09-30',status:'未开始',acceptance:'',result:''});}};
  const deleteDraft=()=>{const result=registry.deleteProject(project.id);notice(result.message);if(result.ok)onBack();};
  return <section className="m10-workbench">
    <header className="m10-object-header"><button onClick={onBack}><ArrowLeft size={16}/>返回项目台账</button><div><h2>{project.name}</h2><p>{project.id} · {project.kind} · {project.organization}</p></div><span className={`m10-status s-${project.status}`}>{project.status}</span>{project.status==='草稿'&&canManageProject&&<button onClick={()=>setEditOpen(true)}>编辑草稿</button>}</header>
    <nav className="m10-workbench-tabs">{tabs.map(item=><span className="m10-tab-item" key={item}><button className={`m10-tab-button ${tab===item?'active':''}`} onClick={()=>setTab(item)}>{item}</button>{item==='里程碑'&&<M10TermHelp term="MILESTONE" label={item}/>} {item==='验收与 SLA'&&<M10TermHelp term="SLA" label={item}/>}</span>)}</nav>
    <main className="m10-workbench-content">
      {tab==='项目概览'&&<><section className="m10-kpis"><article><b>{project.progress}%</b><span>总体进度</span></article><article><b>{project.milestones.filter(item=>item.status==='已完成').length}/{project.milestones.length}</b><span>完成里程碑 <M10TermHelp term="MILESTONE"/></span></article><article><b>{project.taskCount}</b><span>关联任务</span></article><article><b>{project.bindings.filter(item=>item.kind==='Agent').length}</b><span>参与 Agent</span></article></section><section className="m10-panel"><header><div><h3>项目主数据</h3><p>M10 维护；M04 以成员使用视图只读投影。</p></div></header><dl className="m10-detail-grid"><dt>项目目标</dt><dd>{project.goal}</dd><dt>项目负责人</dt><dd>{project.owner}</dd><dt>所属组织</dt><dd>{project.organization}</dd><dt>项目周期</dt><dd>{project.period}</dd><dt>当前阶段</dt><dd>{project.stage}</dd><dt>立项来源</dt><dd>{project.kind==='客户交付项目'?`${project.contractId} / ${project.sowId}`:project.basis}</dd></dl></section><section className="m10-panel"><header><div><h3>生命周期操作 <M10TermHelp term="ACCEPTANCE_GATE"/></h3><p>非法状态转换会被明确阻止并保留当前状态。</p></div></header><div className="m10-action-row">{projectEvents(project,role).map(event=><button key={event} className={event==='approve'||event==='request-acceptance'?'m10-primary':event==='reject'||event==='archive'?'danger':''} onClick={()=>run(event)}>{eventLabels[event]}</button>)}{project.status==='草稿'&&canManageProject&&<button className="danger" onClick={deleteDraft}>删除草稿</button>}{!projectEvents(project,role).length&&<span>当前身份或状态没有可执行的生命周期动作。</span>}</div></section></>}
      {tab==='合同与范围'&&<section className="m10-panel"><header><div><h3>{project.kind==='客户交付项目'?<>合同、SOW 与交付范围 <M10TermHelp term="SOW"/></>:'内部立项依据'}</h3><p>项目只引用合同和计费 ID，不在此处理报价、收款或发票。</p></div></header>{contract?<><dl className="m10-detail-grid"><dt>合同</dt><dd>{contract.name} · {contract.id}</dd><dt>客户 / 租户 <M10TermHelp term="TENANT"/></dt><dd>{contract.customer} / {contract.tenantId}</dd><dt>SOW <M10TermHelp term="SOW"/></dt><dd>{contract.sowId}</dd><dt>交付范围</dt><dd>{contract.sowScope}</dd><dt>合同周期</dt><dd>{contract.period}</dd><dt>计费关联</dt><dd>{contract.billingRef}</dd></dl><div className="m10-product-grid">{products.map(product=><article key={product!.id}><strong>{product!.name}</strong><span>{product!.id} · {product!.version}</span><p>{product!.capabilityScope}</p><em>{product!.status}</em></article>)}</div></>:<dl className="m10-detail-grid"><dt>项目类型</dt><dd>{project.kind}</dd><dt>立项依据</dt><dd>{project.basis}</dd><dt>合同要求</dt><dd>内部项目不强制关联合同</dd><dt>产品引用</dt><dd>{products.map(item=>item!.name).join('、')||'无'}</dd></dl>}</section>}
      {tab==='里程碑'&&<section className="m10-panel"><header><div><h3>项目里程碑 <M10TermHelp term="MILESTONE"/></h3><p>完成条件与实际结果共同构成验收证据。</p></div>{canManageProject&&<button onClick={()=>setMilestoneOpen(true)}><Plus size={14}/>新增里程碑</button>}</header><div className="m10-list">{project.milestones.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.id} · 负责人 {item.owner} · 截止 {item.dueAt}</small><p>完成条件：{item.acceptance}</p>{item.result&&<p>实际结果：{item.result}</p>}</div><span className={`m10-status s-${item.status}`}>{item.status}</span>{canManageProject&&<select value={item.status} onChange={event=>notice(registry.updateMilestone(project.id,item.id,event.target.value as typeof item.status,actor[role]).message)}><option>未开始</option><option>进行中</option><option>已完成</option><option>逾期</option></select>}</article>)}{!project.milestones.length&&<p className="m10-empty-row">尚未配置里程碑。</p>}</div></section>}
      {tab==='成员与职责'&&<section className="m10-panel"><header><div><h3>项目成员与职责</h3><p>成员关系决定 M04 项目可见范围和字段权限。</p></div>{canManageProject&&<button onClick={()=>setMemberOpen(true)}><Plus size={14}/>添加成员</button>}</header><div className="m10-table"><div><b>成员</b><b>项目角色</b><b>组织</b><b>职责</b><b>数据范围</b><b>有效期</b><b>操作</b></div>{project.members.map(member=><div key={member.id}><span><strong>{member.name}</strong><small>{member.id}</small></span><span>{member.role}</span><span>{member.organization}</span><span>{member.responsibility}</span><span>{member.dataScope}</span><span>{member.validTo}</span><span>{canManageProject?<button className="danger" onClick={()=>notice(registry.removeMember(project.id,member.id,actor[role]).message)}>移除</button>:'只读'}</span></div>)}</div></section>}
      {tab==='Agent 与能力'&&<BindingPanel project={project} kinds={['Agent','Skill','Tool']} canManage={canManageBindings} onAdd={()=>setBindingOpen(true)} onRemove={id=>notice(registry.removeBinding(project.id,id,actor[role]).message)}/>}
      {tab==='知识、数据与内容'&&<BindingPanel project={project} kinds={['知识','数据','内容']} canManage={canManageBindings} onAdd={()=>setBindingOpen(true)} onRemove={id=>notice(registry.removeBinding(project.id,id,actor[role]).message)}/>}
      {tab==='验收与 SLA'&&<div className="m10-two-col"><section className="m10-panel"><header><div><h3>验收清单 <M10TermHelp term="ACCEPTANCE_GATE"/></h3><p>业务结论必须具备可追溯证据。</p></div></header><div className="m10-list">{project.acceptance.map(item=><article key={item.id}><div><strong>{item.item}</strong><small>{item.id} · 负责人 {item.owner}</small><p>证据：{item.evidence}</p><p>结论：{item.conclusion}</p></div><span className={`m10-status s-${item.status}`}>{item.status}</span>{canManageProject&&<select value={item.status} onChange={event=>notice(registry.updateAcceptance(project.id,item.id,event.target.value as typeof item.status,actor[role]).message)}><option>待验收</option><option>通过</option><option>不通过</option></select>}</article>)}</div></section><section className="m10-panel"><header><div><h3>SLA 履约 <M10TermHelp term="SLA"/></h3><p>内部项目展示治理目标，客户项目展示合同 SLA。</p></div></header><div className="m10-list">{project.slas.map(item=><article key={item.id}><div><strong>{item.metric}</strong><small>{item.id}</small><p>目标 {item.target} · 实际 {item.actual}</p><p>{item.handling}</p></div><span className={`m10-status s-${item.status}`}>{item.status}</span></article>)}</div></section></div>}
      {tab==='动态与审计'&&<section className="m10-panel"><header><div><h3>项目动态与不可变审计</h3><p>状态、成员、绑定、里程碑和验收操作均写入证据链。</p></div></header><div className="m10-audit">{project.audit.map(item=><article key={item.id}><time>{item.time}</time><div><strong>{item.action}</strong><p>{item.summary}</p><small>{item.actor} · {item.id}</small></div></article>)}</div></section>}
    </main>
    {editOpen&&<Modal title="编辑项目草稿" close={()=>setEditOpen(false)}><div className="m10-form-grid"><label>项目名称<input value={patch.name} onChange={e=>setPatch({...patch,name:e.target.value})}/></label><label>负责人<input value={patch.owner} onChange={e=>setPatch({...patch,owner:e.target.value})}/></label><label className="wide">目标<textarea value={patch.goal} onChange={e=>setPatch({...patch,goal:e.target.value})}/></label><label>所属组织<input value={patch.organization} onChange={e=>setPatch({...patch,organization:e.target.value})}/></label><label>周期<input value={patch.period} onChange={e=>setPatch({...patch,period:e.target.value})}/></label><label>阶段<input value={patch.stage} onChange={e=>setPatch({...patch,stage:e.target.value})}/></label></div><footer><button onClick={()=>setEditOpen(false)}>取消</button><button className="m10-primary" onClick={saveEdit}>保存</button></footer></Modal>}
    {memberOpen&&<Modal title="添加项目成员" close={()=>setMemberOpen(false)}><div className="m10-form-grid"><label>姓名 *<input value={memberDraft.name} onChange={e=>setMemberDraft({...memberDraft,name:e.target.value})}/></label><label>项目角色<select value={memberDraft.role} onChange={e=>setMemberDraft({...memberDraft,role:e.target.value})}><option>项目成员</option><option>项目负责人</option><option>AI能力负责人</option><option>治理审批人</option></select></label><label>所属组织<input value={memberDraft.organization} onChange={e=>setMemberDraft({...memberDraft,organization:e.target.value})}/></label><label>数据范围<select value={memberDraft.dataScope} onChange={e=>setMemberDraft({...memberDraft,dataScope:e.target.value})}><option>项目只读</option><option>本人及项目脱敏数据</option><option>项目授权能力</option><option>项目全量业务指标</option></select></label><label className="wide">项目职责<input value={memberDraft.responsibility} onChange={e=>setMemberDraft({...memberDraft,responsibility:e.target.value})}/></label><label>有效期<input type="date" value={memberDraft.validTo} onChange={e=>setMemberDraft({...memberDraft,validTo:e.target.value})}/></label></div><footer><button onClick={()=>setMemberOpen(false)}>取消</button><button className="m10-primary" onClick={addMember}>确认添加</button></footer></Modal>}
    {bindingOpen&&<Modal title="绑定已发布能力资产" close={()=>setBindingOpen(false)}><label><span className="m10-field-label">资产与固定版本 <M10TermHelp term="FIXED_VERSION_BINDING"/></span><select value={selectedAsset} onChange={e=>setSelectedAsset(e.target.value)}>{bindableAssets.map(asset=><option key={asset.id} value={asset.id}>{asset.kind} · {asset.name} · {asset.version}</option>)}</select><small>仅展示已发布且健康的资产；保存后不随最新版本自动漂移。</small></label><footer><button onClick={()=>setBindingOpen(false)}>取消</button><button className="m10-primary" onClick={addBinding}>确认绑定</button></footer></Modal>}
    {milestoneOpen&&<Modal title="新增里程碑" close={()=>setMilestoneOpen(false)}><div className="m10-form-grid"><label><span className="m10-field-label">里程碑名称 * <M10TermHelp term="MILESTONE"/></span><input value={milestoneDraft.name} onChange={e=>setMilestoneDraft({...milestoneDraft,name:e.target.value})}/></label><label>负责人 *<input value={milestoneDraft.owner} onChange={e=>setMilestoneDraft({...milestoneDraft,owner:e.target.value})}/></label><label>截止日期 *<input type="date" value={milestoneDraft.dueAt} onChange={e=>setMilestoneDraft({...milestoneDraft,dueAt:e.target.value})}/></label><label>初始状态<select value={milestoneDraft.status} onChange={e=>setMilestoneDraft({...milestoneDraft,status:e.target.value as ProjectMilestone['status']})}><option>未开始</option><option>进行中</option></select></label><label className="wide">完成条件 *<textarea value={milestoneDraft.acceptance} onChange={e=>setMilestoneDraft({...milestoneDraft,acceptance:e.target.value})} placeholder="填写可验证的完成条件与证据要求"/></label></div><footer><button onClick={()=>setMilestoneOpen(false)}>取消</button><button className="m10-primary" onClick={addMilestone}>创建里程碑</button></footer></Modal>}
  </section>;
}

function BindingPanel({project,kinds,canManage,onAdd,onRemove}:{project:ProjectRecord;kinds:Array<ProjectRecord['bindings'][number]['kind']>;canManage:boolean;onAdd:()=>void;onRemove:(id:string)=>void}){
  const items=project.bindings.filter(item=>kinds.includes(item.kind));
  return <section className="m10-panel"><header><div><h3>{kinds.join('、')}绑定</h3><p>固定资产 ID 和版本，运行中项目变更必须保留审计。</p></div>{canManage&&<button onClick={onAdd}><Plus size={14}/>绑定资产</button>}</header><div className="m10-table bindings"><div><b>类型</b><b>资产</b><b>固定版本 <M10TermHelp term="FIXED_VERSION_BINDING"/></b><b>用途</b><b>授权范围</b><b>状态</b><b>操作</b></div>{items.map(item=><div key={item.id}><span>{item.kind}</span><span><strong>{item.name}</strong><small>{item.id}</small></span><span>{item.version}</span><span>{item.purpose}</span><span>{item.scope}</span><span>{item.status}</span><span>{canManage?<button className="danger" onClick={()=>onRemove(item.id)}>移除</button>:'只读'}</span></div>)}</div>{!items.length&&<p className="m10-empty-row">暂无此类绑定。</p>}</section>;
}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="m10-mask" onMouseDown={close}><section className="m10-modal" onMouseDown={event=>event.stopPropagation()}><header><h2>{title}</h2><button aria-label="关闭" onClick={close}><X size={18}/></button></header><main>{children}</main></section></div>}
