import React, { useMemo, useState } from 'react';
import { Check, ChevronLeft, ChevronRight, Play, X } from 'lucide-react';
import { useToolRegistry } from '../tools/tool-registry-store';
import { useSkillRegistry } from './skill-registry-store';
import { createSkillDraft, type SkillDependency, type SkillRecord, type SkillType } from './skills-data';

const steps = ['基本信息', '指令场景', '输入输出', '能力依赖', '执行治理', '校验保存'];
const promptOptions: SkillDependency[] = [{ id: 'PROMPT-LEAD-12', type: 'Prompt', name: '线索评分偏差诊断', version: 'v2.3', status: '已发布', scope: '生产指令' }, { id: 'PROMPT-RAG-08', type: 'Prompt', name: '证据回答模板', version: 'v1.8', status: '已发布', scope: '生产指令' }];
const knowledgeOptions: SkillDependency[] = [{ id: 'KB-LEAD-001', type: '知识策略', name: '线索判定与跟进规则', version: '2026.08', status: '已发布', scope: '只读检索' }, { id: 'KB-GOV-006', type: '知识策略', name: '治理知识与法规', version: '2026.08', status: '已发布', scope: '混合检索' }];

export function SkillWizard({ existingNames, onClose, onSave }: { existingNames: string[]; onClose: () => void; onSave: (record: SkillRecord) => void }) {
  const tools = useToolRegistry(); const skills = useSkillRegistry();
  const [step, setStep] = useState(0); const [draft, setDraft] = useState<SkillRecord>(() => createSkillDraft('原子', ''));
  const [testState, setTestState] = useState<'idle' | 'running' | 'passed' | 'failed'>('idle'); const [error, setError] = useState('');
  const set = <K extends keyof SkillRecord>(key: K, value: SkillRecord[K]) => setDraft(current => ({ ...current, [key]: value }));
  const duplicate = existingNames.some(name => name.trim().toLowerCase() === draft.name.trim().toLowerCase());
  const assetOptions = useMemo<SkillDependency[]>(() => draft.type === '组合' ? skills.bindableAtomicSkills.map(item => ({ id: item.id, type: '原子 Skill', name: item.name, version: item.currentVersion, status: item.health, scope: `组合步骤 ${draft.dependencies.filter(dep => dep.type === '原子 Skill').length + 1}` })) : [...promptOptions, ...knowledgeOptions, ...tools.bindableTools.map(item => ({ id: item.id, type: 'Tool' as const, name: item.name, version: item.currentVersion, status: item.health, scope: '受控调用' }))], [draft.type, draft.dependencies, skills.bindableAtomicSkills, tools.bindableTools]);
  const validateStep = (targetStep: number) => {
    if (targetStep === 0 && (!draft.name.trim() || !draft.description.trim() || !draft.purpose.trim() || duplicate)) return duplicate ? 'Skill 名称已存在，请使用唯一名称。' : '请填写名称、能力说明和业务用途。';
    if (targetStep === 1 && (!draft.instruction.objective.trim() || !draft.instruction.instruction.trim() || !draft.instruction.boundaries.trim())) return '请完整填写能力目标、执行指令和能力边界。';
    if (targetStep === 2) { try { JSON.parse(draft.contract.outputSchema); JSON.parse(draft.contract.exampleInput); JSON.parse(draft.contract.exampleOutput); } catch { return '输入示例、输出 Schema 或输出示例不是合法 JSON。'; } if (!draft.contract.inputs.length) return '至少需要一个输入参数。'; }
    if (targetStep === 3) { const assets = draft.dependencies.filter(dep => ['Prompt', '知识策略', 'Tool', '原子 Skill'].includes(dep.type)); if (draft.type === '组合' && assets.length < 2) return '组合 Skill 至少选择两个已发布且健康的原子 Skill。'; if (draft.type === '原子' && !assets.length) return '原子 Skill 至少绑定一个 Prompt、知识策略或 Tool。'; }
    if (targetStep === 4 && (draft.policy.timeoutMs < 1000 || draft.policy.concurrency < 1 || !draft.policy.fallback.trim())) return '请配置有效的超时、并发和降级策略。';
    return '';
  };
  const next = () => { const message = validateStep(step); if (message) { setError(message); return; } setError(''); setStep(value => Math.min(5, value + 1)); };
  const toggleDependency = (dependency: SkillDependency) => setDraft(current => ({ ...current, lastTestPassed: false, dependencies: current.dependencies.some(item => item.id === dependency.id) ? current.dependencies.filter(item => item.id !== dependency.id) : [...current.dependencies, dependency] }));
  const changeType = (type: SkillType) => setDraft(current => ({ ...createSkillDraft(type, current.name), description: current.description, purpose: current.purpose, owner: current.owner, department: current.department }));
  const runTest = () => { const messages = [0, 1, 2, 3, 4].map(validateStep).filter(Boolean); if (messages.length) { setError(messages[0]); setTestState('failed'); return; } setTestState('running'); window.setTimeout(() => { setDraft(current => ({ ...current, lifecycle: '测试中', health: '正常', lastTestPassed: true, testPassRate: 100, successRate: 95.6, averageLatency: current.type === '组合' ? '3.2s' : '1.1s', tests: [{ id: `SKILL-RUN-${Date.now()}`, time: '刚刚', result: '通过', score: 94, latency: current.type === '组合' ? '3.2s' : '1.1s', traceId: `TRACE-SKILL-${Date.now().toString().slice(-5)}`, input: current.contract.exampleInput, output: current.contract.exampleOutput, dependencyHits: current.dependencies.map(dep => `${dep.id} ${dep.version || ''}`), retries: 0, fallback: '未触发' }], audit: [{ id: `AUD-${Date.now()}`, time: '刚刚', actor: '周芮', action: '向导试运行通过', evidence: '契约、依赖、权限和输出结构通过' }, ...current.audit] })); setTestState('passed'); setError(''); }, 350); };
  return <div className="tools-modal-mask"><section className="tools-wizard skills-wizard">
    <header><div><h2>新建 Skill</h2><p>声明式能力包 · 已发布版本不可变</p></div><button onClick={onClose} aria-label="关闭"><X /></button></header>
    <ol className="tools-stepper">{steps.map((item, index) => <li key={item} className={index === step ? 'active' : index < step ? 'done' : ''}><span>{index < step ? <Check size={13} /> : index + 1}</span><b>{item}</b></li>)}</ol>
    <div className="tools-wizard-body">{step === 0 && <div className="tools-form-grid"><label>Skill 类型<select value={draft.type} onChange={event => changeType(event.target.value as SkillType)}><option>原子</option><option>组合</option></select></label><label>Skill 名称 *<input value={draft.name} onChange={event => set('name', event.target.value)} placeholder="例如：线索评分偏差诊断" /></label><label>负责人<input value={draft.owner} onChange={event => set('owner', event.target.value)} /></label><label>所属部门<select value={draft.department} onChange={event => set('department', event.target.value)}><option>AIMP能力运营组</option><option>线索事业部</option><option>内容事业部</option><option>用户服务中心</option></select></label><label className="span-2">能力说明 *<textarea value={draft.description} onChange={event => set('description', event.target.value)} /></label><label className="span-2">业务用途 *<textarea value={draft.purpose} onChange={event => set('purpose', event.target.value)} /></label></div>}
      {step === 1 && <div className="tools-form-grid"><label>能力目标 *<input value={draft.instruction.objective} onChange={event => set('instruction', { ...draft.instruction, objective: event.target.value })} /></label><label>适用场景<input value={draft.instruction.scenarios} onChange={event => set('instruction', { ...draft.instruction, scenarios: event.target.value })} /></label><label className="span-2">执行指令 *<textarea value={draft.instruction.instruction} onChange={event => set('instruction', { ...draft.instruction, instruction: event.target.value })} /></label><label>能力边界 *<textarea value={draft.instruction.boundaries} onChange={event => set('instruction', { ...draft.instruction, boundaries: event.target.value })} /></label><label>禁止事项<textarea value={draft.instruction.forbidden} onChange={event => set('instruction', { ...draft.instruction, forbidden: event.target.value })} /></label></div>}
      {step === 2 && <div className="tools-schema-grid"><label>输入示例 JSON<textarea value={draft.contract.exampleInput} onChange={event => set('contract', { ...draft.contract, exampleInput: event.target.value })} /></label><label>输出 Schema JSON<textarea value={draft.contract.outputSchema} onChange={event => set('contract', { ...draft.contract, outputSchema: event.target.value })} /></label><label>输出示例 JSON<textarea value={draft.contract.exampleOutput} onChange={event => set('contract', { ...draft.contract, exampleOutput: event.target.value })} /></label><label>错误码与语义<textarea value={draft.contract.errorCodes} onChange={event => set('contract', { ...draft.contract, errorCodes: event.target.value })} /></label></div>}
      {step === 3 && <div><div className="tools-type-tip"><strong>{draft.type === '组合' ? '组合规则' : '依赖规则'}</strong><small>{draft.type === '组合' ? '只能选择已发布且健康的原子 Skill；禁止组合嵌套和循环依赖。' : '选择已发布 Prompt、知识策略和健康 Tool；源资产仍在各自模块维护。'}</small></div><div className="skills-dependency-picker">{assetOptions.map(item => <label key={item.id}><input type="checkbox" checked={draft.dependencies.some(dep => dep.id === item.id)} onChange={() => toggleDependency(item)} /><span><b>{item.name}</b><small>{item.type} · {item.id} · {item.version} · {item.status}</small></span></label>)}</div></div>}
      {step === 4 && <div className="tools-form-grid"><label>执行模式<select value={draft.policy.mode} onChange={event => set('policy', { ...draft.policy, mode: event.target.value as '顺序' | '并行' })}><option>顺序</option><option>并行</option></select></label><label>超时（ms）<input type="number" value={draft.policy.timeoutMs} onChange={event => set('policy', { ...draft.policy, timeoutMs: Number(event.target.value) })} /></label><label>重试次数<input type="number" value={draft.policy.retries} onChange={event => set('policy', { ...draft.policy, retries: Number(event.target.value) })} /></label><label>并发上限<input type="number" value={draft.policy.concurrency} onChange={event => set('policy', { ...draft.policy, concurrency: Number(event.target.value) })} /></label><label>降级策略<textarea value={draft.policy.fallback} onChange={event => set('policy', { ...draft.policy, fallback: event.target.value })} /></label><label>人工介入<textarea value={draft.policy.humanIntervention} onChange={event => set('policy', { ...draft.policy, humanIntervention: event.target.value })} /></label></div>}
      {step === 5 && <div className="tools-test-summary"><h3>发布前校验</h3><dl><div><dt>Skill 类型</dt><dd>{draft.type} Skill</dd></div><div><dt>契约</dt><dd>输入 {draft.contract.inputs.length} 项 · 输出 Schema 已配置</dd></div><div><dt>能力依赖</dt><dd>{draft.dependencies.length} 项 · {draft.type === '组合' ? '一层组合校验' : '资产版本校验'}</dd></div><div><dt>治理策略</dt><dd>{draft.policy.timeoutMs}ms · 重试 {draft.policy.retries} 次 · 并发 {draft.policy.concurrency}</dd></div><div><dt>试运行</dt><dd>{testState === 'passed' ? '通过 · 评分94 · 契约100%' : testState === 'failed' ? '失败，请修复后重试' : testState === 'running' ? '执行中…' : '尚未执行'}</dd></div></dl><button className="tools-test-button" disabled={testState === 'running'} onClick={runTest}><Play size={14} />运行契约、依赖与安全测试</button></div>}
      {error && <p className="tools-error">{error}</p>}</div>
    <footer><button disabled={step === 0} onClick={() => { setError(''); setStep(value => value - 1); }}><ChevronLeft size={14} />上一步</button><span />{step < 5 ? <button className="tools-primary" onClick={next}>下一步<ChevronRight size={14} /></button> : <button className="tools-primary" disabled={testState !== 'passed'} onClick={() => onSave(draft)}>保存 Skill 草稿</button>}</footer>
  </section></div>;
}
