import React, { useMemo, useState } from 'react';
import { Archive, ArrowLeft, CheckCircle2, Copy, PauseCircle, Play, Plus, RotateCcw, Save, Send, ShieldCheck, Trash2, X, XCircle } from 'lucide-react';
import type { RoleId } from '../../types';
import { useToolRegistry } from '../tools/tool-registry-store';
import { useSkillRegistry, type SkillLifecycleAction } from './skill-registry-store';
import type { SkillDependency, SkillRecord, SkillTestCase, SkillTestRun } from './skills-data';

const tabs = ['基本配置', '指令与契约', '能力依赖', '调试与测试', '适用范围与权限', '版本与审计'] as const;
type Tab = typeof tabs[number];

export function SkillWorkbench({ role, skill, onBack, onSelectSkill }: { role: RoleId; skill: SkillRecord; onBack: () => void; onSelectSkill: (id: string) => void }) {
  const registry = useSkillRegistry(); const [tab, setTab] = useState<Tab>('基本配置'); const [notice, setNotice] = useState(''); const [reasonAction, setReasonAction] = useState<'reject' | null>(null);
  const editable = ['trainer', 'admin', 'superadmin'].includes(role) && ['草稿', '测试中'].includes(skill.lifecycle);
  const act = (action: SkillLifecycleAction, reason = '') => { const result = registry.transition(skill.id, action, role === 'trainer' ? '周芮' : role === 'admin' ? '赵岑' : '顾川', role, reason); setNotice(result.message); if (result.record && result.record.id !== skill.id) onSelectSkill(result.record.id); };
  const remove = () => { const result = registry.remove(skill.id); setNotice(result.message); if (result.ok) onBack(); };
  return <section className="tools-page skills-page">
    <main className="tools-content"><header className="tools-workbench-head"><button className="tools-back" onClick={onBack}><ArrowLeft size={15} />返回目录</button><div><h2>{skill.name}</h2><p>{skill.id} · {skill.currentVersion} · {skill.type} Skill</p></div><div className="tools-workbench-actions">{lifecycleActions(skill, role).map(action => <button key={action.id} className={action.primary ? 'tools-primary' : action.danger ? 'danger' : ''} onClick={() => action.id === 'delete' ? remove() : action.id === 'reject' ? setReasonAction('reject') : act(action.id as SkillLifecycleAction)}>{action.icon}{action.label}</button>)}</div></header>
      <section className="tools-overview"><div className="tools-overview-main"><div><i className="tools-type">{skill.type} Skill</i><i className={`tools-life is-${skill.lifecycle}`}>{skill.lifecycle}</i><i className="tools-risk">风险 {skill.risk}</i></div><h1>{skill.name}</h1><p>{skill.description}</p><small>{skill.owner} · {skill.department} · {skill.purpose}</small></div><div className="tools-metrics"><div><span>测试通过率</span><strong>{skill.testPassRate}%</strong></div><div><span>运行成功率</span><strong>{skill.successRate}%</strong></div><div><span>平均耗时</span><strong>{skill.averageLatency}</strong></div><div><span>健康状态</span><strong className={`tools-health is-${skill.health}`}>● {skill.health}</strong></div></div></section>
      <nav className="tools-tabs">{tabs.map(item => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}</nav>
      <section className="tools-tab-panel">{tab === '基本配置' ? <BasicTab skill={skill} editable={editable} save={(record, message) => { registry.upsert(record, { actor: '当前用户', action: '更新基本配置', evidence: message }); setNotice(message); }} /> : tab === '指令与契约' ? <ContractTab skill={skill} editable={editable} save={record => { registry.upsert(record, { actor: '当前用户', action: '更新指令与契约', evidence: '输入输出 Schema 已重新校验' }); setNotice('指令与契约已保存，发布门禁已重置。'); }} /> : tab === '能力依赖' ? <DependencyTab skill={skill} editable={editable} notice={setNotice} /> : tab === '调试与测试' ? <TestTab skill={skill} writable={editable} notice={setNotice} /> : tab === '适用范围与权限' ? <PermissionTab skill={skill} writable={['admin', 'superadmin'].includes(role)} notice={setNotice} /> : <VersionTab role={role} skill={skill} copy={() => act(skill.lifecycle === '已归档' ? 'restore-draft' : 'copy-draft')} />}</section>
    </main>{notice && <div className="tools-notice">{notice}<button onClick={() => setNotice('')}>关闭</button></div>}{reasonAction && <ReasonDialog title="驳回 Skill" onClose={() => setReasonAction(null)} onConfirm={reason => { act('reject', reason); setReasonAction(null); }} />}
  </section>;
}

function BasicTab({ skill, editable, save }: { skill: SkillRecord; editable: boolean; save: (record: SkillRecord, message: string) => void }) {
  const [draft, setDraft] = useState(skill); const set = <K extends keyof SkillRecord>(key: K, value: SkillRecord[K]) => setDraft(current => ({ ...current, [key]: value, lastTestPassed: false }));
  return <section className="tools-panel"><header><div><h3>基本配置</h3><p>定义 Skill 的责任归属、用途和风险边界。</p></div>{editable && <button className="tools-primary" onClick={() => save(draft, `${skill.id} 基本配置已更新`)}><Save size={14} />保存配置</button>}</header><div className="tools-form-grid"><label>Skill 名称<input disabled={!editable} value={draft.name} onChange={event => set('name', event.target.value)} /></label><label>Skill 类型<select disabled={!editable} value={draft.type} onChange={event => set('type', event.target.value as SkillRecord['type'])}><option>原子</option><option>组合</option></select></label><label>负责人<input disabled={!editable} value={draft.owner} onChange={event => set('owner', event.target.value)} /></label><label>所属部门<select disabled={!editable} value={draft.department} onChange={event => set('department', event.target.value)}><option>AIMP能力运营组</option><option>线索事业部</option><option>内容事业部</option><option>用户服务中心</option></select></label><label className="span-2">能力说明<textarea disabled={!editable} value={draft.description} onChange={event => set('description', event.target.value)} /></label><label className="span-2">业务用途<textarea disabled={!editable} value={draft.purpose} onChange={event => set('purpose', event.target.value)} /></label></div></section>;
}

function ContractTab({ skill, editable, save }: { skill: SkillRecord; editable: boolean; save: (record: SkillRecord) => void }) {
  const [draft, setDraft] = useState(skill); const [error, setError] = useState(''); const updateInstruction = (key: keyof SkillRecord['instruction'], value: string) => setDraft(current => ({ ...current, instruction: { ...current.instruction, [key]: value }, lastTestPassed: false })); const updateContract = (key: keyof SkillRecord['contract'], value: string) => setDraft(current => ({ ...current, contract: { ...current.contract, [key]: value }, lastTestPassed: false }));
  const validateSave = () => { try { JSON.parse(draft.contract.outputSchema); JSON.parse(draft.contract.exampleInput); JSON.parse(draft.contract.exampleOutput); setError(''); save(draft); } catch { setError('JSON 校验失败：输入示例、输出 Schema 和输出示例必须是合法 JSON。'); } };
  return <div className="tools-two-column"><section className="tools-panel"><header><div><h3>能力指令</h3><p>说明 Skill 做什么、何时使用以及不可越过的边界。</p></div></header><div className="tools-form-grid"><label>能力目标<input disabled={!editable} value={draft.instruction.objective} onChange={event => updateInstruction('objective', event.target.value)} /></label><label>适用场景<input disabled={!editable} value={draft.instruction.scenarios} onChange={event => updateInstruction('scenarios', event.target.value)} /></label><label className="span-2">执行指令<textarea disabled={!editable} value={draft.instruction.instruction} onChange={event => updateInstruction('instruction', event.target.value)} /></label><label>能力边界<textarea disabled={!editable} value={draft.instruction.boundaries} onChange={event => updateInstruction('boundaries', event.target.value)} /></label><label>禁止事项<textarea disabled={!editable} value={draft.instruction.forbidden} onChange={event => updateInstruction('forbidden', event.target.value)} /></label></div></section><section className="tools-panel"><header><div><h3>输入输出契约</h3><p>契约必须通过 JSON 校验后才能进入测试。</p></div>{editable && <button className="tools-primary" onClick={validateSave}><Save size={14} />保存并校验</button>}</header><div className="tools-schema-grid"><label>输入示例<textarea disabled={!editable} value={draft.contract.exampleInput} onChange={event => updateContract('exampleInput', event.target.value)} /></label><label>输出 Schema<textarea disabled={!editable} value={draft.contract.outputSchema} onChange={event => updateContract('outputSchema', event.target.value)} /></label><label>输出示例<textarea disabled={!editable} value={draft.contract.exampleOutput} onChange={event => updateContract('exampleOutput', event.target.value)} /></label><label>错误码<textarea disabled={!editable} value={draft.contract.errorCodes} onChange={event => updateContract('errorCodes', event.target.value)} /></label></div>{error && <p className="tools-error">{error}</p>}</section></div>;
}

function DependencyTab({ skill, editable, notice }: { skill: SkillRecord; editable: boolean; notice: (message: string) => void }) {
  const registry = useSkillRegistry(); const tools = useToolRegistry(); const [kind, setKind] = useState(skill.type === '组合' ? '原子 Skill' : 'Prompt'); const [choice, setChoice] = useState('');
  const options = useMemo<SkillDependency[]>(() => kind === '原子 Skill' ? registry.bindableAtomicSkills.filter(item => item.id !== skill.id).map(item => ({ id: item.id, type: '原子 Skill', name: item.name, version: item.currentVersion, status: item.health, scope: `组合步骤 ${skill.dependencies.filter(dep => dep.type === '原子 Skill').length + 1}` })) : kind === 'Tool' ? tools.bindableTools.map(item => ({ id: item.id, type: 'Tool', name: item.name, version: item.currentVersion, status: item.health, scope: '受控调用' })) : kind === '知识策略' ? [{ id: 'KB-LEAD-001', type: '知识策略', name: '线索判定与跟进规则', version: '2026.08', status: '已发布', scope: '只读检索' }, { id: 'KB-GOV-006', type: '知识策略', name: '治理知识与法规', version: '2026.08', status: '已发布', scope: '混合检索' }] as SkillDependency[] : [{ id: 'PROMPT-LEAD-12', type: 'Prompt', name: '线索评分偏差诊断', version: 'v2.3', status: '已发布', scope: '生产指令' }, { id: 'PROMPT-RAG-08', type: 'Prompt', name: '证据回答模板', version: 'v1.8', status: '已发布', scope: '生产指令' }] as SkillDependency[], [kind, registry.bindableAtomicSkills, tools.bindableTools, skill]);
  const assetDeps = skill.dependencies.filter(item => ['Prompt', '知识策略', 'Tool', '原子 Skill'].includes(item.type));
  const add = () => { const item = options.find(value => value.id === choice); if (!item) return; const result = registry.addDependency(skill.id, item); notice(result.message); if (result.ok) setChoice(''); };
  return <section className="tools-panel"><header><div><h3>能力依赖</h3><p>{skill.type === '组合' ? '组合 Skill 只能引用原子 Skill，禁止循环依赖和多层嵌套。' : '原子 Skill 绑定已发布 Prompt、知识策略和健康 Tool。'}</p></div>{editable && <div className="tools-inline-create"><select value={kind} onChange={event => { setKind(event.target.value); setChoice(''); }}>{skill.type === '组合' ? <option>原子 Skill</option> : <><option>Prompt</option><option>知识策略</option><option>Tool</option></>}</select><select value={choice} onChange={event => setChoice(event.target.value)}><option value="">选择已发布依赖</option>{options.filter(item => !assetDeps.some(dep => dep.id === item.id)).map(item => <option key={item.id} value={item.id}>{item.name} · {item.version}</option>)}</select><button className="tools-primary" disabled={!choice} onClick={add}><Plus size={14} />添加</button></div>}</header><div className="tools-dependency-table"><div><b>类型</b><b>依赖资产</b><b>版本</b><b>用途范围</b><b>状态</b><b>操作</b></div>{assetDeps.map(item => <div key={item.id}><i>{item.type}</i><span><b>{item.name}</b><small>{item.id}</small></span><span>{item.version || '—'}</span><span>{item.scope}</span><span>{item.status}</span><span>{editable ? <button className="danger" onClick={() => notice(registry.removeDependency(skill.id, item.id).message)}>移除</button> : '只读'}</span></div>)}{!assetDeps.length && <p className="tools-empty-row">尚未装配能力依赖。</p>}</div><div className="tools-security-note"><ShieldCheck size={18} /><div><strong>依赖快照规则</strong><p>发布时固定 ID 与版本；源资产停用或健康恶化只产生风险提示，不自动替换生产依赖。</p></div></div></section>;
}

function TestTab({ skill, writable, notice }: { skill: SkillRecord; writable: boolean; notice: (message: string) => void }) {
  const registry = useSkillRegistry(); const [input, setInput] = useState(skill.contract.exampleInput); const [error, setError] = useState(''); const [result, setResult] = useState<SkillTestRun | null>(skill.tests[0] || null); const [caseName, setCaseName] = useState(''); const [cases, setCases] = useState(skill.testCases); const [editingId, setEditingId] = useState<string | null>(null);
  const run = () => { if (!input.trim()) { setError('测试输入不能为空。'); return; } try { JSON.parse(input); } catch { setError('测试输入不是合法 JSON，禁止运行。'); return; } const failed = skill.dependencies.some(item => item.status === '波动' || item.status === '已停用'); const runResult: SkillTestRun = { id: `SKILL-RUN-${Date.now()}`, time: '刚刚', result: failed ? '失败' : '通过', score: failed ? 72 : 94, latency: failed ? '8.0s' : skill.type === '组合' ? '3.2s' : '1.1s', traceId: `TRACE-SKILL-${Date.now().toString().slice(-6)}`, input, output: failed ? '{"error":"SKILL-424","stage":"能力依赖"}' : skill.contract.exampleOutput, dependencyHits: skill.dependencies.filter(item => ['Prompt', '知识策略', 'Tool', '原子 Skill'].includes(item.type)).map(item => `${item.name} ${item.version || ''}`), retries: failed ? skill.policy.retries : 0, fallback: failed ? skill.policy.fallback : '未触发', error: failed ? '失败阶段：能力依赖；上游资产未发布或健康异常' : undefined }; const operation = registry.addTestRun(skill.id, runResult, 'Skill 工作台'); setResult(runResult); setError(runResult.error || ''); notice(operation.message); };
  const saveCase = () => { if (!caseName.trim()) return; const next: SkillTestCase = { id: editingId || `CASE-${Date.now()}`, name: caseName, category: '正常', input, expected: '返回符合输出 Schema 的结果、证据和下一步', status: '草稿' }; setCases(current => editingId ? current.map(item => item.id === editingId ? next : item) : [next, ...current]); setCaseName(''); setEditingId(null); notice(editingId ? '测试用例已更新。' : '测试用例草稿已创建。'); };
  return <div className="tools-debug-layout"><section className="tools-panel"><header><div><h3>测试用例</h3><p>覆盖正常、边界、异常、安全和组合场景。</p></div></header>{writable && <div className="skills-test-case-form"><input value={caseName} onChange={event => setCaseName(event.target.value)} placeholder="测试用例名称" /><button className="tools-primary" disabled={!caseName.trim()} onClick={saveCase}>{editingId ? '保存修改' : '新建用例'}</button></div>}<div className="skills-test-cases">{cases.map(item => <article key={item.id}><div><b>{item.name}</b><small>{item.category} · {item.status} · {item.id}</small></div>{writable && <span><button onClick={() => { setEditingId(item.id); setCaseName(item.name); setInput(item.input); }}>编辑</button><button className="danger" onClick={() => { setCases(current => current.filter(value => value.id !== item.id)); notice('已删除测试用例草稿。'); }}><Trash2 size={13} /></button></span>}</article>)}</div></section><section className="tools-panel"><header><div><h3>调试运行</h3><p>结果回写 Skill 发布门禁和 M11 测试证据。</p></div></header><label>测试输入 JSON<textarea value={input} onChange={event => setInput(event.target.value)} /></label><button className="tools-primary tools-test-button" disabled={!writable} onClick={run}><Play size={14} />运行 Skill 测试</button>{error && <p className="tools-error">{error}</p>}{result && <dl className="tools-detail-list"><div><dt>结果 / 评分</dt><dd>{result.result} · {result.score}</dd></div><div><dt>Trace / 耗时</dt><dd>{result.traceId} · {result.latency}</dd></div><div><dt>依赖命中</dt><dd>{result.dependencyHits.join(' · ') || '无'}</dd></div><div><dt>重试 / 降级</dt><dd>{result.retries} 次 · {result.fallback}</dd></div><div><dt>结构化输出</dt><dd><pre>{result.output}</pre></dd></div></dl>}</section></div>;
}

function PermissionTab({ skill, writable, notice }: { skill: SkillRecord; writable: boolean; notice: (message: string) => void }) {
  const registry = useSkillRegistry(); const [type, setType] = useState<'部门' | '岗位' | '角色'>('部门'); const [name, setName] = useState('线索事业部'); const permissions = skill.dependencies.filter(item => ['部门', '岗位', '角色', 'Agent', '工作流'].includes(item.type)); const add = () => { const dependency: SkillDependency = { id: `${type}-${name}`, type, name, status: '已授权', scope: type === '角色' ? '运行与查看' : '本范围内使用' }; notice(registry.addDependency(skill.id, dependency).message); };
  return <section className="tools-panel"><header><div><h3>适用范围与权限</h3><p>授权 Skill 给部门、岗位、角色、Agent 或工作流；源权限由 M16 继续裁决。</p></div>{writable && <div className="tools-inline-create"><select value={type} onChange={event => setType(event.target.value as typeof type)}><option>部门</option><option>岗位</option><option>角色</option></select><select value={name} onChange={event => setName(event.target.value)}>{type === '部门' ? <><option>线索事业部</option><option>内容事业部</option><option>用户服务中心</option></> : type === '岗位' ? <><option>AI训练师</option><option>线索运营经理</option><option>内容审核员</option></> : <><option>业务负责人</option><option>AI训练师</option><option>平台管理员</option></>}</select><button className="tools-primary" onClick={add}><Plus size={14} />授权</button></div>}</header><div className="tools-dependency-table"><div><b>对象类型</b><b>授权对象</b><b>版本</b><b>权限范围</b><b>状态</b><b>操作</b></div>{permissions.map(item => <div key={`${item.type}-${item.id}`}><i>{item.type}</i><span><b>{item.name}</b><small>{item.id}</small></span><span>{item.version || '—'}</span><span>{item.scope}</span><span>{item.status}</span><span>{writable ? <button className="danger" onClick={() => notice(registry.removeDependency(skill.id, item.id).message)}>回收</button> : '只读'}</span></div>)}</div></section>;
}

function VersionTab({ role, skill, copy }: { role: RoleId; skill: SkillRecord; copy: () => void }) { const [selected, setSelected] = useState(skill.versions[0]?.version || ''); const version = skill.versions.find(item => item.version === selected); const canCopy = ['trainer', 'admin', 'superadmin'].includes(role) && ['已发布', '已归档'].includes(skill.lifecycle); return <div className="tools-version-layout"><section className="tools-panel"><header><div><h3>版本历史</h3><p>已发布版本不可变，恢复或修改只生成新草稿。</p></div>{canCopy && <button className="tools-primary" onClick={copy}><Copy size={14} />{skill.lifecycle === '已归档' ? '恢复为新草稿' : '复制为新草稿'}</button>}</header><div className="tools-version-list">{skill.versions.map(item => <button key={item.version} className={selected === item.version ? 'active' : ''} onClick={() => setSelected(item.version)}><b>{item.version}</b><i className={`tools-life is-${item.status}`}>{item.status}</i><span>{item.author} · {item.time}</span><small>{item.change}</small></button>)}</div></section><section className="tools-panel"><header><div><h3>版本差异</h3><p>{version ? `${version.version} 与当前配置的差异摘要` : '选择版本'}</p></div></header>{version && <dl className="tools-detail-list"><div><dt>依赖快照</dt><dd>{version.dependencySnapshot}</dd></div><div><dt>指令契约</dt><dd>{version.change}</dd></div><div><dt>影响范围</dt><dd>{skill.dependencies.filter(item => ['Agent', '工作流'].includes(item.type)).length} 项生产消费者需回归</dd></div><div><dt>测试证据</dt><dd>{skill.tests[0]?.id || '无测试证据'}</dd></div></dl>}</section><section className="tools-panel span-2"><header><div><h3>操作审计</h3><p>配置、测试、授权和生命周期事件不可编辑或删除。</p></div></header><div className="tools-audit-list">{skill.audit.map(item => <article key={item.id}><time>{item.time}</time><b>{item.actor}</b><span>{item.action}</span><small>{item.evidence}</small></article>)}</div></section></div>; }

function lifecycleActions(skill: SkillRecord, role: RoleId) { const trainer = ['trainer', 'admin', 'superadmin'].includes(role); const admin = ['admin', 'superadmin'].includes(role); const list: { id: string; label: string; icon: React.ReactNode; primary?: boolean; danger?: boolean }[] = []; if (trainer && skill.lifecycle === '草稿') list.push({ id: 'test', label: '进入测试', icon: <Play size={14} />, primary: true }); if (trainer && skill.lifecycle === '测试中') list.push({ id: 'submit', label: '提交审核', icon: <Send size={14} />, primary: true }); if (trainer && skill.lifecycle === '待审核') list.push({ id: 'withdraw', label: '撤回', icon: <RotateCcw size={14} /> }); if (admin && skill.lifecycle === '待审核') list.push({ id: 'reject', label: '驳回', icon: <XCircle size={14} />, danger: true }, { id: 'publish', label: '发布', icon: <CheckCircle2 size={14} />, primary: true }); if (trainer && skill.lifecycle === '已发布') list.push({ id: 'copy-draft', label: '复制新草稿', icon: <Copy size={14} /> }); if (admin && skill.lifecycle === '已发布') list.push({ id: 'disable', label: '停用', icon: <PauseCircle size={14} />, danger: true }); if (admin && skill.lifecycle === '已停用') list.push({ id: 'restore', label: '恢复', icon: <Play size={14} />, primary: true }, { id: 'archive', label: '归档', icon: <Archive size={14} /> }); if (trainer && skill.lifecycle === '已归档') list.push({ id: 'restore-draft', label: '恢复为新草稿', icon: <RotateCcw size={14} /> }); if (trainer && skill.lifecycle === '草稿') list.push({ id: 'delete', label: '删除草稿', icon: <Trash2 size={14} />, danger: true }); return list; }
function ReasonDialog({ title, onClose, onConfirm }: { title: string; onClose: () => void; onConfirm: (reason: string) => void }) { const [reason, setReason] = useState('测试覆盖或依赖健康未达到发布要求'); return <div className="tools-modal-mask"><section className="tools-reason-dialog"><header><h2>{title}</h2><button onClick={onClose}><X /></button></header><label>驳回原因 *<textarea value={reason} onChange={event => setReason(event.target.value)} /></label><footer><button onClick={onClose}>取消</button><button className="danger" disabled={!reason.trim()} onClick={() => onConfirm(reason)}>确认驳回</button></footer></section></div>; }
