import React, { useMemo, useState } from 'react';
import type { RoleId } from '../../types';
import { useModelBillingRegistry } from './model-billing-store';

const tabs=['计费总览','价目管理','用量计量','内部归集','供应商账单','对账中心','预算告警'];
const canGovern=(role:RoleId)=>['admin','superadmin'].includes(role);

export function BillingWorkspace({role}:{role:RoleId}){
  const registry=useModelBillingRegistry();const {state}=registry;
  const [tab,setTab]=useState(tabs[0]);const [notice,setNotice]=useState('');const [query,setQuery]=useState('');
  const supplierCost=state.usage.reduce((sum,item)=>sum+item.supplierCost,0);const allocated=state.usage.reduce((sum,item)=>sum+item.allocatedCost,0);const openCases=state.reconciliations.filter(item=>item.status!=='已解决');const budgetRate=Math.round(state.budgets.reduce((sum,item)=>sum+item.used,0)/state.budgets.reduce((sum,item)=>sum+item.monthlyLimit,0)*100);
  return <section className="mb-workspace"><header className="mb-toolbar"><div><h2>计费管理</h2><p>管理供应商成本、用量计量、内部归集、预算告警和账单对账；客户合同与发票归 M10。</p></div></header>
    <div className="mb-metrics"><Metric label="本月供应商成本" value={`¥ ${supplierCost.toLocaleString(undefined,{maximumFractionDigits:2})}`}/><Metric label="内部归集金额" value={`¥ ${allocated.toLocaleString(undefined,{maximumFractionDigits:2})}`}/><Metric label="预算使用率" value={`${budgetRate}%`} tone={budgetRate>80?'warning':'success'}/><Metric label="待处理差异" value={`${openCases.length} 项`} tone={openCases.length?'danger':'success'}/></div>
    <nav className="mb-tabs">{tabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</nav>
    {tab==='计费总览'&&<div className="mb-grid-2"><section className="mb-panel"><Section title="供应商成本结构" subtitle="按平台计量数据汇总，不含客户侧开票。"/>{['OpenAI','DeepSeek','百炼'].map(provider=>{const cost=state.usage.filter(item=>item.provider===provider).reduce((s,i)=>s+i.supplierCost,0);return <div className="mb-progress-row" key={provider}><span>{provider}</span><i><b style={{width:`${supplierCost?Math.max(4,cost/supplierCost*100):0}%`}}/></i><strong>¥{cost.toFixed(2)}</strong></div>})}</section><section className="mb-panel"><Section title="需要处理" subtitle="从计量、预算和对账规则产生的治理事项。"/>{openCases.map(item=><div className="mb-list-row" key={item.id}><span><b>{item.kind}</b><small>{item.id} · ¥{item.amount}</small></span><em>{item.status}</em></div>)}{state.budgets.filter(item=>item.used/item.monthlyLimit>=.8).map(item=><div className="mb-list-row" key={item.id}><span><b>{item.name}</b><small>已使用 {Math.round(item.used/item.monthlyLimit*100)}% · 动作 {item.action}</small></span><em>预算预警</em></div>)}</section></div>}
    {tab==='价目管理'&&<PricingTable role={role} query={query} setQuery={setQuery} notify={setNotice}/>} 
    {tab==='用量计量'&&<UsageTable query={query} setQuery={setQuery}/>} 
    {tab==='内部归集'&&<AllocationTable role={role} notify={setNotice}/>} 
    {tab==='供应商账单'&&<BillTable role={role} notify={setNotice}/>} 
    {tab==='对账中心'&&<ReconciliationTable role={role} notify={setNotice}/>} 
    {tab==='预算告警'&&<BudgetTable role={role} notify={setNotice}/>} 
    {notice&&<div className="mb-toast"><span>{notice}</span><button onClick={()=>setNotice('')}>关闭</button></div>}
  </section>
}

function PricingTable({role,query,setQuery,notify}:{role:RoleId;query:string;setQuery:(v:string)=>void;notify:(v:string)=>void}){const {state}=useModelBillingRegistry();const rows=state.pricing.filter(item=>!query||JSON.stringify(item).toLowerCase().includes(query.toLowerCase()));return <div className="mb-panel"><Section title="供应商价目版本" subtitle="已发布版本不可直接修改；价格发布仅允许超级管理员。" actions={<><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索供应商或模型"/>{canGovern(role)&&<button onClick={()=>notify('已创建 2026.09 价目草稿，可维护后提交审核。')}>新建价目草稿</button>}</>}/><Table head={['供应商 / 模型','版本','生效时间','输入 / 百万','输出 / 百万','缓存 / 百万','币种','状态','操作']}>{rows.map(item=><tr key={item.id}><td><b>{item.provider}</b><small>{item.modelId}</small></td><td>{item.version}</td><td>{item.effectiveFrom}</td><td>{item.inputPerMillion}</td><td>{item.outputPerMillion}</td><td>{item.cachePerMillion}</td><td>{item.currency}</td><td><Badge value={item.status}/></td><td><button onClick={()=>notify(item.status==='已发布'?'已打开价目版本差异，不允许原地编辑。':'已进入价目草稿编辑。')}>{item.status==='已发布'?'查看差异':'编辑草稿'}</button>{item.status==='草稿'&&role==='superadmin'&&<button onClick={()=>notify('价目版本已通过门禁并发布。')}>发布</button>}</td></tr>)}</Table></div>}

function UsageTable({query,setQuery}:{query:string;setQuery:(v:string)=>void}){const {state}=useModelBillingRegistry();const rows=state.usage.filter(item=>!query||JSON.stringify(item).toLowerCase().includes(query.toLowerCase()));return <div className="mb-panel"><Section title="模型用量明细" subtitle="可按日期、供应商、模型、部门、项目、Agent、工作流和成本中心追溯。" actions={<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索任一计量维度"/>}/><Table head={['日期','供应商 / 模型','部门 / 项目','Agent / 工作流','Token（入/出）','请求量','供应商成本','归集成本']}>{rows.map(item=><tr key={item.id}><td>{item.date}</td><td><b>{item.provider}</b><small>{item.modelId}</small></td><td>{item.departmentId}<small>{item.projectId}</small></td><td>{item.agentId}<small>{item.workflowId}</small></td><td>{item.inputTokens.toLocaleString()} / {item.outputTokens.toLocaleString()}</td><td>{item.calls.toLocaleString()}</td><td>¥{item.supplierCost.toFixed(2)}</td><td>¥{item.allocatedCost.toFixed(2)}</td></tr>)}</Table></div>}

function AllocationTable({role,notify}:{role:RoleId;notify:(v:string)=>void}){const {state}=useModelBillingRegistry();return <div className="mb-panel"><Section title="内部成本归集" subtitle="将供应商成本按部门、项目、Agent、工作流和成本中心归集，不生成客户账单。" actions={canGovern(role)?<button onClick={()=>notify('已按当前规则模拟重算；差额 ¥0.00，尚未写入正式账期。')}>模拟重算</button>:undefined}/><Table head={['成本中心','部门','项目','供应商成本','管理加成','归集金额','规则状态','操作']}>{state.usage.map(item=><tr key={item.id}><td>{item.costCenter}</td><td>{item.departmentId}</td><td>{item.projectId}</td><td>¥{item.supplierCost.toFixed(2)}</td><td>{Math.round((item.allocatedCost/item.supplierCost-1)*100)}%</td><td>¥{item.allocatedCost.toFixed(2)}</td><td><Badge value="生效"/></td><td><button onClick={()=>notify(canGovern(role)?`已进入 ${item.costCenter} 分摊规则编辑。`:'当前身份只能查看归集规则。')}>{canGovern(role)?'编辑规则':'查看规则'}</button></td></tr>)}</Table></div>}

function BillTable({role,notify}:{role:RoleId;notify:(v:string)=>void}){const registry=useModelBillingRegistry();return <div className="mb-panel"><Section title="供应商账单" subtitle="导入供应商账单并与平台计量结果核对。" actions={canGovern(role)?<button onClick={()=>notify('已打开账单导入表单：请选择供应商、账期、币种和源文件。')}>导入账单</button>:undefined}/><Table head={['账单 ID','供应商','账期','账单金额','计量金额','差额','源文件','状态','操作']}>{registry.state.supplierBills.map(item=><tr key={item.id}><td>{item.id}</td><td>{item.provider}</td><td>{item.period}</td><td>{item.currency} {item.billedAmount.toLocaleString()}</td><td>{item.currency} {item.meteredAmount.toLocaleString()}</td><td>{(item.billedAmount-item.meteredAmount).toFixed(2)}</td><td>{item.sourceFile}</td><td><Badge value={item.status}/></td><td><button onClick={()=>notify(`已打开 ${item.id} 的账单原始行与计量匹配明细。`)}>查看明细</button>{item.status==='已核对'&&<button onClick={()=>notify(registry.settleSupplierBill(role,item.id).message)}>结算</button>}</td></tr>)}</Table></div>}

function ReconciliationTable({role,notify}:{role:RoleId;notify:(v:string)=>void}){const registry=useModelBillingRegistry();const [resolution,setResolution]=useState<Record<string,string>>({});return <div className="mb-panel"><Section title="对账差异处理" subtitle="覆盖缺失、重复、价格不一致和汇率差异，处理过程留痕。"/><Table head={['差异 ID','账单','类型','差异金额','负责人','状态','处理说明','操作']}>{registry.state.reconciliations.map(item=><tr key={item.id}><td>{item.id}</td><td>{item.billId}</td><td>{item.kind}</td><td>¥{item.amount}</td><td>{item.owner}</td><td><Badge value={item.status}/></td><td>{item.status==='已解决'?item.resolution:<input value={resolution[item.id]??item.resolution} onChange={e=>setResolution({...resolution,[item.id]:e.target.value})} placeholder="填写核对结论"/>}</td><td>{item.status!=='已解决'&&<button onClick={()=>notify(registry.resolveReconciliation(role,item.id,resolution[item.id]??item.resolution).message)}>标记解决</button>}</td></tr>)}</Table></div>}

function BudgetTable({role,notify}:{role:RoleId;notify:(v:string)=>void}){const {state}=useModelBillingRegistry();return <div className="mb-panel"><Section title="模型预算与告警动作" subtitle="预算命中后给出提醒、限流、降级或停用建议，不自动改写生产依赖。" actions={canGovern(role)?<button onClick={()=>notify('已打开预算策略新建表单。')}>新建预算策略</button>:undefined}/>{state.budgets.map(item=>{const rate=Math.round(item.used/item.monthlyLimit*100);return <div className="mb-budget-row" key={item.id}><div><b>{item.name}</b><small>{item.scopeType} · {item.scopeId} · 阈值 {item.thresholds.join('% / ')}%</small></div><div className="mb-budget-bar"><i><b style={{width:`${Math.min(rate,100)}%`}}/></i><span>¥{item.used.toLocaleString()} / ¥{item.monthlyLimit.toLocaleString()}（{rate}%）</span></div><Badge value={item.enabled?'启用':'停用'}/><strong>触发：{item.action}</strong><button onClick={()=>notify(canGovern(role)?`已进入 ${item.id} 编辑。`:'当前身份只能查看预算策略。')}>{canGovern(role)?'编辑':'查看'}</button></div>})}</div>}

function Metric({label,value,tone='normal'}:{label:string;value:string;tone?:string}){return <article className={`mb-metric ${tone}`}><span>{label}</span><strong>{value}</strong></article>}
function Section({title,subtitle,actions}:{title:string;subtitle:string;actions?:React.ReactNode}){return <header className="mb-section-title"><div><h3>{title}</h3><p>{subtitle}</p></div>{actions&&<div className="mb-toolbar-actions">{actions}</div>}</header>}
function Table({head,children}:{head:string[];children:React.ReactNode}){return <div className="mb-table-wrap"><table><thead><tr>{head.map(item=><th key={item}>{item}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Badge({value}:{value:string}){return <span className={`mb-badge tone-${['已发布','已核对','已解决','生效','启用'].includes(value)?'success':['有差异','待审核','处理中'].includes(value)?'warning':['故障'].includes(value)?'danger':'neutral'}`}>{value}</span>}
