import React, { useState } from 'react';
import { Plus, Search, ShieldCheck } from 'lucide-react';
import type { RoleId } from '../../types';
import { canSeeManagementModule, getManagementDecision, roleUserId, type ManageableObject, type ManagementAction, type ManagementObjectType } from './management-capability';
import { nameOfUser, type PermissionPolicy, type RoleBinding } from './platform-data';
import { selectMyPermissionSummary, usePlatformManagement } from './platform-management-store';
import { EmptyState, ImpactPanel, ManagementDetail, ManagementDialog, ManagementHeader, ManagementTabs, ManagementToolbar, OperationMenu, Risk, Status } from './shared/management-ui';
import './platform-management.css';

type View='roles'|'matrix'|'scopes'|'reviews'|'decisions';
type Detail={type:ManagementObjectType;id:string}|null;
type ActiveModal={mode:'create'|'edit'|'delete'|'transition'|'delegate';type:ManagementObjectType;id?:string;event?:ManagementAction};
type Modal=ActiveModal|null;
const actorName:Record<RoleId,string>={employee:'陈屿',business:'李沐',trainer:'周芮',admin:'赵岑',superadmin:'顾川',client:'客户管理员'};
const tabs=[
  {id:'roles',label:'角色管理',description:'角色、成员与委派'},
  {id:'matrix',label:'权限矩阵',description:'页面、字段与动作'},
  {id:'scopes',label:'数据权限',description:'七级范围与边界'},
  {id:'reviews',label:'权限复核',description:'高风险、越权与冲突复核'},
  {id:'decisions',label:'决策日志',description:'依据与审计证据'},
];
const emptyDraft={name:'',description:'',risk:'中',roleId:'ROLE-TRAINER',moduleId:'custom',moduleName:'M03 Agent 管理',page:'Agent 工作台',effect:'允许',actionsText:'查看、编辑',fieldsText:'常规字段',dataScope:'部门',scope:'平台管理员与超级管理员',owner:'顾川',dueAt:'2026-08-31',subjectId:'USR-TRAINER',objectTypes:['config'],delegatedActions:['read','update'],scopeTargets:['ORG-CAPABILITY'],riskCeiling:'中',validTo:'2026-12-31'};

export function M16AccessControlPage({role}:{role:RoleId}){
  const {state,setState,execute,applyRoleBindingChange,applyDelegationChange,resolvePermissionReview}=usePlatformManagement();
  const [view,setView]=useState<View>('roles');
  const [detail,setDetail]=useState<Detail>(null);
  const [modal,setModal]=useState<Modal>(null);
  const [draft,setDraft]=useState<any>(emptyDraft);
  const [query,setQuery]=useState('');
  const [notice,setNotice]=useState('');
  const userId=roleUserId[role];
  const context={role,userId};
  const isSelfService=['employee','business','trainer'].includes(role);
  const objectFor=(type:ManagementObjectType,item:any):ManageableObject=>({id:item.id,objectType:type,ownerId:item.ownerId??item.subjectId,organizationId:item.organizationId,tenantId:'TENANT-AIMP',status:item.status,risk:item.risk,protected:(type==='role'&&item.kind==='系统内置')||['ROLE-SUPERADMIN','POL-SUPER-ALL'].includes(item.id),dependencies:dependencies(type,item,state)});
  const decision=(type:ManagementObjectType,item:any,action:ManagementAction)=>getManagementDecision(context,objectFor(type,item),action);
  const visible=(type:ManagementObjectType,list:any[])=>list.filter(item=>decision(type,item,'read').allowed);
  const selected=detail?findItem(state,detail.type,detail.id):undefined;
  const run=(type:ManagementObjectType,item:any,action:ManagementAction,payload?:any)=>{const resultDecision=decision(type,item,action);if(!resultDecision.allowed){setNotice(`${resultDecision.reason} · ${resultDecision.auditId}`);return false}const result=execute({objectType:type,action,id:item.id,payload,actor:actorName[role],dependencies:action==='delete'?dependencies(type,item,state):undefined});setNotice(`${result.message}${result.blockedBy.length?` 依赖：${result.blockedBy.join('、')}`:''}`);if(result.ok&&action==='delete')setDetail(null);return result.ok};
  const openForm=(mode:'create'|'edit',type:ManagementObjectType,item?:any)=>{setDraft(item?toDraft(type,item):{...emptyDraft});setModal({mode,type,id:item?.id})};
  const save=()=>{if(!modal)return;if(!draft.name?.trim()&&!['policy','scope'].includes(modal.type)){setNotice('请填写名称。');return}const existing=findItem(state,modal.type,modal.id);const payload=buildPayload(modal.type,draft,existing);if(modal.mode==='create'){const d=getManagementDecision(context,objectFor(modal.type,{...payload,ownerId:userId}),'create');if(!d.allowed){setNotice(`${d.reason} · ${d.auditId}`);return}execute({objectType:modal.type,action:'create',payload,actor:actorName[role]});setDetail({type:modal.type,id:payload.id});setNotice(`新增成功：${payload.id}`)}else if(existing)run(modal.type,existing,'update',payload);setModal(null)};
  const createDelegation=()=>{const result=applyDelegationChange({actorId:userId,actorName:actorName[role],actorRole:role,subjectId:draft.subjectId,objectTypes:draft.objectTypes,actions:draft.delegatedActions,dataScope:draft.dataScope,scopeTargets:draft.scopeTargets,validTo:draft.validTo,riskCeiling:draft.riskCeiling});setNotice(result.outcome==='applied'?`委派已生效：${result.bindingId}`:`委派已进入权限复核：${result.reviewItemId} · ${result.reasons.join('；')}`);setModal(null)};
  if(!canSeeManagementModule(role,'M16'))return <section className="pm-gate"><ShieldCheck/><h1>M16 权限管理不可访问</h1><p>当前身份没有内部权限管理能力；客户管理员请在客户门户管理本租户成员。</p></section>;
  if(isSelfService)return <section className="pm"><ManagementHeader title="M16 我的权限" subtitle="查看本人角色、授权来源、数据范围、有效期和最近拒绝记录"/><MyPermissions state={state} userId={userId}/></section>;
  const listFor=(v:View)=>v==='roles'?visible('role',state.roles):v==='matrix'||v==='scopes'?visible('policy',state.policies):v==='reviews'?visible('review',state.reviews):visible('decision',state.decisions);
  const tableType:ManagementObjectType=view==='roles'?'role':view==='matrix'?'policy':view==='reviews'?'review':'decision';
  return <section className="pm"><ManagementHeader title="M16 权限管理" subtitle="统一管理角色、权限策略、数据范围、复核与决策证据"/>
    {selected&&detail?<M16Detail type={detail.type} item={selected} state={state} role={role} userId={userId} back={()=>setDetail(null)} open={setDetail} decision={decision} edit={()=>openForm('edit',detail.type,selected)} remove={()=>setModal({mode:'delete',type:detail.type,id:selected.id})} transition={event=>setModal({mode:'transition',type:detail.type,id:selected.id,event})} delegate={()=>{setDraft({...emptyDraft});setModal({mode:'delegate',type:'role',id:selected.id})}} setState={setState} applyRoleBindingChange={applyRoleBindingChange} resolvePermissionReview={resolvePermissionReview} notice={setNotice}/>:<main className="pm-content">
      <ManagementTabs items={tabs} value={view} onChange={id=>{setView(id as View);setDetail(null)}}/>
      <ManagementToolbar><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索名称、主体或审计 ID"/></label><span>对象与动作已按身份、范围和有效期过滤</span>{!['decisions'].includes(view)&&<button className="primary" onClick={()=>openForm('create',view==='roles'?'role':view==='matrix'||view==='scopes'?'policy':'review')}><Plus/>新增</button>}</ManagementToolbar>
      {view==='scopes'?<ScopeCards items={listFor(view) as PermissionPolicy[]} open={setDetail}/>:<M16Table type={tableType} items={listFor(view)} query={query} open={setDetail} decision={decision} action={(type,item,action)=>action==='delete'?setModal({mode:'delete',type,id:item.id}):action==='update'?openForm('edit',type,item):setModal({mode:'transition',type,id:item.id,event:action})}/>} 
    </main>}
    {modal&&<M16Modal modal={modal} item={findItem(state,modal.type,modal.id)} state={state} draft={draft} setDraft={setDraft} close={()=>setModal(null)} save={save} delegate={createDelegation} confirm={()=>{const item=findItem(state,modal.type,modal.id);if(!item)return;if(modal.mode==='delete')run(modal.type,item,'delete');else run(modal.type,item,modal.event!,transitionPayload(item,modal.event!));setModal(null)}}/>}
    {notice&&<div className="pm-notice">{notice}<button onClick={()=>setNotice('')}>关闭</button></div>}
  </section>;
}

function MyPermissions({state,userId}:{state:any;userId:string}){
  const summary=selectMyPermissionSummary(state,userId);
  return <main className="pm-content pm-related-stack pm-self-permissions"><section className="pm-kpis"><article className="pm-kpi"><span>有效角色</span><strong>{summary.roles.length}</strong></article><article className="pm-kpi"><span>数据范围</span><strong>{summary.dataScopes.length}</strong></article><article className="pm-kpi"><span>有效委派</span><strong>{summary.delegations.length}</strong></article><article className="pm-kpi"><span>最近拒绝</span><strong>{summary.recentDenials.length}</strong></article></section>
    <article className="pm-panel"><header><b>角色与授权来源</b><span>只读</span></header>{summary.roles.map(item=><div className="pm-list-row" key={item.id}><span><b>{item.name}</b><small>{item.id} · 来源：{item.source} · 有效期：{item.validTo}</small></span><Status value={item.status}/></div>)}</article>
    <article className="pm-panel"><header><b>数据范围与委派</b></header><div className="pm-scope-tags">{summary.dataScopes.map(scope=><span className="pm-status" key={scope}>{scope}</span>)}</div>{summary.delegations.map(item=><div className="pm-list-row" key={item.id}><span><b>{item.objectTypes.join('、')}</b><small>{item.actions.join('、')} · {item.scopeTargets.join('、')} · 至 {item.validTo}</small></span><Status value={item.status}/></div>)}</article>
    <article className="pm-panel"><header><b>最近拒绝记录</b><span>不可修改的决策证据</span></header>{summary.recentDenials.length?<div className="pm-table-wrap"><table><thead><tr><th>时间</th><th>模块 / 动作</th><th>资源</th><th>拒绝原因</th><th>审计 ID</th></tr></thead><tbody>{summary.recentDenials.map(item=><tr key={item.id}><td>{item.at}</td><td>{item.module} · {item.action}</td><td>{item.resource}</td><td>{item.reason}</td><td>{item.id}</td></tr>)}</tbody></table></div>:<EmptyState text="近期没有权限拒绝记录"/>}</article>
    <article className="pm-panel"><p>权限由管理员直接维护；当前页面不提供自助申请、编辑或审批入口。</p></article>
  </main>;
}

function dependencies(type:ManagementObjectType,item:any,state:any){if(type==='role')return [...(item.memberCount?[`${item.memberCount} 名成员`]:[]),...state.policies.filter((policy:any)=>policy.roleId===item.id).map((policy:any)=>`策略 ${policy.id}`),...state.bindings.filter((binding:any)=>binding.roleId===item.id&&binding.status==='生效').map((binding:any)=>`角色绑定 ${binding.id}`)];if(type==='policy'&&item.effect)return ['已发布策略版本'];if(type==='review'&&item.status!=='待开始')return [`复核批次 ${item.status}`];return []}
function findItem(state:any,type:ManagementObjectType,id?:string){if(!id)return;const keys:Partial<Record<ManagementObjectType,string>>={role:'roles',policy:'policies',scope:'policies',review:'reviews',decision:'decisions'};const key=keys[type];return key?state[key].find((item:any)=>item.id===id):undefined}
function displayName(type:ManagementObjectType,item:any){if(type==='policy'||type==='scope')return `${item.roleId} · ${item.moduleName}`;if(type==='decision')return `${item.subject} · ${item.action}`;return item.name}
function displayOwner(type:ManagementObjectType,item:any){if(type==='role')return `${item.kind} · ${item.memberCount} 人`;if(type==='policy'||type==='scope')return `${item.page} · ${item.dataScope}`;if(type==='review')return `${item.owner} · ${item.reviewed}/${item.total}`;return `${item.module} · ${item.resource}`}
function actionsFor(type:ManagementObjectType,item:any):ManagementAction[]{if(type==='decision')return [];const actions:ManagementAction[]=['update'];if(['停用','归档'].includes(item.status))actions.push('restore');else actions.push('disable','archive');actions.push('delete');return actions}
const actionLabel=(action:ManagementAction)=>({update:'编辑',delete:'删除',disable:'停用',restore:'恢复',archive:'归档',approve:'审批',revoke:'回收',create:'新增',read:'查看',publish:'发布',delegate:'委派'}[action]);

function M16Table({type,items,query,open,decision,action}:{type:ManagementObjectType;items:any[];query:string;open:(detail:Detail)=>void;decision:any;action:(type:ManagementObjectType,item:any,action:ManagementAction)=>void}){const filtered=items.filter(item=>!query||JSON.stringify(item).toLowerCase().includes(query.toLowerCase()));if(!filtered.length)return <EmptyState text="当前范围暂无对象"/>;return <div className="pm-table-wrap"><table><thead><tr><th>对象</th><th>类型 / 范围</th><th>风险</th><th>状态 / 结果</th><th>操作</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id} onClick={()=>open({type,id:item.id})}><td><b>{displayName(type,item)}</b><small>{item.id}</small></td><td>{displayOwner(type,item)}</td><td>{item.risk?<Risk value={item.risk}/>:<span>—</span>}</td><td><Status value={item.status??item.result??item.effect}/></td><td onClick={event=>event.stopPropagation()}><button onClick={()=>open({type,id:item.id})}>详情</button>{actionsFor(type,item).length>0&&<OperationMenu items={actionsFor(type,item).map(operation=>({label:actionLabel(operation),onClick:()=>action(type,item,operation),disabled:!decision(type,item,operation).allowed,reason:decision(type,item,operation).reason,danger:operation==='delete'}))}/>}</td></tr>)}</tbody></table></div>}
function ScopeCards({items,open}:{items:PermissionPolicy[];open:(detail:Detail)=>void}){return <section className="pm-card-list">{items.map(item=><article key={item.id} onClick={()=>open({type:'scope',id:item.id})}><header><div><b>{item.roleId} · {item.moduleName}</b><small>{item.id}</small></div><Status value={item.dataScope}/></header><p>页面：{item.page} · 字段：{item.fields.join('、')}</p><footer><button onClick={event=>{event.stopPropagation();open({type:'scope',id:item.id})}}>进入范围详情</button></footer></article>)}</section>}

function M16Detail(props:{type:ManagementObjectType;item:any;state:any;role:RoleId;userId:string;back:()=>void;open:(detail:Detail)=>void;decision:any;edit:()=>void;remove:()=>void;transition:(action:ManagementAction)=>void;delegate:()=>void;setState:any;applyRoleBindingChange:any;resolvePermissionReview:any;notice:(message:string)=>void}){
  const {type,item,state,role,userId,back,decision,edit,remove,transition,delegate,setState,applyRoleBindingChange,resolvePermissionReview,notice}=props;
  const [tab,setTab]=useState('基本信息');
  const detailTabs=['基本信息','关联与成员','权限/状态','审计证据'];
  const metrics=[{label:'状态',value:item.status??item.result??item.effect},{label:'风险',value:item.risk??'—'},{label:'数据范围',value:item.dataScope??item.scope??'—'},{label:'当前权限',value:decision(type,item,'update').allowed?'可管理':'只读'}];
  return <ManagementDetail title={displayName(type,item)} meta={`${item.id} · ${type}`} backLabel="返回列表" onBack={back} metrics={metrics} tabs={<nav className="pm-detail-tabs">{detailTabs.map(name=><button className={tab===name?'active':''} key={name} onClick={()=>setTab(name)}>{name}</button>)}</nav>} actions={<>{type!=='decision'&&<button disabled={!decision(type,item,'update').allowed} title={decision(type,item,'update').reason} onClick={edit}>编辑</button>}{type==='role'&&<button disabled={!decision(type,item,'delegate').allowed} onClick={delegate}>新增委派</button>}{actionsFor(type,item).filter(action=>action!=='update').length>0&&<OperationMenu items={actionsFor(type,item).filter(action=>action!=='update').map(action=>({label:actionLabel(action),onClick:()=>action==='delete'?remove():transition(action),disabled:!decision(type,item,action).allowed,reason:decision(type,item,action).reason,danger:action==='delete'}))}/>}</>}>
    {tab==='基本信息'&&<article className="pm-panel"><header><b>对象资料</b></header><dl>{Object.entries(item).filter(([,value])=>typeof value!=='object').map(([key,value])=><React.Fragment key={key}><dt>{key}</dt><dd>{String(value)}</dd></React.Fragment>)}</dl></article>}
    {tab==='关联与成员'&&<Related type={type} item={item} state={state} role={role} userId={userId} setState={setState} notice={notice} canManage={decision(type,item,'delegate').allowed} applyRoleBindingChange={applyRoleBindingChange} resolvePermissionReview={resolvePermissionReview}/>} 
    {tab==='权限/状态'&&<article className="pm-panel"><header><b>动作决策</b></header>{(['read','update','delete','approve','revoke','delegate'] as ManagementAction[]).map(action=><div className="pm-list-row" key={action}><b>{actionLabel(action)}</b><Status value={decision(type,item,action).allowed?'允许':'拒绝'}/><span>{decision(type,item,action).reason}</span></div>)}</article>}
    {tab==='审计证据'&&(type==='decision'?<DecisionEvidence item={item}/>:<div className="pm-table-wrap"><table><tbody>{state.audits.filter((audit:any)=>audit.object===item.id||audit.object?.includes(item.id)).map((audit:any)=><tr key={audit.id}><td>{audit.at}</td><td>{audit.action}</td><td>{audit.detail}</td><td>{audit.id}</td></tr>)}</tbody></table></div>)}
  </ManagementDetail>;
}

function Related({type,item,state,role,userId,setState,notice,canManage,applyRoleBindingChange,resolvePermissionReview}:{type:ManagementObjectType;item:any;state:any;role:RoleId;userId:string;setState:any;notice:(message:string)=>void;canManage:boolean;applyRoleBindingChange:any;resolvePermissionReview:any}){
  const [subjectId,setSubjectId]=useState('USR-EMP');
  const [source,setSource]=useState<RoleBinding['source']>('直接授权');
  const [validTo,setValidTo]=useState('2026-12-31');
  if(type==='role'){
    const bindings=state.bindings.filter((binding:any)=>binding.roleId===item.id);
    const bind=()=>{const result=applyRoleBindingChange({actorId:userId,actorName:actorName[role],actorRole:role,subjectId,roleId:item.id,validTo,source});notice(result.outcome==='applied'?`已将 ${nameOfUser(subjectId)} 绑定到 ${item.name} · ${result.bindingId}`:`授权已进入权限复核：${result.reviewItemId} · ${result.reasons.join('；')}`)};
    const revoke=(binding:any)=>{setState((current:any)=>({...current,bindings:current.bindings.map((candidate:any)=>candidate.id===binding.id?{...candidate,status:'回收'}:candidate),roles:current.roles.map((candidate:any)=>candidate.id===item.id?{...candidate,memberCount:Math.max(0,candidate.memberCount-1)}:candidate),audits:[{id:`AUD-${Date.now().toString().slice(-6)}`,at:'刚刚',actor:actorName[role],action:'回收角色成员',object:item.id,detail:`${nameOfUser(binding.subjectId)} · ${binding.id}`},...current.audits]}));notice(`成员绑定 ${binding.id} 已回收`)};
    return <article className="pm-panel"><header><b>角色成员</b><span>{bindings.filter((binding:any)=>binding.status==='生效').length} 项生效绑定</span></header>{canManage&&<div className="pm-inline-form"><select aria-label="选择成员" value={subjectId} onChange={event=>setSubjectId(event.target.value)}>{state.users.map((user:any)=><option key={user.id} value={user.id}>{user.name} · {user.account}</option>)}</select><select aria-label="授权来源" value={source} onChange={event=>setSource(event.target.value as RoleBinding['source'])}><option>直接授权</option><option>岗位继承</option><option>组织继承</option></select><input aria-label="有效期" type="date" value={validTo} onChange={event=>setValidTo(event.target.value)}/><button className="primary" onClick={bind}>绑定成员</button></div>}{bindings.map((binding:any)=><div className="pm-list-row" key={binding.id}><span><b>{nameOfUser(binding.subjectId)}</b><small>{binding.source} · {binding.validFrom} 至 {binding.validTo}</small></span><Status value={binding.status}/>{canManage&&binding.status==='生效'&&<button onClick={()=>revoke(binding)}>回收</button>}</div>)}</article>;
  }
  if(type==='review'){
    const reviewItems=state.reviewItems.filter((reviewItem:any)=>reviewItem.reviewId===item.id);
    const resolve=(reviewItem:any,reviewDecision:'approve'|'reject')=>{const result=resolvePermissionReview({reviewItemId:reviewItem.id,decision:reviewDecision,actorName:actorName[role],actorRole:role});notice(`${result.message} · ${result.auditId}`)};
    const updatePeriodic=(reviewItem:any,status:string)=>{setState((current:any)=>({...current,reviewItems:current.reviewItems.map((candidate:any)=>candidate.id===reviewItem.id?{...candidate,status}:candidate),audits:[{id:`AUD-${Date.now().toString().slice(-6)}`,at:'刚刚',actor:actorName[role],action:'更新周期复核项',object:reviewItem.id,detail:status},...current.audits]}));notice(`复核项 ${reviewItem.id} 已更新`)};
    return <article className="pm-panel"><header><b>逐项复核</b><span>高风险、越权和冲突规则只在此处处置</span></header>{reviewItems.map((reviewItem:any)=><div className="pm-list-row" key={reviewItem.id}><span><b>{nameOfUser(reviewItem.subjectId)} · {reviewItem.permission}</b><small>{reviewItem.trigger??'周期复核'} · {reviewItem.requestedBy?`发起人 ${reviewItem.requestedBy} · `:''}{reviewItem.reasons?.join('；')??`最近使用 ${reviewItem.lastUsed}`}{reviewItem.conflictIds?.length?` · 规则 ${reviewItem.conflictIds.join('、')}`:''}</small></span><Status value={reviewItem.status}/>{canManage&&reviewItem.status==='待复核'&&(reviewItem.trigger&&reviewItem.trigger!=='周期复核'?<span className="pm-row-actions"><button onClick={()=>resolve(reviewItem,'reject')}>驳回</button><button className="primary" onClick={()=>resolve(reviewItem,'approve')}>批准</button></span>:<select value={reviewItem.status} onChange={event=>updatePeriodic(reviewItem,event.target.value)}><option>待复核</option><option>已保留</option><option>已回收</option><option>已转交</option></select>)}</div>)}</article>;
  }
  if(type==='decision')return <DecisionEvidence item={item}/>;
  return <article className="pm-panel"><header><b>关联策略与范围</b></header><p>角色 {item.roleId} · 动作 {item.actions?.join('、')} · 字段 {item.fields?.join('、')} · 范围 {item.dataScope}</p></article>;
}

function DecisionEvidence({item}:{item:any}){return <article className="pm-panel"><header><b>不可修改的决策证据</b></header><dl><dt>主体</dt><dd>{item.subject}</dd><dt>资源</dt><dd>{item.resource}</dd><dt>请求动作</dt><dd>{item.action}</dd><dt>数据范围</dt><dd>{item.dataScope}</dd><dt>命中策略 / 冲突规则</dt><dd>{item.matchedPolicies.join('、')}</dd><dt>最终原因</dt><dd>{item.reason}</dd><dt>审计 ID</dt><dd>{item.id}</dd></dl></article>}

function M16Modal({modal,item,state,draft,setDraft,close,save,delegate,confirm}:{modal:ActiveModal;item:any;state:any;draft:any;setDraft:(draft:any)=>void;close:()=>void;save:()=>void;delegate:()=>void;confirm:()=>void}){
  if(modal.mode==='delete'||modal.mode==='transition'){const deps=dependencies(modal.type,item,state);return <ManagementDialog title={`${modal.mode==='delete'?'删除':actionLabel(modal.event!)} ${displayName(modal.type,item)}`} onClose={close} footer={<><button onClick={close}>取消</button><button className="danger" onClick={confirm}>确认</button></>}><ImpactPanel title="影响分析" items={deps.length?deps:['无阻断依赖；操作将保留审计证据。']}/></ManagementDialog>}
  if(modal.mode==='delegate')return <ManagementDialog title="新增受委派管理员能力" onClose={close} footer={<><button onClick={close}>取消</button><button className="primary" onClick={delegate}>确认委派</button></>} size="wide"><div className="pm-form"><label>委派对象<select value={draft.subjectId} onChange={event=>setDraft({...draft,subjectId:event.target.value})}><option value="USR-BIZ">李沐（业务负责人）</option><option value="USR-TRAINER">周芮（AI训练师）</option><option value="USR-EMP">陈屿（员工）</option></select></label><ChoiceGrid label="对象类型" values={draft.objectTypes} options={['organization','position','user','reporting','config','budget','review']} onChange={objectTypes=>setDraft({...draft,objectTypes})}/><ChoiceGrid label="操作集合" values={draft.delegatedActions} options={['create','read','update','delete','disable','restore','archive','approve']} onChange={delegatedActions=>setDraft({...draft,delegatedActions})}/><label>数据范围<select value={draft.dataScope} onChange={event=>setDraft({...draft,dataScope:event.target.value})}>{['本人','项目','部门','组织','租户','平台','全租户'].map(option=><option key={option}>{option}</option>)}</select></label><ChoiceGrid label="目标范围" values={draft.scopeTargets} options={['ORG-LEAD','ORG-LEAD-CULTIVATE','ORG-CAPABILITY','ORG-MKT-HQ']} onChange={scopeTargets=>setDraft({...draft,scopeTargets})}/><label>风险上限<select value={draft.riskCeiling} onChange={event=>setDraft({...draft,riskCeiling:event.target.value})}>{['低','中','高','极高'].map(option=><option key={option}>{option}</option>)}</select></label><label>有效期<input type="date" value={draft.validTo} onChange={event=>setDraft({...draft,validTo:event.target.value})}/></label></div></ManagementDialog>;
  return <ManagementDialog title={`${modal.mode==='create'?'新增':'编辑'}${typeLabel(modal.type)}`} onClose={close} footer={<><button onClick={close}>取消</button><button className="primary" onClick={save}>保存</button></>} size="wide"><div className="pm-form"><Fields type={modal.type} draft={draft} setDraft={setDraft}/></div></ManagementDialog>;
}
function ChoiceGrid({label:legend,values=[],options,onChange}:{label:string;values:string[];options:string[];onChange:(values:string[])=>void}){return <fieldset className="pm-choice-grid"><legend>{legend}</legend>{options.map(option=><label key={option}><input type="checkbox" checked={values.includes(option)} onChange={()=>onChange(values.includes(option)?values.filter(value=>value!==option):[...values,option])}/><span>{option}</span></label>)}</fieldset>}
function Fields({type,draft,setDraft}:{type:ManagementObjectType;draft:any;setDraft:(draft:any)=>void}){const input=(key:string,label:string)=><label>{label}<input value={draft[key]??''} onChange={event=>setDraft({...draft,[key]:event.target.value})}/></label>;const select=(key:string,label:string,options:string[])=><label>{label}<select value={draft[key]??options[0]} onChange={event=>setDraft({...draft,[key]:event.target.value})}>{options.map(option=><option key={option}>{option}</option>)}</select></label>;if(type==='role')return <>{input('name','角色名称 *')}{select('risk','风险',['低','中','高','极高'])}<label className="wide">角色说明<textarea value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></label></>;if(type==='policy'||type==='scope')return <>{select('roleId','角色',['ROLE-EMPLOYEE','ROLE-BUSINESS','ROLE-TRAINER','ROLE-ADMIN'])}{input('moduleName','模块名称')}{input('page','页面')}{select('effect','效果',['允许','显式拒绝'])}{select('dataScope','数据范围',['本人','项目','部门','组织','租户','平台','全租户'])}{input('actionsText','操作（顿号分隔）')}{input('fieldsText','字段（顿号分隔）')}</>;return <>{input('name','复核批次名称 *')}{input('scope','复核范围')}{input('owner','负责人')}{input('dueAt','截止日期')}</>}
function toDraft(type:ManagementObjectType,item:any){if(type==='policy'||type==='scope')return {...item,actionsText:item.actions.join('、'),fieldsText:item.fields.join('、')};return {...item,name:item.name??displayName(type,item)}}
function buildPayload(type:ManagementObjectType,draft:any,existing:any){const id=existing?.id??`${type.toUpperCase().slice(0,4)}-${Date.now().toString().slice(-6)}`;if(type==='role')return {...existing,id,name:draft.name,kind:existing?.kind??'自定义',risk:draft.risk,status:existing?.status??'草稿',memberCount:existing?.memberCount??0,description:draft.description};if(type==='policy'||type==='scope')return {...existing,id,roleId:draft.roleId,moduleId:draft.moduleId??'custom',moduleName:draft.moduleName,page:draft.page,actions:String(draft.actionsText??'查看').split(/[、,]/),fields:String(draft.fieldsText??'常规字段').split(/[、,]/),effect:draft.effect,dataScope:draft.dataScope,risk:existing?.risk??'中'};return {...existing,id,name:draft.name,scope:draft.scope,owner:draft.owner,dueAt:draft.dueAt,status:existing?.status??'待开始',total:existing?.total??0,reviewed:existing?.reviewed??0,revokeSuggested:existing?.revokeSuggested??0}}
function transitionPayload(item:any,event:ManagementAction){return {status:event==='disable'?'停用':event==='restore'?'启用':event==='archive'?'归档':item.status}}
function typeLabel(type:ManagementObjectType){const labels:Partial<Record<ManagementObjectType,string>>={role:'角色',policy:'权限策略',scope:'数据范围',review:'复核批次'};return labels[type]??type}
