import React, { useMemo, useState } from 'react';
import { KeyRound, Plus, Search, ShieldCheck } from 'lucide-react';
import type { RoleId } from '../../types';
import { canSeeManagementModule, getManagementDecision, roleUserId, type ManageableObject, type ManagementAction, type ManagementObjectType } from './management-capability';
import { nameOfUser, type AccessRequest, type PermissionPolicy } from './platform-data';
import { usePlatformManagement } from './platform-management-store';
import { EmptyState, ImpactPanel, ManagementDetail, ManagementDialog, ManagementHeader, ManagementTabs, ManagementToolbar, OperationMenu, Risk, Status } from './shared/management-ui';
import './platform-management.css';

type View='roles'|'matrix'|'scopes'|'requests'|'conflicts'|'reviews'|'decisions';
type Detail={type:ManagementObjectType;id:string}|null;
type Modal={mode:'create'|'edit'|'delete'|'transition'|'delegate';type:ManagementObjectType;id?:string;event?:ManagementAction}|null;
const actorName:Record<RoleId,string>={employee:'陈屿',business:'李沐',trainer:'周芮',admin:'赵岑',superadmin:'顾川',client:'客户管理员'};
const tabs=[{id:'roles',label:'角色管理',description:'角色、成员与委派'},{id:'matrix',label:'权限矩阵',description:'页面、字段与动作'},{id:'scopes',label:'数据权限',description:'七级范围与边界'},{id:'requests',label:'授权申请',description:'申请、审批与回收'},{id:'conflicts',label:'职责冲突',description:'规则、命中与整改'},{id:'reviews',label:'权限复核',description:'批次与逐项复核'},{id:'decisions',label:'决策日志',description:'依据与审计证据'}];
const emptyDraft={name:'',description:'',risk:'中',roleId:'ROLE-TRAINER',moduleId:'agent-management',moduleName:'M03 Agent 管理',page:'Agent 工作台',effect:'允许',actions:['查看'],fields:['常规字段'],dataScope:'部门',permission:'M03 Agent 编辑',scopeTarget:'数字营销能力中台',reason:'',temporary:true,validTo:'2026-08-31',leftPermission:'',rightPermission:'',handling:'阻断',scope:'平台管理员与超级管理员',owner:'顾川',dueAt:'2026-08-31',subjectId:'USR-TRAINER',objectTypes:['config'],delegatedActions:['read','update'],scopeTargets:['ORG-CAPABILITY'],riskCeiling:'中'};

export function M16AccessControlPage({role}:{role:RoleId}){
  const {state,setState,execute}=usePlatformManagement();
  const [view,setView]=useState<View>(['employee','business','trainer'].includes(role)?'requests':'roles');
  const [detail,setDetail]=useState<Detail>(null);
  const [modal,setModal]=useState<Modal>(null);
  const [draft,setDraft]=useState<any>(emptyDraft);
  const [query,setQuery]=useState('');
  const [notice,setNotice]=useState('');
  const userId=roleUserId[role];
  const context={role,userId};
  const canEnter=canSeeManagementModule(role,'M16');
  const objectFor=(type:ManagementObjectType,item:any):ManageableObject=>({id:item.id,objectType:type,ownerId:type==='request'?item.applicantId:item.ownerId??item.subjectId,organizationId:organizationFor(type,item),tenantId:'TENANT-AIMP',status:item.status,risk:item.risk,protected:(type==='role'&&item.kind==='系统内置')||['ROLE-SUPERADMIN','POL-SUPER-ALL'].includes(item.id),dependencies:dependencies(type,item,state)});
  const decision=(type:ManagementObjectType,item:any,action:ManagementAction)=>getManagementDecision(context,objectFor(type,item),action);
  const visible=(type:ManagementObjectType,list:any[])=>list.filter(item=>decision(type,item,'read').allowed);
  const selected=detail?findItem(state,detail.type,detail.id):undefined;
  const run=(type:ManagementObjectType,item:any,action:ManagementAction,payload?:any)=>{const d=decision(type,item,action);if(!d.allowed){setNotice(`${d.reason} · ${d.auditId}`);return false}const result=execute({objectType:type,action,id:item.id,payload,actor:actorName[role],dependencies:action==='delete'?dependencies(type,item,state):undefined});setNotice(`${result.message}${result.blockedBy.length?` 依赖：${result.blockedBy.join('、')}`:''}`);if(result.ok&&action==='delete')setDetail(null);return result.ok};
  const openForm=(mode:'create'|'edit',type:ManagementObjectType,item?:any)=>{setDraft(item?toDraft(type,item):{...emptyDraft});setModal({mode,type,id:item?.id})};
  const save=()=>{if(!modal)return;if(!draft.name?.trim()&&!['policy','scope','request'].includes(modal.type)){setNotice('请填写名称。');return}const existing=findItem(state,modal.type,modal.id);const payload=buildPayload(modal.type,draft,existing,userId);if(modal.mode==='create'){const d=getManagementDecision(context,objectFor(modal.type,{...payload,ownerId:userId}),'create');if(!d.allowed){setNotice(`${d.reason} · ${d.auditId}`);return}execute({objectType:modal.type,action:'create',payload,actor:actorName[role]});setDetail({type:modal.type,id:payload.id});setNotice(`新增成功：${payload.id}`)}else if(existing)run(modal.type,existing,'update',payload);setModal(null)};
  const createDelegation=()=>{const id=`DEL-${Date.now().toString().slice(-6)}`;setState(s=>({...s,delegations:[{id,subjectId:draft.subjectId,objectTypes:draft.objectTypes,actions:draft.delegatedActions,dataScope:draft.dataScope,scopeTargets:draft.scopeTargets,validFrom:'2026-08-06',validTo:draft.validTo,riskCeiling:draft.riskCeiling,status:'生效'},...s.delegations],audits:[{id:`AUD-${id}`,at:'刚刚',actor:actorName[role],action:'创建委派',object:id,detail:`${draft.subjectId} · ${draft.objectTypes.join('、')}`},...s.audits]}));setNotice(`委派已生效：${id}`);setModal(null)};
  if(!canEnter)return <section className="pm-gate"><ShieldCheck/><h1>M16 权限管理不可访问</h1><p>当前身份没有内部权限管理能力；客户管理员请在客户门户管理本租户成员。</p></section>;
  const listFor=(v:View)=>v==='roles'?visible('role',state.roles):v==='matrix'||v==='scopes'?visible('policy',state.policies):v==='requests'?visible('request',state.requests):v==='conflicts'?visible('conflict',state.conflicts):v==='reviews'?visible('review',state.reviews):visible('decision',state.decisions);
  return <section className="pm"><ManagementHeader title="M16 权限管理" subtitle="统一管理角色、对象级权限、数据范围、委派、审批和决策证据"/>
    {selected&&detail?<M16Detail type={detail.type} item={selected} state={state} role={role} back={()=>setDetail(null)} open={setDetail} decision={decision} edit={()=>openForm('edit',detail.type,selected)} remove={()=>setModal({mode:'delete',type:detail.type,id:selected.id})} transition={event=>setModal({mode:'transition',type:detail.type,id:selected.id,event})} delegate={()=>{setDraft({...emptyDraft});setModal({mode:'delegate',type:'role',id:selected.id})}} setState={setState} notice={setNotice}/>:<main className="pm-content"><ManagementTabs items={tabs} value={view} onChange={id=>{setView(id as View);setDetail(null)}}/>
      <ManagementToolbar><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名称、主体或审计 ID"/></label><span>对象与动作已按身份、范围和有效期过滤</span>{!['decisions'].includes(view)&&<button className="primary" onClick={()=>openForm('create',view==='roles'?'role':view==='matrix'||view==='scopes'?'policy':view==='requests'?'request':view==='conflicts'?'conflict':'review')}><Plus/>新增</button>}</ManagementToolbar>
      {view==='scopes'?<ScopeCards items={listFor(view) as PermissionPolicy[]} open={setDetail}/>:<M16Table type={view==='roles'?'role':view==='matrix'?'policy':view==='requests'?'request':view==='conflicts'?'conflict':view==='reviews'?'review':'decision'} items={listFor(view)} query={query} open={setDetail} decision={decision} action={(type,item,action)=>action==='delete'?setModal({mode:'delete',type,id:item.id}):action==='update'?openForm('edit',type,item):setModal({mode:'transition',type,id:item.id,event:action})}/>} 
    </main>}
    {modal&&<M16Modal modal={modal} item={findItem(state,modal.type,modal.id)} state={state} draft={draft} setDraft={setDraft} close={()=>setModal(null)} save={save} delegate={createDelegation} confirm={()=>{const item=findItem(state,modal.type,modal.id);if(!item)return;if(modal.mode==='delete')run(modal.type,item,'delete');else {const event=modal.event!;const payload=transitionPayload(modal.type,item,event);run(modal.type,item,event,payload)}setModal(null)}}/>}
    {notice&&<div className="pm-notice">{notice}<button onClick={()=>setNotice('')}>关闭</button></div>}
  </section>
}

function organizationFor(type:ManagementObjectType,item:any){if(type==='request'&&item.applicantId==='USR-EMP')return 'ORG-LEAD-CULTIVATE';if(type==='request'&&item.applicantId==='USR-BIZ')return 'ORG-LEAD';if(type==='request'&&item.applicantId==='USR-TRAINER')return 'ORG-CAPABILITY';return item.organizationId}
function dependencies(type:ManagementObjectType,item:any,state:any){if(type==='role')return [...(item.memberCount?[`${item.memberCount} 名成员`]:[]),...state.policies.filter((p:any)=>p.roleId===item.id).map((p:any)=>`策略 ${p.id}`),...state.requests.filter((r:any)=>r.targetRoleId===item.id&&r.status==='已生效').map((r:any)=>`授权 ${r.id}`)];if(type==='policy'&&item.effect)return ['已发布策略版本'];if(type==='request'&&item.status!=='草稿')return [`当前状态 ${item.status}`];if(type==='conflict'&&item.hitCount)return [`${item.hitCount} 条命中记录`];if(type==='review'&&item.status!=='待开始')return [`复核批次 ${item.status}`];return []}
function findItem(state:any,type:ManagementObjectType,id?:string){if(!id)return;const keys:Partial<Record<ManagementObjectType,string>>={role:'roles',policy:'policies',scope:'policies',request:'requests',conflict:'conflicts',review:'reviews',decision:'decisions'};const key=keys[type];return key?state[key].find((i:any)=>i.id===id):undefined}
function displayName(type:ManagementObjectType,i:any){if(type==='policy'||type==='scope')return `${i.roleId} · ${i.moduleName}`;if(type==='request')return `${i.applicantName} · ${i.permission}`;if(type==='decision')return `${i.subject} · ${i.action}`;return i.name}
function displayOwner(type:ManagementObjectType,i:any){if(type==='role')return `${i.kind} · ${i.memberCount} 人`;if(type==='policy'||type==='scope')return `${i.page} · ${i.dataScope}`;if(type==='request')return `${i.scopeTarget} · ${i.validTo}`;if(type==='conflict')return `${i.handling} · 命中 ${i.hitCount}`;if(type==='review')return `${i.owner} · ${i.reviewed}/${i.total}`;return `${i.module} · ${i.resource}`}
function actionsFor(type:ManagementObjectType,item:any):ManagementAction[]{if(type==='decision')return [];const a:ManagementAction[]=['update'];if(type==='request'){if(item.status==='草稿')return ['update','delete'];if(['待审批','审批中'].includes(item.status))return ['approve'];if(item.status==='已生效')return ['revoke'];return []}if(['停用','归档'].includes(item.status))a.push('restore');else a.push('disable','archive');a.push('delete');return a}
const label=(a:ManagementAction)=>({update:'编辑',delete:'删除',disable:'停用',restore:'恢复',archive:'归档',approve:'审批',revoke:'回收',create:'新增',read:'查看',publish:'发布',delegate:'委派'}[a]);

function M16Table({type,items,query,open,decision,action}:{type:ManagementObjectType;items:any[];query:string;open:(d:Detail)=>void;decision:any;action:(type:ManagementObjectType,item:any,a:ManagementAction)=>void}){const filtered=items.filter(i=>!query||JSON.stringify(i).toLowerCase().includes(query.toLowerCase()));if(!filtered.length)return <EmptyState text="当前范围暂无对象"/>;return <div className="pm-table-wrap"><table><thead><tr><th>对象</th><th>类型 / 范围</th><th>风险</th><th>状态 / 结果</th><th>操作</th></tr></thead><tbody>{filtered.map(i=><tr key={i.id} onClick={()=>open({type,id:i.id})}><td><b>{displayName(type,i)}</b><small>{i.id}</small></td><td>{displayOwner(type,i)}</td><td>{i.risk?<Risk value={i.risk}/>:<span>—</span>}</td><td><Status value={i.status??i.result??i.effect}/></td><td onClick={e=>e.stopPropagation()}><button onClick={()=>open({type,id:i.id})}>详情</button>{actionsFor(type,i).length>0&&<OperationMenu items={actionsFor(type,i).map(a=>({label:label(a),onClick:()=>action(type,i,a),disabled:!decision(type,i,a).allowed,reason:decision(type,i,a).reason,danger:a==='delete'||a==='revoke'}))}/>}</td></tr>)}</tbody></table></div>}
function ScopeCards({items,open}:{items:PermissionPolicy[];open:(d:Detail)=>void}){return <section className="pm-card-list">{items.map(i=><article key={i.id} onClick={()=>open({type:'scope',id:i.id})}><header><div><b>{i.roleId} · {i.moduleName}</b><small>{i.id}</small></div><Status value={i.dataScope}/></header><p>页面：{i.page} · 字段：{i.fields.join('、')}</p><footer><button onClick={e=>{e.stopPropagation();open({type:'scope',id:i.id})}}>进入范围详情</button></footer></article>)}</section>}

function M16Detail({type,item,state,role,back,open,decision,edit,remove,transition,delegate,setState,notice}:{type:ManagementObjectType;item:any;state:any;role:RoleId;back:()=>void;open:(d:Detail)=>void;decision:any;edit:()=>void;remove:()=>void;transition:(a:ManagementAction)=>void;delegate:()=>void;setState:any;notice:(s:string)=>void}){const [tab,setTab]=useState('基本信息');const tabs=['基本信息','关联与成员','权限/状态','审计证据'];const metrics=[{label:'状态',value:item.status??item.result??item.effect},{label:'风险',value:item.risk??'—'},{label:'数据范围',value:item.dataScope??item.scope??'—'},{label:'当前权限',value:decision(type,item,'update').allowed?'可管理':'只读'}];return <ManagementDetail title={displayName(type,item)} meta={`${item.id} · ${type}`} backLabel="返回列表" onBack={back} metrics={metrics} tabs={<nav className="pm-detail-tabs">{tabs.map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</nav>} actions={<>{type!=='decision'&&<button disabled={!decision(type,item,'update').allowed} title={decision(type,item,'update').reason} onClick={edit}>编辑</button>}{type==='role'&&<button disabled={!decision(type,item,'delegate').allowed} onClick={delegate}>新增委派</button>}{actionsFor(type,item).filter(a=>a!=='update').length>0&&<OperationMenu items={actionsFor(type,item).filter(a=>a!=='update').map(a=>({label:label(a),onClick:()=>a==='delete'?remove():transition(a),disabled:!decision(type,item,a).allowed,reason:decision(type,item,a).reason,danger:a==='delete'||a==='revoke'}))}/>}</>}>
  {tab==='基本信息'&&<article className="pm-panel"><header><b>对象资料</b></header><dl>{Object.entries(item).filter(([,v])=>typeof v!=='object').map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{String(v)}</dd></React.Fragment>)}</dl></article>}
  {tab==='关联与成员'&&<Related type={type} item={item} state={state} open={open} setState={setState} notice={notice} canManage={decision(type,item,'delegate').allowed}/>} 
  {tab==='权限/状态'&&<article className="pm-panel"><header><b>动作决策</b></header>{(['read','update','delete','approve','revoke','delegate'] as ManagementAction[]).map(a=><div className="pm-list-row" key={a}><b>{label(a)}</b><Status value={decision(type,item,a).allowed?'允许':'拒绝'}/><span>{decision(type,item,a).reason}</span></div>)}</article>}
  {tab==='审计证据'&&(type==='decision'?<DecisionEvidence item={item}/>:<div className="pm-table-wrap"><table><tbody>{state.audits.filter((a:any)=>a.object===item.id).map((a:any)=><tr key={a.id}><td>{a.at}</td><td>{a.action}</td><td>{a.detail}</td></tr>)}</tbody></table></div>)}
  </ManagementDetail>}
function Related({type,item,state,open,setState,notice,canManage}:{type:ManagementObjectType;item:any;state:any;open:(d:Detail)=>void;setState:any;notice:(s:string)=>void;canManage:boolean}){
  const [subjectId,setSubjectId]=useState('USR-EMP');
  const [source,setSource]=useState('直接授权');
  const [validTo,setValidTo]=useState('2026-12-31');
  if(type==='role'){
    const bindings=state.bindings.filter((binding:any)=>binding.roleId===item.id);
    const delegations=state.delegations.filter((delegation:any)=>delegation.status!=='回收');
    const bind=()=>{const id=`BIND-${Date.now().toString().slice(-6)}`;setState((s:any)=>({...s,bindings:[{id,subjectType:'用户',subjectId,roleId:item.id,validFrom:'2026-08-06',validTo,source,status:'生效'},...s.bindings],roles:s.roles.map((role:any)=>role.id===item.id?{...role,memberCount:role.memberCount+1}:role),audits:[{id:`AUD-${id}`,at:'刚刚',actor:'当前管理员',action:'绑定角色成员',object:item.id,detail:`${nameOfUser(subjectId)} · ${source} · 至 ${validTo}`},...s.audits]}));notice(`已将 ${nameOfUser(subjectId)} 绑定到 ${item.name}`)};
    const revoke=(binding:any)=>{setState((s:any)=>({...s,bindings:s.bindings.map((x:any)=>x.id===binding.id?{...x,status:'回收'}:x),roles:s.roles.map((role:any)=>role.id===item.id?{...role,memberCount:Math.max(0,role.memberCount-1)}:role),audits:[{id:`AUD-${Date.now().toString().slice(-6)}`,at:'刚刚',actor:'当前管理员',action:'回收角色成员',object:item.id,detail:`${nameOfUser(binding.subjectId)} · ${binding.id}`},...s.audits]}));notice(`成员绑定 ${binding.id} 已回收`)};
    return <div className="pm-related-stack"><article className="pm-panel"><header><b>角色成员</b><span>{bindings.filter((binding:any)=>binding.status==='生效').length} 项生效绑定</span></header>{canManage&&<div className="pm-inline-form"><select aria-label="选择成员" value={subjectId} onChange={event=>setSubjectId(event.target.value)}>{state.users.map((user:any)=><option key={user.id} value={user.id}>{user.name} · {user.account}</option>)}</select><select aria-label="授权来源" value={source} onChange={event=>setSource(event.target.value)}><option>直接授权</option><option>岗位继承</option><option>组织继承</option><option>临时申请</option></select><input aria-label="有效期" type="date" value={validTo} onChange={event=>setValidTo(event.target.value)}/><button className="primary" onClick={bind}>绑定成员</button></div>}{bindings.map((binding:any)=><div className="pm-list-row" key={binding.id}><span><b>{nameOfUser(binding.subjectId)}</b><small>{binding.source} · {binding.validFrom} 至 {binding.validTo}</small></span><Status value={binding.status}/>{canManage&&binding.status==='生效'&&<button onClick={()=>revoke(binding)}>回收</button>}</div>)}</article><article className="pm-panel"><header><b>受委派管理员能力</b></header>{delegations.map((delegation:any)=><div className="pm-list-row" key={delegation.id}><span><b>{nameOfUser(delegation.subjectId)}</b><small>{delegation.objectTypes.join('、')} · {delegation.scopeTargets.join('、')} · 至 {delegation.validTo}</small></span><Status value={delegation.status}/>{canManage&&<button onClick={()=>{setState((s:any)=>({...s,delegations:s.delegations.map((x:any)=>x.id===delegation.id?{...x,status:'回收'}:x),audits:[{id:`AUD-${Date.now().toString().slice(-6)}`,at:'刚刚',actor:'当前管理员',action:'回收委派',object:delegation.id,detail:`${nameOfUser(delegation.subjectId)} 的范围委派已回收`},...s.audits]}));notice(`委派 ${delegation.id} 已回收`)}}>回收委派</button>}</div>)}</article></div>;
  }
  if(type==='conflict')return <article className="pm-panel"><header><b>命中与整改</b></header>{state.conflictHits.filter((h:any)=>h.ruleId===item.id).map((h:any)=><div className="pm-list-row" key={h.id}><span><b>{nameOfUser(h.subjectId)}</b><small>{h.objectId} · {h.resolution}</small></span><Status value={h.status}/><button onClick={()=>open({type:'request',id:h.objectId})}>查看申请</button></div>)}</article>;
  if(type==='review')return <article className="pm-panel"><header><b>逐项复核</b></header>{state.reviewItems.filter((r:any)=>r.reviewId===item.id).map((r:any)=><div className="pm-list-row" key={r.id}><span><b>{nameOfUser(r.subjectId)}</b><small>{r.permission} · 最近使用 {r.lastUsed}</small></span><Status value={r.status}/><select disabled={!canManage} value={r.status} onChange={e=>{setState((s:any)=>({...s,reviewItems:s.reviewItems.map((x:any)=>x.id===r.id?{...x,status:e.target.value}:x),audits:[{id:`AUD-${Date.now().toString().slice(-6)}`,at:'刚刚',actor:'当前复核人',action:'更新复核项',object:r.id,detail:e.target.value},...s.audits]}));notice(`复核项 ${r.id} 已更新`)}}><option>待复核</option><option>已保留</option><option>已回收</option><option>已转交</option></select></div>)}</article>;
  if(type==='request')return <article className="pm-panel"><header><b>审批时间线</b></header>{['创建申请','提交审批',item.status].map((x,n)=><div className="pm-audit" key={x}><b>{x}</b><span>步骤 {n+1}</span><p>{n===2?'当前状态':'已完成'}</p></div>)}</article>;
  return <EmptyState text="暂无关联对象"/>;
}
function DecisionEvidence({item}:{item:any}){return <article className="pm-panel"><header><b>不可修改的决策证据</b></header><dl><dt>主体</dt><dd>{item.subject}</dd><dt>资源</dt><dd>{item.resource}</dd><dt>请求动作</dt><dd>{item.action}</dd><dt>数据范围</dt><dd>{item.dataScope}</dd><dt>命中策略</dt><dd>{item.matchedPolicies.join('、')}</dd><dt>最终原因</dt><dd>{item.reason}</dd><dt>审计 ID</dt><dd>{item.id}</dd></dl></article>}

function M16Modal({modal,item,state,draft,setDraft,close,save,delegate,confirm}:{modal:Modal;item:any;state:any;draft:any;setDraft:(d:any)=>void;close:()=>void;save:()=>void;delegate:()=>void;confirm:()=>void}){if(!modal)return null;if(modal.mode==='delete'||modal.mode==='transition'){const deps=dependencies(modal.type,item,state);return <ManagementDialog title={`${modal.mode==='delete'?'删除':label(modal.event!)} ${displayName(modal.type,item)}`} onClose={close} footer={<><button onClick={close}>取消</button><button className="danger" onClick={confirm}>确认</button></>}><ImpactPanel title="影响分析" items={deps.length?deps:['无阻断依赖；操作将保留审计证据。']}/></ManagementDialog>};if(modal.mode==='delegate')return <ManagementDialog title="新增受委派管理员能力" onClose={close} footer={<><button onClick={close}>取消</button><button className="primary" onClick={delegate}>确认委派</button></>} size="wide"><div className="pm-form"><label>委派对象<select value={draft.subjectId} onChange={e=>setDraft({...draft,subjectId:e.target.value})}><option value="USR-BIZ">李沐（业务负责人）</option><option value="USR-TRAINER">周芮（AI训练师）</option><option value="USR-EMP">陈屿（员工）</option></select></label><ChoiceGrid label="对象类型" values={draft.objectTypes} options={['organization','position','user','reporting','config','budget','request','review']} onChange={objectTypes=>setDraft({...draft,objectTypes})}/><ChoiceGrid label="操作集合" values={draft.delegatedActions} options={['create','read','update','delete','disable','restore','archive','approve']} onChange={delegatedActions=>setDraft({...draft,delegatedActions})}/><label>数据范围<select value={draft.dataScope} onChange={e=>setDraft({...draft,dataScope:e.target.value})}>{['本人','项目','部门','组织','租户','平台'].map(x=><option key={x}>{x}</option>)}</select></label><ChoiceGrid label="目标范围" values={draft.scopeTargets} options={['ORG-LEAD','ORG-LEAD-CULTIVATE','ORG-CAPABILITY','ORG-MKT-HQ']} onChange={scopeTargets=>setDraft({...draft,scopeTargets})}/><label>有效期<input type="date" value={draft.validTo} onChange={e=>setDraft({...draft,validTo:e.target.value})}/></label></div></ManagementDialog>;return <ManagementDialog title={`${modal.mode==='create'?'新增':'编辑'}${typeLabel(modal.type)}`} onClose={close} footer={<><button onClick={close}>取消</button><button className="primary" onClick={save}>保存</button></>} size="wide"><div className="pm-form"><Fields type={modal.type} draft={draft} setDraft={setDraft}/></div></ManagementDialog>}
function ChoiceGrid({label:legend,values=[],options,onChange}:{label:string;values:string[];options:string[];onChange:(values:string[])=>void}){return <fieldset className="pm-choice-grid"><legend>{legend}</legend>{options.map(option=><label key={option}><input type="checkbox" checked={values.includes(option)} onChange={()=>onChange(values.includes(option)?values.filter(value=>value!==option):[...values,option])}/><span>{option}</span></label>)}</fieldset>}
function Fields({type,draft,setDraft}:{type:ManagementObjectType;draft:any;setDraft:(d:any)=>void}){const input=(k:string,l:string)=><label>{l}<input value={draft[k]??''} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>;const select=(k:string,l:string,o:string[])=><label>{l}<select value={draft[k]??o[0]} onChange={e=>setDraft({...draft,[k]:e.target.value})}>{o.map(x=><option key={x}>{x}</option>)}</select></label>;if(type==='role')return <>{input('name','角色名称 *')}{select('risk','风险',['低','中','高','极高'])}<label className="wide">角色说明<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label></>;if(type==='policy'||type==='scope')return <>{select('roleId','角色',['ROLE-EMPLOYEE','ROLE-BUSINESS','ROLE-TRAINER','ROLE-ADMIN'])}{input('moduleName','模块名称')}{input('page','页面')}{select('effect','效果',['允许','显式拒绝'])}{select('dataScope','数据范围',['本人','项目','部门','组织','租户','平台','全租户'])}{input('actionsText','操作（顿号分隔）')}{input('fieldsText','字段（顿号分隔）')}</>;if(type==='request')return <>{select('roleId','目标角色',['ROLE-LEAD-QA','ROLE-TRAINER','ROLE-ADMIN'])}{input('permission','申请权限')}{select('dataScope','数据范围',['本人','项目','部门','组织','租户','平台'])}{input('scopeTarget','范围对象')}<label className="wide">业务理由<textarea value={draft.reason} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label>{input('validTo','有效期')}</>;if(type==='conflict')return <>{input('name','规则名称 *')}{input('leftPermission','权限 A')}{input('rightPermission','权限 B')}{select('handling','处理方式',['阻断','例外审批'])}{select('risk','风险',['低','中','高','极高'])}</>;return <>{input('name','复核批次名称 *')}{input('scope','复核范围')}{input('owner','负责人')}{input('dueAt','截止日期')}</>}
function toDraft(type:ManagementObjectType,item:any){if(type==='policy'||type==='scope')return {...item,actionsText:item.actions.join('、'),fieldsText:item.fields.join('、')};return {...item,name:item.name??displayName(type,item),roleId:item.targetRoleId??item.roleId}}
function buildPayload(type:ManagementObjectType,d:any,e:any,userId:string){const id=e?.id??`${type.toUpperCase().slice(0,4)}-${Date.now().toString().slice(-6)}`;if(type==='role')return {...e,id,name:d.name,kind:e?.kind??'自定义',risk:d.risk,status:e?.status??'草稿',memberCount:e?.memberCount??0,description:d.description};if(type==='policy'||type==='scope')return {...e,id,roleId:d.roleId,moduleId:d.moduleId??'custom',moduleName:d.moduleName,page:d.page,actions:String(d.actionsText??'查看').split(/[、,]/),fields:String(d.fieldsText??'常规字段').split(/[、,]/),effect:d.effect,dataScope:d.dataScope,risk:e?.risk??'中'};if(type==='request')return {...e,id,applicantId:e?.applicantId??userId,applicantName:e?.applicantName??nameOfUser(userId),targetRoleId:d.roleId,permission:d.permission,dataScope:d.dataScope,scopeTarget:d.scopeTarget,reason:d.reason,temporary:true,validTo:d.validTo,risk:e?.risk??'中',status:e?.status??'草稿',approvers:e?.approvers??['赵岑'],conflictIds:e?.conflictIds??[],createdAt:e?.createdAt??'刚刚'} as AccessRequest;if(type==='conflict')return {...e,id,name:d.name,leftPermission:d.leftPermission,rightPermission:d.rightPermission,risk:d.risk,handling:d.handling,hitCount:e?.hitCount??0,status:e?.status??'草稿'};return {...e,id,name:d.name,scope:d.scope,owner:d.owner,dueAt:d.dueAt,status:e?.status??'待开始',total:e?.total??0,reviewed:e?.reviewed??0,revokeSuggested:e?.revokeSuggested??0}}
function transitionPayload(type:ManagementObjectType,item:any,event:ManagementAction){if(type==='request')return {status:event==='approve'?'已生效':event==='revoke'?'已回收':item.status};return {status:event==='disable'?'停用':event==='restore'?'启用':event==='archive'?'归档':item.status}}
function typeLabel(t:ManagementObjectType){const labels:Partial<Record<ManagementObjectType,string>>={role:'角色',policy:'权限策略',scope:'数据范围',request:'授权申请',conflict:'冲突规则',review:'复核批次'};return labels[t]??t}
