import React, { useMemo, useState } from 'react';
import { ArrowLeft, ChevronRight, Plus, Search, X } from 'lucide-react';
import type { RoleId } from '../../types';
import { useModelBillingRegistry } from './model-billing-store';
import type { ModelConnection, ModelHealth, ModelLifecycle, ModelProviderType } from './model-billing-types';

const providers:ModelProviderType[]=['OpenAI','Azure OpenAI','百炼','火山方舟','百度千帆','腾讯混元','DeepSeek','私有化','OpenAI Compatible'];
const healths:ModelHealth[]=['正常','波动','故障','维护中'];
const lifecycles:ModelLifecycle[]=['草稿','测试中','待审核','已发布','已停用','已归档'];
const tabs=['基本配置','模型目录','路由与限流','调试与健康','依赖与影响','版本与审计'];
const actor:Record<RoleId,string>={employee:'陈屿',business:'李沐',trainer:'周芮',admin:'赵岑',superadmin:'顾川',client:'客户管理员'};
const canEdit=(role:RoleId)=>['trainer','admin','superadmin'].includes(role);
const canGovern=(role:RoleId)=>['admin','superadmin'].includes(role);

export function ModelAccessWorkspace({role,readOnly=false}:{role:RoleId;readOnly?:boolean}){
  const registry=useModelBillingRegistry();
  const [query,setQuery]=useState('');
  const [provider,setProvider]=useState('全部供应商');
  const [health,setHealth]=useState('全部健康度');
  const [lifecycle,setLifecycle]=useState('全部生命周期');
  const [selectedId,setSelectedId]=useState<string|null>(null);
  const [wizard,setWizard]=useState(false);
  const [notice,setNotice]=useState('');
  const rows=useMemo(()=>registry.state.connections.filter(item=>(!query||JSON.stringify(item).toLowerCase().includes(query.toLowerCase()))&&(provider==='全部供应商'||item.provider===provider)&&(health==='全部健康度'||item.health===health)&&(lifecycle==='全部生命周期'||item.lifecycle===lifecycle)),[registry.state.connections,query,provider,health,lifecycle]);
  const selected=registry.state.connections.find(item=>item.id===selectedId);
  if(selected)return <ModelWorkbench role={role} readOnly={readOnly} connection={selected} back={()=>setSelectedId(null)} notify={setNotice} notice={notice}/>;
  return <section className="mb-workspace">
    <header className="mb-toolbar"><div><h2>大模型接入</h2><p>{readOnly?'查看当前部门可用的供应商连接、模型版本、路由与健康状态。':'统一维护供应商连接、模型版本、路由、健康和生产依赖。'}</p></div><div className="mb-toolbar-actions"><label className="mb-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索连接、模型或 ID"/></label>{!readOnly&&canEdit(role)&&<button className="primary" onClick={()=>setWizard(true)}><Plus/>新建连接</button>}</div></header>
    <div className="mb-filters"><select value={provider} onChange={e=>setProvider(e.target.value)}><option>全部供应商</option>{providers.map(v=><option key={v}>{v}</option>)}</select><select value={health} onChange={e=>setHealth(e.target.value)}><option>全部健康度</option>{healths.map(v=><option key={v}>{v}</option>)}</select><select value={lifecycle} onChange={e=>setLifecycle(e.target.value)}><option>全部生命周期</option>{lifecycles.map(v=><option key={v}>{v}</option>)}</select><span>共 {rows.length} 个连接</span></div>
    <div className="mb-table-wrap"><table><thead><tr><th>供应商与连接</th><th>区域</th><th>健康</th><th>模型</th><th>P95</th><th>今日调用</th><th>版本</th><th>生命周期</th><th>操作</th></tr></thead><tbody>{rows.map(item=><tr key={item.id} onClick={()=>setSelectedId(item.id)}><td><b>{item.name}</b><small>{item.provider} · {item.id}</small></td><td>{item.region}</td><td><Badge value={item.health}/></td><td>{item.models.length} 个</td><td>{item.p95?`${item.p95}ms`:'—'}</td><td>{item.todayCalls.toLocaleString()}</td><td>{item.version}</td><td><Badge value={item.lifecycle}/></td><td><button onClick={e=>{e.stopPropagation();setSelectedId(item.id)}}>{readOnly?'查看详情':'进入工作台'} <ChevronRight/></button></td></tr>)}</tbody></table></div>
    {!rows.length&&<div className="mb-empty">没有符合当前条件的模型连接。</div>}
    {wizard&&<ConnectionWizard role={role} close={()=>setWizard(false)} save={connection=>{const result=registry.createConnection(connection);setNotice(result.message);if(result.ok){setWizard(false);setSelectedId(connection.id)}}}/>} 
    {notice&&<Toast text={notice} close={()=>setNotice('')}/>} 
  </section>
}

function ModelWorkbench({role,connection,back,notify,notice,readOnly=false}:{role:RoleId;connection:ModelConnection;back:()=>void;notify:(v:string)=>void;notice:string;readOnly?:boolean}){
  const registry=useModelBillingRegistry();
  const [tab,setTab]=useState(tabs[0]);
  const [editing,setEditing]=useState(false);
  const [draft,setDraft]=useState(connection);
  const [testInput,setTestInput]=useState('{\n  "messages": [{"role":"user","content":"分析线索评分偏差"}]\n}');
  const [testResult,setTestResult]=useState('');
  const run=(fn:()=>{message:string})=>notify(fn().message);
  const save=()=>{const result=registry.updateConnection(role,draft);notify(result.message);if(result.ok)setEditing(false)};
  const runTest=()=>{try{JSON.parse(testInput);const passed=!testInput.includes('timeout');const evidence={id:`MEVI-${Date.now()}`,connectionId:connection.id,modelId:connection.models[0]?.modelId??'unknown',source:'M15' as const,passed,latency:passed?684:60000,score:passed?96:0,createdAt:'刚刚',detail:passed?'连通、鉴权、结构化输出与限流响应均通过':'请求超时，未通过发布门禁'};registry.recordModelTestEvidence(evidence);setTestResult(passed?`200 OK · ${evidence.latency}ms · 评分 ${evidence.score}\n{ "status": "healthy", "trace": "${evidence.id}" }`:`TIMEOUT · ${evidence.latency}ms\n请检查网络范围、超时与路由策略。`);notify(passed?'连接测试通过，证据已保存。':'连接测试失败，已记录证据。')}catch{notify('测试输入不是合法 JSON，无法运行。')}};
  return <section className="mb-workspace">
    <header className="mb-detail-head"><button onClick={back}><ArrowLeft/>返回连接目录</button><div><h2>{connection.name}</h2><p>{connection.id} · {connection.provider} · {connection.version}</p></div><div className="mb-head-actions"><Badge value={connection.health}/><Badge value={connection.lifecycle}/>{!readOnly&&canEdit(role)&&connection.lifecycle!=='已发布'&&<button onClick={()=>setEditing(!editing)}>{editing?'取消编辑':'编辑草稿'}</button>}{!readOnly&&canEdit(role)&&connection.lifecycle==='草稿'&&<button onClick={()=>run(()=>registry.transitionConnection(role,connection.id,'测试中'))}>进入测试</button>}{!readOnly&&canEdit(role)&&['草稿','测试中'].includes(connection.lifecycle)&&<button className="primary" onClick={()=>run(()=>registry.transitionConnection(role,connection.id,'待审核'))}>提交审核</button>}{!readOnly&&canGovern(role)&&connection.lifecycle==='待审核'&&<button className="primary" onClick={()=>run(()=>registry.transitionConnection(role,connection.id,'已发布'))}>审核发布</button>}{!readOnly&&<MoreLifecycle role={role} connection={connection} notify={notify}/>}</div></header>
    <nav className="mb-tabs">{tabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</nav>
    {tab==='基本配置'&&<div className="mb-panel"><SectionTitle title="连接资料" subtitle="生产凭据只展示 Secret ID，不读取或显示明文。"/><div className="mb-form-grid"><Field label="连接名称"><input disabled={!editing} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="供应商"><select disabled={!editing} value={draft.provider} onChange={e=>setDraft({...draft,provider:e.target.value as ModelProviderType})}>{providers.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Base URL"><input disabled={!editing} value={draft.baseUrl} onChange={e=>setDraft({...draft,baseUrl:e.target.value})}/></Field><Field label="区域"><input disabled={!editing} value={draft.region} onChange={e=>setDraft({...draft,region:e.target.value})}/></Field><Field label="Secret ID"><input disabled={!editing} value={draft.secretRef} onChange={e=>setDraft({...draft,secretRef:e.target.value})}/><small>仅保存密钥引用。</small></Field><Field label="负责人"><input disabled={!editing} value={draft.owner} onChange={e=>setDraft({...draft,owner:e.target.value})}/></Field></div>{editing&&<div className="mb-form-actions"><button onClick={()=>{setDraft(connection);setEditing(false)}}>取消</button><button className="primary" onClick={save}>保存草稿</button></div>}</div>}
    {tab==='模型目录'&&<div className="mb-panel"><SectionTitle title="可用模型版本" subtitle="只有已发布且健康正常的模型可被 Agent 和工作流绑定。"/><div className="mb-table-wrap"><table><thead><tr><th>模型</th><th>上下文</th><th>模态</th><th>健康</th><th>生命周期</th><th>输入价格</th><th>输出价格</th></tr></thead><tbody>{connection.models.map(model=><tr key={model.id}><td><b>{model.displayName}</b><small>{model.modelId}</small></td><td>{model.contextWindow.toLocaleString()}</td><td>{model.modalities.join(' / ')}</td><td><Badge value={model.health}/></td><td><Badge value={model.lifecycle}/></td><td>{model.currency} {model.inputPrice}/百万</td><td>{model.currency} {model.outputPrice}/百万</td></tr>)}</tbody></table></div>{!readOnly&&canEdit(role)&&connection.lifecycle!=='已发布'&&<button onClick={()=>notify('已新增模型草稿行，可在保存连接时一并提交。')}><Plus/>新增模型</button>}</div>}
    {tab==='路由与限流'&&<div className="mb-panel"><SectionTitle title="路由、超时与保护策略" subtitle="连接级策略由平台统一治理，业务 Agent 不可覆盖生产上限。"/><div className="mb-form-grid"><Field label="路由策略"><textarea disabled={!editing} value={draft.routePolicy} onChange={e=>setDraft({...draft,routePolicy:e.target.value})}/></Field><Field label="超时（秒）"><input type="number" disabled={!editing} value={draft.timeout} onChange={e=>setDraft({...draft,timeout:Number(e.target.value)})}/></Field><Field label="每分钟限流"><input type="number" disabled={!editing} value={draft.rateLimit} onChange={e=>setDraft({...draft,rateLimit:Number(e.target.value)})}/></Field><Field label="失败处理"><select disabled={!editing}><option>重试 2 次后切换备线</option><option>立即熔断并告警</option><option>降级到轻量模型</option></select></Field></div></div>}
    {tab==='调试与健康'&&<div className="mb-split">{!readOnly&&<div className="mb-panel"><SectionTitle title="连接调试" subtitle="模拟请求不会访问真实外部模型。"/><Field label="测试输入 JSON"><textarea className="mb-code" value={testInput} onChange={e=>setTestInput(e.target.value)}/></Field><button className="primary" onClick={runTest}>运行连通与契约测试</button>{testResult&&<pre className="mb-result">{testResult}</pre>}</div>}<div className="mb-panel"><SectionTitle title="健康与测试证据" subtitle={`当前 P95 ${connection.p95||'—'}ms`}/>{registry.state.testEvidence.filter(item=>item.connectionId===connection.id).map(item=><div className="mb-list-row" key={item.id}><span><b>{item.source} · {item.id}</b><small>{item.createdAt} · {item.latency}ms · 评分 {item.score}</small></span><Badge value={item.passed?'通过':'失败'}/><p>{item.detail}</p></div>)}</div></div>}
    {tab==='依赖与影响'&&<div className="mb-panel"><SectionTitle title="生产依赖与变更影响" subtitle="停用、归档或版本变更前必须查看影响，不自动改写生产依赖。"/>{connection.dependencies.length?connection.dependencies.map(dep=><div className="mb-list-row" key={dep.id}><span><b>{dep.name}</b><small>{dep.type} · {dep.id} · {dep.version}</small></span><p>{dep.scope}</p><button onClick={()=>notify(`已定位依赖对象：${dep.id}`)}>查看对象</button></div>):<div className="mb-empty">当前连接没有登记依赖。</div>}</div>}
    {tab==='版本与审计'&&<div className="mb-panel"><SectionTitle title="版本、发布与审计证据" subtitle="已发布版本不可变；恢复或修改均生成新草稿。"/><div className="mb-list-row"><span><b>{connection.version}</b><small>{connection.lifecycle} · 当前连接版本</small></span><button onClick={()=>notify('已生成当前版本与上一发布版本的字段差异视图。')}>查看差异</button></div>{connection.audit.map(event=><div className="mb-audit-row" key={event.id}><time>{event.at}</time><b>{event.action}</b><span>{event.actor}</span><p>{event.result}</p></div>)}</div>}
    {notice&&<Toast text={notice} close={()=>notify('')}/>} 
  </section>
}

function MoreLifecycle({role,connection,notify}:{role:RoleId;connection:ModelConnection;notify:(v:string)=>void}){const registry=useModelBillingRegistry();if(!canEdit(role))return null;return <select className="mb-action-select" value="" onChange={e=>{const action=e.target.value;if(action==='停用')notify(registry.transitionConnection(role,connection.id,'已停用').message);if(action==='恢复')notify(registry.transitionConnection(role,connection.id,'已发布').message);if(action==='归档')notify(registry.transitionConnection(role,connection.id,'已归档').message);if(action==='删除')notify(registry.deleteConnection(role,connection.id).message);e.target.value=''}}><option value="">更多操作</option>{connection.lifecycle==='已发布'&&<option>停用</option>}{connection.lifecycle==='已停用'&&<option>恢复</option>}{canGovern(role)&&<option>归档</option>}{connection.lifecycle==='草稿'&&<option>删除</option>}</select>}

function ConnectionWizard({role,close,save}:{role:RoleId;close:()=>void;save:(v:ModelConnection)=>void}){
  const [step,setStep]=useState(1);const [tested,setTested]=useState(false);const [error,setError]=useState('');
  const [draft,setDraft]=useState({name:'',provider:'OpenAI' as ModelProviderType,baseUrl:'',region:'中国大陆',secretRef:'',modelId:'',modelName:'',timeout:60,rateLimit:300});
  const validate=()=>{if(!draft.name.trim())return '请填写连接名称。';if(!draft.baseUrl.startsWith('http'))return 'Base URL 必须以 http:// 或 https:// 开头。';if(!draft.modelId.trim())return '请登记至少一个模型 ID。';if(!draft.secretRef.startsWith('SECRET-'))return '请输入有效的 Secret ID 引用。';return ''};
  const next=()=>{if(step===1&&!draft.name.trim()){setError('请填写连接名称。');return}if(step===2&&!draft.baseUrl.startsWith('http')){setError('请输入合法 Base URL。');return}if(step===3&&!draft.modelId.trim()){setError('请登记至少一个模型。');return}if(step===4&&!draft.secretRef.startsWith('SECRET-')){setError('Secret ID 必须以 SECRET- 开头。');return}setError('');setStep(Math.min(6,step+1))};
  const submit=()=>{const invalid=validate();if(invalid){setError(invalid);return}if(!tested){setError('请先完成连通测试。');return}const id=`CONN-${draft.provider.replace(/\s/g,'-').toUpperCase()}-${Date.now().toString().slice(-5)}`;save({id,name:draft.name,provider:draft.provider,region:draft.region,baseUrl:draft.baseUrl,secretRef:draft.secretRef,owner:actor[role],departmentId:'ORG-CAPABILITY',risk:draft.provider==='私有化'?'高':'中',health:'正常',lifecycle:'草稿',version:'v0.1-draft',p95:720,todayCalls:0,timeout:draft.timeout,rateLimit:draft.rateLimit,routePolicy:'仅测试环境，发布后配置生产路由',models:[{id:`MV-${Date.now().toString().slice(-5)}`,modelId:draft.modelId,displayName:draft.modelName||draft.modelId,contextWindow:128000,modalities:['文本'],health:'正常',lifecycle:'草稿',inputPrice:0,outputPrice:0,currency:'CNY'}],dependencies:[],audit:[{id:`MAUD-${Date.now()}`,action:'创建草稿',actor:actor[role],at:'刚刚',result:'向导校验和连通测试通过'}]})};
  return <div className="mb-modal-backdrop"><section className="mb-modal"><header><div><h2>新建大模型连接</h2><p>第 {step}/6 步 · {['供应商与基本信息','连接配置','模型登记','认证与环境','路由与保护','连通测试'][step-1]}</p></div><button onClick={close}><X/></button></header><div className="mb-stepper">{[1,2,3,4,5,6].map(v=><i key={v} className={v<=step?'active':''}>{v}</i>)}</div><div className="mb-form-grid">{step===1&&<><Field label="连接名称 *"><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="供应商 *"><select value={draft.provider} onChange={e=>setDraft({...draft,provider:e.target.value as ModelProviderType})}>{providers.map(v=><option key={v}>{v}</option>)}</select></Field></>}{step===2&&<><Field label="Base URL *"><input value={draft.baseUrl} onChange={e=>setDraft({...draft,baseUrl:e.target.value})} placeholder="https://.../v1"/></Field><Field label="区域"><input value={draft.region} onChange={e=>setDraft({...draft,region:e.target.value})}/></Field></>}{step===3&&<><Field label="模型 ID *"><input value={draft.modelId} onChange={e=>setDraft({...draft,modelId:e.target.value})}/></Field><Field label="展示名称"><input value={draft.modelName} onChange={e=>setDraft({...draft,modelName:e.target.value})}/></Field></>}{step===4&&<><Field label="Secret ID *"><input value={draft.secretRef} onChange={e=>setDraft({...draft,secretRef:e.target.value})} placeholder="SECRET-MODEL-..."/><small>不输入真实密钥。</small></Field><Field label="环境"><select><option>测试环境</option><option>生产环境（需超级管理员发布）</option></select></Field></>}{step===5&&<><Field label="超时（秒）"><input type="number" value={draft.timeout} onChange={e=>setDraft({...draft,timeout:Number(e.target.value)})}/></Field><Field label="每分钟限流"><input type="number" value={draft.rateLimit} onChange={e=>setDraft({...draft,rateLimit:Number(e.target.value)})}/></Field></>}{step===6&&<div className="mb-test-card"><b>发布前连通测试</b><p>检查 URL、Secret 引用、模型可发现性、结构化输出和限流响应。</p><button className="primary" onClick={()=>{const invalid=validate();setError(invalid);if(!invalid)setTested(true)}}>运行测试</button>{tested&&<Badge value="测试通过"/>}</div>}</div>{error&&<p className="mb-error">{error}</p>}<footer><button onClick={step===1?close:()=>setStep(step-1)}>{step===1?'取消':'上一步'}</button>{step<6?<button className="primary" onClick={next}>下一步</button>:<button className="primary" onClick={submit}>保存草稿</button>}</footer></section></div>
}

function Badge({value}:{value:string}){return <span className={`mb-badge tone-${['正常','已发布','通过','测试通过'].includes(value)?'success':['波动','待审核','测试中'].includes(value)?'warning':['故障','失败'].includes(value)?'danger':'neutral'}`}>{value}</span>}
function SectionTitle({title,subtitle}:{title:string;subtitle:string}){return <header className="mb-section-title"><div><h3>{title}</h3><p>{subtitle}</p></div></header>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mb-field"><span>{label}</span>{children}</label>}
function Toast({text,close}:{text:string;close:()=>void}){return <div className="mb-toast"><span>{text}</span><button onClick={close}>关闭</button></div>}
