import React, { useMemo, useState } from 'react';
import { ArrowLeft, Bot, CheckCircle2, Edit3, Plus, Search, ShieldCheck, X } from 'lucide-react';
import { ModuleHeader as SharedModuleHeader } from '../../components/ModuleHeader';
import type { RoleId } from '../../types';
import { agentRecords, knowledgeCatalog, promptOptions, skillOptions, toolOptions, type AgentRecord, type AgentStatus } from './m03-data';
import './m03.css';

type DetailTab = 'prompt' | 'knowledge' | 'capability' | 'position' | 'automation';
type Dialog = 'agent' | 'prompt' | 'knowledge' | 'skill' | 'tool' | 'automation' | null;
const canManage = (role: RoleId) => ['trainer', 'admin', 'superadmin'].includes(role);
const canPublish = (role: RoleId) => ['admin', 'superadmin'].includes(role);
const canRead = (agent: AgentRecord, role: RoleId) => !['employee', 'business'].includes(role) || agent.id === 'AGENT-LEAD-03';
const statusList: AgentStatus[] = ['草稿', '测试中', '已发布', '运行中', '已挂起', '已归档'];

export function M03AgentManagementPage({ role }: { role: RoleId }) {
  const [rows, setRows] = useState(agentRecords);
  const [query, setQuery] = useState('');
  const [level, setLevel] = useState('全部层级');
  const [status, setStatus] = useState('全部状态');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [tab, setTab] = useState<DetailTab>('prompt');
  const [dialog, setDialog] = useState<Dialog>(null);
  const [notice, setNotice] = useState('');
  const selected = rows.find(item => item.id === selectedId);
  const visibleRows = useMemo(() => rows.filter(item => canRead(item, role) && item.name.toLowerCase().includes(query.toLowerCase()) && (level === '全部层级' || item.level === level) && (status === '全部状态' || item.status === status)), [rows, query, level, status, role]);
  const update = (next: AgentRecord, message: string) => { setRows(items => items.map(item => item.id === next.id ? { ...next, audit: [`刚刚 当前用户：${message}`, ...next.audit] } : item)); setNotice(message); };

  if (role === 'client') return <section className="m03-gate"><ShieldCheck /><h1>M03 Agent 管理受限</h1><p>客户管理员不访问内部 Agent 管控对象，请前往客户看板查看已授权服务。</p></section>;
  if (!selected) return <Registry rows={visibleRows} query={query} setQuery={setQuery} level={level} setLevel={setLevel} status={status} setStatus={setStatus} role={role} open={id => { setSelectedId(id); setTab('prompt'); }} create={() => setDialog('agent')} />;
  return <AgentWorkbench agent={selected} role={role} tab={tab} setTab={setTab} back={() => setSelectedId(null)} dialog={dialog} closeDialog={() => setDialog(null)} open={setDialog} update={update} notice={notice} closeNotice={() => setNotice('')} />;

  function Registry(props: { rows: AgentRecord[]; query: string; setQuery: (v: string) => void; level: string; setLevel: (v: string) => void; status: string; setStatus: (v: string) => void; role: RoleId; open: (id: string) => void; create: () => void }) {
    return <section className="m03"><ModuleHeader /><main className="m03-content"><section className="m03-panel"><header className="m03-panel-head"><div><h1>Agent 注册中心</h1><p>统一登记可运行 Agent，管理其版本、能力依赖和生命周期。</p></div><div className="m03-toolbar"><label className="m03-search"><Search size={16} /><input value={props.query} onChange={e => props.setQuery(e.target.value)} placeholder="搜索 Agent 名称或 ID" /></label><select value={props.level} onChange={e => props.setLevel(e.target.value)}><option>全部层级</option><option>策略层</option><option>执行层</option></select><select value={props.status} onChange={e => props.setStatus(e.target.value)}><option>全部状态</option>{statusList.map(item => <option key={item}>{item}</option>)}</select>{canManage(props.role) && <button className="m03-primary" onClick={props.create}><Plus size={16} />新建 Agent</button>}</div></header><div className="m03-table"><div className="m03-row m03-head"><span>Agent 名称</span><span>版本</span><span>所属层级</span><span>创建者</span><span>准确率</span><span>7日调用量</span><span>状态</span><span>操作</span></div>{props.rows.map(item => <div className="m03-row" key={item.id}><button className="m03-name" onClick={() => props.open(item.id)}><strong>{item.name}</strong><small>{item.description}</small></button><span>{item.version}</span><span><i className="m03-level">{item.level}</i></span><span>{item.creator}</span><span>{item.accuracy}%</span><span>{item.calls.toLocaleString()}</span><span><i className={`m03-status is-${item.status}`}>{item.status}</i></span><button className="m03-link" onClick={() => props.open(item.id)}>{item.status === '测试中' ? '排查' : '详情'} →</button></div>)}</div></section></main>{dialog === 'agent' && <AgentForm close={() => setDialog(null)} save={agent => { setRows(items => [{ ...agent, audit: ['刚刚 当前用户：新建 Agent 草稿'] }, ...items]); setSelectedId(agent.id); setTab('prompt'); setDialog(null); setNotice('新建 Agent 草稿成功，请继续绑定能力并提交测试。'); }} />}{notice && <Notice text={notice} close={() => setNotice('')} />}</section>;
  }
}

function ModuleHeader() { return <SharedModuleHeader title="M03 Agent 管理" subtitle="注册、配置、运行与治理 Agent 全生命周期" />; }

function AgentWorkbench({ agent, role, tab, setTab, back, dialog, closeDialog, open, update, notice, closeNotice }: { agent: AgentRecord; role: RoleId; tab: DetailTab; setTab: (v: DetailTab) => void; back: () => void; dialog: Dialog; closeDialog: () => void; open: (v: Dialog) => void; update: (v: AgentRecord, msg: string) => void; notice: string; closeNotice: () => void }) {
  const editable = canManage(role);
  const tabs: { id: DetailTab; label: string; icon: string }[] = [{ id: 'prompt', label: 'Prompt配置', icon: '📝' }, { id: 'knowledge', label: '知识库', icon: '📚' }, { id: 'capability', label: '技能与工具', icon: '⚡' }, { id: 'position', label: '适用岗位', icon: '👥' }, { id: 'automation', label: '自动化任务', icon: '⏰' }];
  return <section className="m03"><ModuleHeader /><main className="m03-workbench"><header className="m03-workbench-head"><button className="m03-back" onClick={back}><ArrowLeft size={16} />返回注册中心</button><div><h1><Bot size={20} />{agent.name}</h1><p>{agent.id} · {agent.version} · {agent.status}</p></div>{editable && <button onClick={() => open('agent')}><Edit3 size={15} />编辑 Agent</button>}</header><section className="m03-agent-card"><p className="m03-kicker">核心指标</p><div className="m03-metrics"><Metric value={`${agent.accuracy}%`} label="准确率" accent /><Metric value={agent.calls.toLocaleString()} label="7日调用量" /><Metric value={agent.latency} label="P99延迟" /></div><dl className="m03-facts"><div><dt>Agent名称</dt><dd>{agent.name}</dd></div><div><dt>版本</dt><dd>{agent.version}</dd></div><div><dt>所属层级</dt><dd><i className="m03-level">{agent.level}</i></dd></div><div><dt>创建部门</dt><dd>{agent.creator}团队</dd></div><div><dt>状态</dt><dd><i className={`m03-status is-${agent.status}`}>{agent.status}</i></dd></div></dl><nav className="m03-tabs">{tabs.map(item => <button key={item.id} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)}><span>{item.icon}</span>{item.label}</button>)}</nav><section className="m03-tab-content">{tab === 'prompt' && <PromptTab agent={agent} editable={editable} open={open} update={update} />}{tab === 'knowledge' && <KnowledgeTab agent={agent} editable={editable} open={open} update={update} />}{tab === 'capability' && <CapabilityTab agent={agent} editable={editable} open={open} update={update} />}{tab === 'position' && <PositionTab agent={agent} editable={editable} update={update} />}{tab === 'automation' && <AutomationTab agent={agent} editable={editable} open={open} update={update} />}</section></section></main><DetailDialogs active={dialog} agent={agent} close={closeDialog} update={update} />{notice && <Notice text={notice} close={closeNotice} />}</section>;
}

function Metric({ value, label, accent = false }: { value: string; label: string; accent?: boolean }) { return <div className="m03-metric"><strong className={accent ? 'accent' : ''}>{value}</strong><span>{label}</span></div>; }
function PromptTab({ agent, editable, open, update }: { agent: AgentRecord; editable: boolean; open: (v: Dialog) => void; update: (v: AgentRecord, msg: string) => void }) { return <><p className="m03-section-note">当前绑定 Prompt 模板 · 支持多版本管理</p><div className="m03-binding-list">{agent.prompts.map(item => <article className={`m03-binding prompt-${item.state}`} key={item.id}><div><strong>📝 {item.name} {item.version}</strong><small>{item.note}</small></div><i>{item.state}</i>{editable && item.state !== '生产' && <button onClick={() => update({ ...agent, prompts: agent.prompts.map(value => value.id === item.id ? { ...value, state: '归档' } : value.state === '生产' ? { ...value, state: '预发布' } : { ...value, state: '生产' }) }, `已将 ${item.version} 切换为生产版本`)}>设为生产</button>}</article>)}</div>{editable && <button className="m03-outline" onClick={() => open('prompt')}><Plus size={15} />绑定新 Prompt 模板</button>}</>; }
function KnowledgeTab({ agent, editable, open, update }: { agent: AgentRecord; editable: boolean; open: (v: Dialog) => void; update: (v: AgentRecord, msg: string) => void }) { return <><p className="m03-section-note">已绑定知识库文档 · Agent 可检索范围</p><div className="m03-binding-list">{agent.knowledge.map(item => <article className="m03-binding" key={item.id}><div><strong>📚 {item.name}（{item.count.toLocaleString()}篇）</strong><small>{item.id} · M06 已发布知识资产</small></div><i className={item.bound ? 'yes' : 'muted'}>{item.bound ? '已绑定' : '未绑定'}</i>{editable && item.bound && <button onClick={() => update({ ...agent, knowledge: agent.knowledge.map(value => value.id === item.id ? { ...value, bound: false } : value) }, `已解绑 ${item.name}`)}>解绑</button>}</article>)}</div><dl className="m03-rag"><dt>检索配置</dt><div><span>最大检索片段数</span><b>{agent.rag.topK}</b></div><div><span>相似度阈值</span><b>{agent.rag.threshold}</b></div><div><span>检索权重</span><b>{agent.rag.weight}</b></div></dl>{editable && <button className="m03-outline" onClick={() => open('knowledge')}><Plus size={15} />绑定知识库</button>}</>; }
function CapabilityTab({ agent, editable, open, update }: { agent: AgentRecord; editable: boolean; open: (v: Dialog) => void; update: (v: AgentRecord, msg: string) => void }) { const remove = (type: 'skills' | 'tools', value: string) => update({ ...agent, [type]: agent[type].filter(item => item !== value) }, `已移除${type === 'skills' ? ' Skill' : ' Tool'}：${value}`); return <><p className="m03-section-note">已绑定技能（Skill）和工具（Tool）</p><h3>⚡ Skills</h3><div className="m03-chips">{agent.skills.map(item => <span key={item}>{item}{editable && <button onClick={() => remove('skills', item)}>×</button>}</span>)}{editable && <button className="add" onClick={() => open('skill')}>＋ 添加Skill</button>}</div><h3>🔧 Tools</h3><div className="m03-chips">{agent.tools.map(item => <span key={item}>{item}{editable && <button onClick={() => remove('tools', item)}>×</button>}</span>)}{editable && <button className="add" onClick={() => open('tool')}>＋ 添加Tool</button>}</div></>; }
function PositionTab({ agent, editable, update }: { agent: AgentRecord; editable: boolean; update: (v: AgentRecord, msg: string) => void }) { return <><p className="m03-section-note">该 Agent 适用的岗位及权限范围</p><div className="m03-binding-list">{agent.positions.map(item => <article className="m03-binding" key={item.name}><div><strong>👤 {item.name}</strong><small>{item.scope}</small></div><i className={item.state === '未开放' ? 'muted' : item.state === '可选启用' ? 'warn' : 'yes'}>{item.state}</i>{editable && item.state !== '未开放' && <button onClick={() => update({ ...agent, positions: agent.positions.map(value => value.name === item.name ? { ...value, state: value.state === '默认启用' ? '可选启用' : '默认启用' } : value) }, `${item.name} 已${item.state === '默认启用' ? '改为可选启用' : '设为默认启用'}`)}>{item.state === '默认启用' ? '设为可选' : '设为默认'}</button>}</article>)}</div></>; }
function AutomationTab({ agent, editable, open, update }: { agent: AgentRecord; editable: boolean; open: (v: Dialog) => void; update: (v: AgentRecord, msg: string) => void }) { return <><p className="m03-section-note">自动化任务配置 · Agent 定时或事件触发执行</p><div className="m03-binding-list">{agent.automations.map(item => <article className="m03-binding" key={item.id}><div><strong>⏱ {item.name}</strong><small>触发：{item.schedule} · {item.detail}</small></div><i className={item.running ? 'yes' : 'muted'}>{item.running ? '运行中' : '已暂停'}</i>{editable && <button onClick={() => update({ ...agent, automations: agent.automations.map(value => value.id === item.id ? { ...value, running: !value.running } : value) }, `${item.name} 已${item.running ? '暂停' : '启动'}`)}>{item.running ? '暂停' : '启动'}</button>}</article>)}</div>{editable && <button className="m03-outline" onClick={() => open('automation')}><Plus size={15} />新建自动化任务</button>}</>; }

function DetailDialogs({ active, agent, close, update }: { active: Dialog; agent: AgentRecord; close: () => void; update: (v: AgentRecord, msg: string) => void }) {
  const [choice, setChoice] = useState('');
  const [title, setTitle] = useState('');
  if (!active) return null;
  if (active === 'agent') return <Modal title="编辑 Agent" close={close}><label>Agent 名称<input value={agent.name} onChange={e => setTitle(e.target.value)} placeholder={agent.name} /></label><label>运行模型<select defaultValue={agent.model}><option>LeadReasoner · v1.8</option><option>QualityGuard · v2.0</option></select></label><button className="m03-primary" onClick={() => { update({ ...agent, name: title.trim() || agent.name }, 'Agent 基础信息已保存，生成待测试修订'); close(); }}>保存修订</button></Modal>;
  if (active === 'prompt') return <Modal title="绑定 Prompt 模板" close={close}><label>选择已发布 Prompt<select value={choice} onChange={e => setChoice(e.target.value)}><option value="">请选择 Prompt</option>{promptOptions.map(item => <option key={item.id} value={item.id}>{item.id} · {item.name} · {item.version}</option>)}</select></label><button className="m03-primary" disabled={!choice} onClick={() => { const item = promptOptions.find(value => value.id === choice)!; update({ ...agent, prompts: [...agent.prompts, { ...item, state: '预发布', note: '新绑定版本 · 等待 A/B 验证' }] }, `已绑定 Prompt：${item.name} ${item.version}（预发布）`); close(); }}>绑定并进入预发布</button></Modal>;
  if (active === 'knowledge') return <Modal title="绑定知识库" close={close}><p className="m03-modal-tip">选择 M06 已发布资产；绑定后按当前检索配置进入 Agent 可检索范围。</p><div className="m03-option-list">{agent.knowledge.filter(item => !item.bound).map(item => <label key={item.id}><input type="radio" name="knowledge" value={item.id} onChange={e => setChoice(e.target.value)} />{item.name}（{item.count}篇）</label>)}</div><button className="m03-primary" disabled={!choice} onClick={() => { const item = agent.knowledge.find(value => value.id === choice)!; update({ ...agent, knowledge: agent.knowledge.map(value => value.id === item.id ? { ...value, bound: true } : value) }, `已绑定知识库：${item.name}`); close(); }}>确认绑定</button></Modal>;
  if (active === 'skill' || active === 'tool') { const options = active === 'skill' ? skillOptions : toolOptions; const current = active === 'skill' ? agent.skills : agent.tools; return <Modal title={`添加${active === 'skill' ? ' Skill' : ' Tool'}`} close={close}><div className="m03-option-list">{options.filter(item => !current.includes(item)).map(item => <label key={item}><input type="radio" name="capability" value={item} onChange={e => setChoice(e.target.value)} />{item}</label>)}</div><button className="m03-primary" disabled={!choice} onClick={() => { update({ ...agent, [active === 'skill' ? 'skills' : 'tools']: [...current, choice] }, `已添加${active === 'skill' ? ' Skill' : ' Tool'}：${choice}`); close(); }}>确认添加</button></Modal>; }
  return <AutomationForm agent={agent} close={close} update={update} />;
}
function AutomationForm({ agent, close, update }: { agent: AgentRecord; close: () => void; update: (v: AgentRecord, msg: string) => void }) { const [name, setName] = useState(''); const [schedule, setSchedule] = useState('每日 09:00'); return <Modal title="新建自动化任务" close={close}><label>任务名称<input value={name} onChange={e => setName(e.target.value)} placeholder="例如：周度效果报告" /></label><label>触发计划<select value={schedule} onChange={e => setSchedule(e.target.value)}><option>每日 09:00</option><option>每周一 08:00</option><option>事件触发</option></select></label><button className="m03-primary" disabled={!name.trim()} onClick={() => { update({ ...agent, automations: [...agent.automations, { id: `AUTO-${Date.now()}`, name, schedule, detail: '创建后等待配置执行动作与通知范围', running: false }] }, `已创建自动化任务：${name}`); close(); }}>创建任务</button></Modal>; }
function AgentForm({ close, save }: { close: () => void; save: (agent: AgentRecord) => void }) { const [name, setName] = useState(''); return <Modal title="新建 Agent" close={close}><label>Agent 名称<input value={name} onChange={e => setName(e.target.value)} placeholder="例如：线索诊断 Agent" /></label><label>所属层级<select><option>执行层</option><option>策略层</option></select></label><p className="m03-modal-tip">创建后进入配置工作台，绑定 Prompt、知识、Skill 与 Tool 后再提交测试。</p><button className="m03-primary" disabled={!name.trim()} onClick={() => save({ ...agentRecords[0], id: `AGENT-NEW-${Date.now()}`, name, version: 'v0.1.0', status: '草稿', calls: 0, accuracy: 0, latency: '暂无', prompts: [], knowledge: knowledgeCatalog.map(item => ({ ...item, bound: false })), skills: [], tools: [], automations: [], audit: [] })}>创建草稿</button></Modal>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="m03-mask"><section className="m03-modal"><header><h2>{title}</h2><button onClick={close}><X /></button></header>{children}</section></div>; }
function Notice({ text, close }: { text: string; close: () => void }) { return <div className="m03-notice">{text}<button onClick={close}>关闭</button></div>; }
