import React from 'react';
import { AlertTriangle, CheckCircle2, Cpu, GitCompare, Play, ShieldCheck } from 'lucide-react';
import { EntityTable, FieldGrid, FilterBar, StatusPill, Timeline } from '../components/ProductComponents';
import type { DeepModuleProps } from './types';

export function AgentWorkspace({ page, moduleEntities, openEntity, onAction, permissionFor }: DeepModuleProps) {
    const agent = moduleEntities.find((item) => item.status === 'active') || moduleEntities[0];
    if (page.id === 'catalog') return <section className="content-panel"><div className="panel-heading"><div><h2>Agent 目录</h2><p>按业务场景、能力、版本、风险和运行健康管理 Agent。</p></div><span>3 个 Agent</span></div><FilterBar count={moduleEntities.length} /><EntityTable entities={moduleEntities} onOpen={openEntity} /></section>;
    if (page.id === 'register') return (
        <section className="content-panel"><div className="panel-heading"><div><h2>注册 Agent</h2><p>完成身份、模型、能力、知识、契约、测试和发布策略配置。</p></div><span>草稿 v0.1</span></div>
            <div className="stepper">{['基本信息', '模型与路由', '能力绑定', '知识授权', '输入输出', '测试门禁', '发布策略'].map((step, index) => <div className={index < 2 ? 'is-current' : ''} key={step}><span>{index + 1}</span><strong>{step}</strong></div>)}</div>
            <div className="form-grid"><label><span>Agent 名称 *</span><input defaultValue="线索诊断 Agent" /></label><label><span>业务场景 *</span><input defaultValue="线索转化 / 诊断" /></label><label><span>主模型 *</span><input defaultValue="Qwen-Max · cn-east" /></label><label><span>降级模型 *</span><input defaultValue="DeepSeek-V3 · cn-north" /></label><label className="span-two"><span>职责边界 *</span><textarea defaultValue="读取授权线索与知识，生成诊断建议；不得自动修改客户等级或直接发起外呼。" /></label></div>
            <div className="form-footer"><span>身份校验通过 · 模型路由待压测</span><button className="primary-button" type="button" disabled={!permissionFor('create').allowed} title={permissionFor('create').reason}>保存并进入能力绑定</button></div>
        </section>
    );
    if (page.id === 'capabilities') return <section className="content-panel"><div className="panel-heading"><h2>能力绑定</h2><span>依赖完整</span></div><div className="capability-grid">{[['Prompt','线索诊断 Prompt v1.8','approved'],['Skill','线索画像与意向评分 v2.1','active'],['Tool','CRM 线索读写 Tool','read-only'],['知识包','新能源销售授权知识包 v3.2','published']].map(([type,name,status]) => <article key={type}><span>{type}</span><strong>{name}</strong><StatusPill status={status} /><button type="button" className="text-button">更换绑定</button></article>)}</div><div className="risk-note"><ShieldCheck />未发现权限冲突；CRM Tool 仅允许读取授权区域线索。</div></section>;
    if (page.id === 'contracts') return <section className="content-panel"><div className="panel-heading"><div><h2>输入输出契约</h2><p>契约变化必须声明兼容策略并触发回归测试。</p></div><span>JSON Schema · v3</span></div><div className="contract-grid"><pre>{`input {\n  lead_id: string *\n  profile: LeadProfile *\n  objective: enum\n  knowledge_scope: string[]\n}`}</pre><pre>{`output {\n  intent_score: number\n  diagnosis: string\n  evidence: Citation[]\n  next_action: enum\n  risk_flags: string[]\n}`}</pre></div><div className="risk-note"><AlertTriangle />`risk_flags` 为 v3 新增字段，对 v2 调用方保持可选兼容。</div></section>;
    if (page.id === 'testing') return <section className="content-panel"><div className="panel-heading"><div><h2>测试与风险门禁</h2><p>功能、回归、对抗、权限和成本测试共同决定是否允许发布。</p></div><StatusPill status="testing" /></div><div className="test-grid">{[['黄金用例','98/100','通过'],['历史 Badcase','46/50','有条件通过'],['提示注入','30/30','通过'],['越权访问','20/20','通过'],['成本阈值','¥0.82/次','通过'],['P95 延迟','4.2秒','通过']].map(([name,result,status]) => <article key={name}><CheckCircle2 /><div><strong>{name}</strong><span>{result}</span></div><StatusPill status={status} /></article>)}</div><button className="primary-button" type="button" disabled={!permissionFor('test').allowed} title={permissionFor('test').reason}><Play />重新运行全量测试</button></section>;
    if (page.id === 'versions') return <section className="content-panel"><div className="panel-heading"><div><h2>版本比较</h2><p>比较能力、Prompt、知识、模型、指标和风险变化。</p></div><GitCompare /></div><div className="version-diff"><div><span>当前生产版本</span><strong>v2.2</strong><p>Prompt v1.7 · 知识包 v3.1</p><p>准确率 91.4% · 成本 ¥0.76</p></div><div><span>候选版本</span><strong>v2.3</strong><p className="added">+ Prompt v1.8 · 知识包 v3.2</p><p className="added">+ 准确率 94.8% · 证据覆盖 97%</p><p className="removed">- P95 延迟增加 0.4秒</p></div></div></section>;
    if (page.id === 'release') return <section className="content-panel"><div className="panel-heading"><div><h2>发布审批</h2><p>测试、权限、风险、回滚和影响范围全部通过后才能发布。</p></div><StatusPill status="review" /></div><div className="gate-list">{['功能测试通过率 ≥ 95%','无高危越权或提示注入风险','模型和Tool供应商健康','回滚版本 v2.2 可用','影子流量 30% · 观察24小时'].map((gate) => <span key={gate}><CheckCircle2 />{gate}</span>)}</div><div className="action-row"><button className="secondary-button" type="button" disabled={!permissionFor('publish').allowed} title={permissionFor('publish').reason}>驳回修改</button><button className="primary-button" type="button" disabled={!permissionFor('publish').allowed} title={permissionFor('publish').reason} onClick={() => onAction(agent, 'approve', '发布审批通过，进入灰度运行')}>批准灰度发布</button></div></section>;
    if (page.id === 'instances') return <section className="content-panel"><div className="panel-heading"><h2>运行实例</h2><span>最近5分钟</span></div><div className="acceptance-grid"><article><Cpu /><span>运行实例</span><strong>12</strong><small>华南区域 4</small></article><article><span>成功率</span><strong>97.6%</strong><small>目标 ≥ 96%</small></article><article><span>P95 延迟</span><strong>4.2s</strong><small>较昨日 +0.3s</small></article><article><span>单次成本</span><strong>¥0.82</strong><small>预算 ¥0.90</small></article></div></section>;
    if (page.id === 'availability') return <section className="content-panel"><div className="panel-heading"><div><h2>启停、降级与回滚</h2><p>高风险控制动作必须说明原因、影响范围和恢复条件。</p></div><StatusPill status={agent.status} /></div><FieldGrid entity={agent} /><div className="action-row"><button className="secondary-button" type="button" onClick={() => onAction(agent, 'degrade', 'P95延迟超过预警阈值，切换降级模型')}>降级运行</button><button className="secondary-button" type="button" onClick={() => onAction(agent, 'offline', '人工下线并转移剩余任务')}>下线</button><button className="primary-button" type="button">回滚到 v2.2</button></div></section>;
    if (page.id === 'audit') return <section className="content-panel"><div className="panel-heading"><h2>Agent 审计</h2><span>发布与控制动作</span></div><Timeline entity={agent} /></section>;
    return <section className="content-panel"><div className="panel-heading"><h2>Agent 详情</h2><StatusPill status={agent.status} /></div><FieldGrid entity={agent} /></section>;
}
