import React from 'react';
import { AlertTriangle, CheckCircle2, FileDiff, Search, ShieldCheck } from 'lucide-react';
import { EntityTable, FieldGrid, FilterBar, StatusPill, Timeline } from '../components/ProductComponents';
import type { DeepModuleProps } from './types';

export function KnowledgeBaseWorkspace({ page, moduleEntities, openEntity, onAction, permissionFor }: DeepModuleProps) {
    const asset = moduleEntities.find((item) => item.status === 'published') || moduleEntities[0];
    const reviewAsset = moduleEntities.find((item) => item.status === 'review') || asset;
    if (page.id === 'spaces') return <section className="content-panel"><div className="panel-heading"><div><h2>知识空间</h2><p>按部门、专题、项目、密级和责任人管理知识边界。</p></div><span>6 个空间</span></div><div className="space-grid">{[['销售专题空间','842项','周敏'],['产品与研发中心','1,126项','李哲'],['客户交付空间','586项','陈琳'],['品牌内容空间','734项','王珂']].map(([name,count,owner]) => <button key={name} type="button"><ShieldCheck /><strong>{name}</strong><span>{count} · 责任人 {owner}</span><small>查看知识、权限和治理状态</small></button>)}</div></section>;
    if (page.id === 'ingestion') return <section className="content-panel"><div className="panel-heading"><div><h2>资产采集</h2><p>支持文件、业务系统、网页和人工录入，采集后进入安全扫描。</p></div><span>今日新增 86</span></div><div className="upload-zone"><strong>拖入文件或选择数据源</strong><p>PDF、DOCX、XLSX、PPTX、Markdown · 单文件≤200MB</p><div><button className="secondary-button" type="button">连接业务系统</button><button className="primary-button" type="button">选择文件</button></div></div><div className="gate-list"><span><CheckCircle2 />病毒与恶意代码扫描</span><span><CheckCircle2 />敏感信息识别</span><span><CheckCircle2 />重复内容检测</span><span><AlertTriangle />责任人与有效期待补充</span></div></section>;
    if (page.id === 'editor') return <section className="content-panel"><div className="panel-heading"><div><h2>知识编辑器</h2><p>正文、元数据、标签、责任人和有效期统一编辑。</p></div><span>草稿自动保存</span></div><div className="editor-layout"><aside><label>标题<input defaultValue="客户合同归档操作规范" /></label><label>空间<input defaultValue="销售专题空间" /></label><label>责任人<input defaultValue="周敏" /></label><label>密级<select><option>内部</option><option>机密</option></select></label><label>有效期<input defaultValue="2027-07-13" /></label></aside><textarea defaultValue={`# 客户合同归档操作规范\n\n## 适用范围\n适用于品牌合作、RaaS交付及续约相关合同。\n\n## 归档规则\n合同生效后2个工作日内完成归档，并关联客户、项目与交付版本。`} /></div><div className="form-footer"><span>附件扫描通过 · 3项元数据完整</span><button className="secondary-button" type="button">保存草稿</button><button className="primary-button" type="button">提交审核</button></div></section>;
    if (page.id === 'processing') return <section className="content-panel"><div className="panel-heading"><div><h2>清洗切分</h2><p>查看解析、去噪、结构识别、切分、向量化和质量检查结果。</p></div><StatusPill status="running" /></div><div className="run-flow">{['文件解析','结构识别','敏感信息处理','语义切分','向量化','质量检查'].map((step,index) => <article className={index < 4 ? 'is-done' : index === 4 ? 'is-running' : ''} key={step}><span>{index < 4 ? <CheckCircle2 /> : index + 1}</span><strong>{step}</strong><small>{index < 4 ? '完成' : index === 4 ? '68%' : '等待'}</small></article>)}</div><div className="acceptance-grid"><article><span>识别页数</span><strong>42</strong></article><article><span>语义块</span><strong>186</strong></article><article><span>平均长度</span><strong>612字</strong></article><article><span>低质量块</span><strong>3</strong></article></div></section>;
    if (page.id === 'review') return <section className="content-panel"><div className="panel-heading"><div><h2>知识审核中心</h2><p>比较版本差异并核对规则、证据、权限和有效期。</p></div><StatusPill status={reviewAsset.status} /></div><div className="review-layout"><aside><strong>审核队列</strong>{['客户合同归档操作规范','差旅补贴新标准','售前方案模板 V2'].map((name,index) => <button className={index === 0 ? 'is-active' : ''} type="button" key={name}><span>{name}</span><small>{index === 0 ? '高优先级 · 2小时' : '普通 · 今日'}</small></button>)}</aside><div><h3>客户合同归档操作规范</h3><p>版本 v0.3 · 内部密级 · 有效期至 2027-07-13</p><div className="diff-block"><p className="added">+ 合同生效后2个工作日内完成归档。</p><p className="added">+ 必须关联客户、交付项目和AI产品版本。</p><p className="removed">- 纸质合同由业务团队自行保管。</p></div><textarea aria-label="审核意见" defaultValue="规则完整，补充客户关闭时的资产导出要求后可发布。" /><div className="action-row"><button className="secondary-button" type="button" disabled={!permissionFor('publish').allowed} title={permissionFor('publish').reason}>驳回</button><button className="secondary-button" type="button" disabled={!permissionFor('publish').allowed} title={permissionFor('publish').reason}>要求补充</button><button className="primary-button" type="button" disabled={!permissionFor('publish').allowed} title={permissionFor('publish').reason} onClick={() => onAction(reviewAsset, 'publish', '知识审核通过并发布')}>通过并发布</button></div></div></div></section>;
    if (page.id === 'publishing') return <section className="content-panel"><div className="panel-heading"><h2>发布管理</h2><span>生产知识</span></div><div className="gate-list"><span><CheckCircle2 />内容审核通过</span><span><CheckCircle2 />密级与授权范围确认</span><span><CheckCircle2 />责任人与有效期完整</span><span><CheckCircle2 />检索质量测试 96.4%</span></div><div className="form-grid"><label><span>发布范围</span><input defaultValue="销售专题空间 / 华南区域" /></label><label><span>生效时间</span><input defaultValue="立即生效" /></label><label><span>授权 Agent</span><input defaultValue="线索诊断 Agent、销售培育 Agent" /></label><label><span>失效策略</span><input defaultValue="到期前30天提醒责任人" /></label></div></section>;
    if (page.id === 'packages') return <section className="content-panel"><div className="panel-heading"><div><h2>知识包</h2><p>将经过审核的知识按场景、Agent、租户和权限组合交付。</p></div><span>14 个已发布</span></div><div className="capability-grid">{[['新能源销售授权知识包','线索诊断 Agent','v3.2'],['品牌内容规范包','内容生产 Agent','v2.7'],['商城活动规则包','商城运营 Agent','v1.9']].map(([name,agent,version]) => <article key={name}><span>{version}</span><strong>{name}</strong><p>{agent}</p><StatusPill status="published" /></article>)}</div></section>;
    if (page.id === 'retrieval') return <section className="content-panel"><div className="panel-heading"><div><h2>检索验证</h2><p>验证查询、召回片段、引用证据、权限过滤和答案可用性。</p></div><Search /></div><div className="search-test"><input defaultValue="RaaS客户合同生效后多久需要完成归档？" /><button className="primary-button" type="button">运行检索</button></div><div className="citation-result"><strong>答案：合同生效后2个工作日内完成归档。</strong><p>来源：客户合同归档操作规范 · 第3章 · 相似度 0.92</p><blockquote>合同生效后2个工作日内完成归档，并关联客户、项目与交付版本。</blockquote><span>权限过滤：通过 · 知识新鲜度：正常</span></div></section>;
    if (page.id === 'citations') return <section className="content-panel"><div className="panel-heading"><h2>引用与反馈</h2><span>最近7天</span></div><div className="test-grid">{[['客户合同归档操作规范','186次引用','正向 94%'],['新能源销售授权知识包','1,428次检索','命中 91%'],['差旅补贴新标准','32次引用','2条纠错']].map(([name,usage,feedback]) => <article key={name}><FileDiff /><div><strong>{name}</strong><span>{usage}</span></div><small>{feedback}</small></article>)}</div></section>;
    if (page.id === 'expiry') return <section className="content-panel"><div className="panel-heading"><div><h2>过期治理</h2><p>到期知识必须续期、替换、下架或归档，不能继续作为确定性证据。</p></div><span>7项待处理</span></div><div className="handoff-card"><AlertTriangle /><div><strong>2026年区域销售政策</strong><p>7天后到期，已被3个Agent和2个知识包引用。</p><small>责任人 周敏 · 影响 428 个进行中任务</small></div><button className="secondary-button" type="button">发起续期</button></div><div className="handoff-card"><AlertTriangle /><div><strong>旧版商城退款规则</strong><p>已到期且存在新版本，建议替换后下架。</p><small>责任人 李哲 · 影响 1 个知识包</small></div><button className="secondary-button" type="button">查看影响</button></div></section>;
    if (page.id === 'audit') return <section className="content-panel"><div className="panel-heading"><h2>知识审计</h2><span>不可编辑</span></div><Timeline entity={asset} /></section>;
    return <section className="content-panel"><div className="panel-heading"><h2>知识详情</h2><StatusPill status={asset.status} /></div><FieldGrid entity={asset} /><button className="primary-button" type="button" onClick={() => openEntity(asset)}>打开统一对象详情</button></section>;
}
