import React, { useMemo, useState } from 'react';
import { Archive, ArrowLeft, CheckCircle2, Copy, Edit3, Eye, PauseCircle, Play, Plus, RotateCcw, Save, Send, ShieldAlert, Trash2, X, XCircle } from 'lucide-react';
import { ModuleHeader } from '../../components/ModuleHeader';
import type { RoleId } from '../../types';
import { useToolRegistry, type ToolLifecycleAction } from './tool-registry-store';
import { isHighRiskTool, type ToolContractParameter, type ToolDependency, type ToolEnvironment, type ToolRecord, type ToolTestRun } from './tools-data';

type Tab = 'basic' | 'contract' | 'environment' | 'debug' | 'dependency' | 'version';
const tabs: { id: Tab; label: string }[] = [{ id: 'basic', label: '基本配置' }, { id: 'contract', label: '接口契约' }, { id: 'environment', label: '认证与环境' }, { id: 'debug', label: '调试与健康' }, { id: 'dependency', label: '依赖与权限' }, { id: 'version', label: '版本与审计' }];
const actorByRole: Record<RoleId, string> = { employee: '陈屿', business: '李沐', trainer: '周芮', admin: '赵岑', superadmin: '顾川', client: '王琳' };

export function ToolWorkbench({ role, tool, onBack, onSelectTool }: { role: RoleId; tool: ToolRecord; onBack: () => void; onSelectTool: (id: string) => void }) {
  const registry = useToolRegistry();
  const [tab, setTab] = useState<Tab>('basic');
  const [notice, setNotice] = useState('');
  const [rejectOpen, setRejectOpen] = useState(false);
  const actor = actorByRole[role];
  const editable = ['trainer', 'admin', 'superadmin'].includes(role) && ['草稿', '测试中'].includes(tool.lifecycle);
  const admin = ['admin', 'superadmin'].includes(role);
  const perform = (action: ToolLifecycleAction, reason?: string) => {
    const result = registry.transition(tool.id, action, actor, role, reason);
    setNotice(result.message);
    if (result.record && result.record.id !== tool.id) onSelectTool(result.record.id);
  };
  const update = (record: ToolRecord, message: string) => { registry.upsert(record, { actor, action: message, evidence: `${record.id} · ${record.currentVersion}` }); setNotice(message); };
  const remove = () => { const result = registry.remove(tool.id); setNotice(result.message); if (result.ok) onBack(); };
  return <section className="tools-page tools-workbench">
    <ModuleHeader title="Tools 工具集" subtitle="注册、测试、发布并治理 Agent 与工作流调用的外部能力" />
    <main className="tools-content">
      <header className="tools-workbench-head"><button className="tools-back" onClick={onBack}><ArrowLeft size={15} />返回 Tool 目录</button><div><h2>{tool.name}</h2><p>{tool.id} · {tool.type} · {tool.currentVersion}</p></div><div className="tools-workbench-actions">{lifecycleActions(tool, role).map(action => <button key={action.id} className={action.primary ? 'tools-primary' : action.danger ? 'danger' : ''} onClick={() => action.id === 'reject' ? setRejectOpen(true) : action.id === 'delete' ? remove() : perform(action.id as ToolLifecycleAction)}>{action.icon}{action.label}</button>)}</div></header>
      <section className="tools-overview"><div className="tools-overview-main"><span className="tools-type">{tool.type}</span><h1>{tool.name}</h1><p>{tool.description}</p><div><i className={`tools-life is-${tool.lifecycle}`}>{tool.lifecycle}</i><i className={`tools-health is-${tool.health}`}>● {tool.health}</i>{isHighRiskTool(tool) && <i className="tools-risk"><ShieldAlert size={13} />高风险发布门禁</i>}</div></div><div className="tools-metrics"><Metric label="成功率" value={`${tool.successRate}%`} /><Metric label="P95 延迟" value={tool.p95Latency} /><Metric label="今日调用" value={tool.dailyCalls.toLocaleString()} /><Metric label="生产依赖" value={`${tool.dependencies.filter(dep => ['Agent', '工作流', 'Skill', '运行实例'].includes(dep.type)).length}`} /></div></section>
      <nav className="tools-tabs">{tabs.map(item => <button key={item.id} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>
      <section className="tools-tab-panel">{tab === 'basic' && <BasicTab tool={tool} editable={editable} update={update} />}{tab === 'contract' && <ContractTab tool={tool} editable={editable} update={update} />}{tab === 'environment' && <EnvironmentTab tool={tool} editable={editable || admin} update={update} />}{tab === 'debug' && <DebugTab tool={tool} role={role} update={update} />}{tab === 'dependency' && <DependencyTab tool={tool} role={role} notice={setNotice} />}{tab === 'version' && <VersionTab tool={tool} role={role} copy={() => perform(tool.lifecycle === '已归档' ? 'restore-draft' : 'copy-draft')} />}</section>
    </main>
    {rejectOpen && <ReasonDialog title="驳回 Tool 审核" onClose={() => setRejectOpen(false)} onConfirm={reason => { setRejectOpen(false); perform('reject', reason); }} />}
    {notice && <div className="tools-notice">{notice}<button onClick={() => setNotice('')}>关闭</button></div>}
  </section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }

function BasicTab({ tool, editable, update }: { tool: ToolRecord; editable: boolean; update: (record: ToolRecord, message: string) => void }) {
  const [draft, setDraft] = useState(tool);
  const set = <K extends keyof ToolRecord>(key: K, value: ToolRecord[K]) => setDraft(current => ({ ...current, [key]: value }));
  return <div className="tools-two-column"><section className="tools-panel"><header><div><h3>基本信息</h3><p>定义工具用途、归属和风险边界。</p></div>{editable && <button className="tools-primary" onClick={() => update(draft, '已保存 Tool 基本配置')}><Save size={14} />保存</button>}</header><div className="tools-form-grid"><label>Tool 名称<input disabled={!editable} value={draft.name} onChange={event => set('name', event.target.value)} /></label><label>类型<select disabled={!editable} value={draft.type} onChange={event => set('type', event.target.value as ToolRecord['type'])}>{['HTTP API', 'MCP Server', '数据库', '消息通道', '文件系统', '代码执行'].map(item => <option key={item}>{item}</option>)}</select></label><label>负责人<input disabled={!editable} value={draft.owner} onChange={event => set('owner', event.target.value)} /></label><label>所属部门<input disabled={!editable} value={draft.department} onChange={event => set('department', event.target.value)} /></label><label>风险等级<select disabled={!editable} value={draft.risk} onChange={event => set('risk', event.target.value as ToolRecord['risk'])}><option>低</option><option>中</option><option>高</option></select></label><label className="span-2">能力说明<textarea disabled={!editable} value={draft.description} onChange={event => set('description', event.target.value)} /></label><label className="span-2">允许用途与边界<textarea disabled={!editable} value={draft.purpose} onChange={event => set('purpose', event.target.value)} /></label></div></section><section className="tools-panel"><header><div><h3>连接摘要</h3><p>详细凭据在「认证与环境」维护。</p></div></header><dl className="tools-detail-list">{Object.entries(tool.connection).map(([key, value]) => <div key={key}><dt>{connectionLabel(key)}</dt><dd>{value || '未配置'}</dd></div>)}<div><dt>超时 / 重试</dt><dd>{tool.timeoutMs}ms / {tool.retries} 次</dd></div><div><dt>QPS / 熔断</dt><dd>{tool.qpsLimit} / {tool.circuitBreaker}</dd></div></dl></section></div>;
}

function ContractTab({ tool, editable, update }: { tool: ToolRecord; editable: boolean; update: (record: ToolRecord, message: string) => void }) {
  const [parameters, setParameters] = useState(tool.contract.parameters);
  const [request, setRequest] = useState(tool.contract.requestSchema);
  const [response, setResponse] = useState(tool.contract.responseSchema);
  const [error, setError] = useState('');
  const save = () => { try { JSON.parse(request); JSON.parse(response); } catch { return setError('Schema 必须是合法 JSON，当前更改未保存。'); } setError(''); update({ ...tool, contract: { ...tool.contract, parameters, requestSchema: request, responseSchema: response } }, '已保存接口契约和 Schema'); };
  const addParameter = () => setParameters(items => [...items, { id: `PARAM-${Date.now()}`, name: 'new_parameter', type: 'string', required: false, example: '', description: '待补充参数说明' }]);
  const patch = (id: string, next: Partial<ToolContractParameter>) => setParameters(items => items.map(item => item.id === id ? { ...item, ...next } : item));
  return <section className="tools-panel"><header><div><h3>接口契约</h3><p>{tool.contract.method} {tool.contract.path} · {tool.contract.operation} · 已发布版本不可直接修改。</p></div>{editable && <div><button onClick={addParameter}><Plus size={14} />新增参数</button><button className="tools-primary" onClick={save}><Save size={14} />保存契约</button></div>}</header><div className="tools-contract-table"><div><span>参数名</span><span>类型</span><span>必填</span><span>示例值</span><span>说明</span><span>操作</span></div>{parameters.map(item => <div key={item.id}><input disabled={!editable} value={item.name} onChange={event => patch(item.id, { name: event.target.value })} /><select disabled={!editable} value={item.type} onChange={event => patch(item.id, { type: event.target.value as ToolContractParameter['type'] })}>{['string', 'number', 'boolean', 'object', 'array'].map(type => <option key={type}>{type}</option>)}</select><input type="checkbox" disabled={!editable} checked={item.required} onChange={event => patch(item.id, { required: event.target.checked })} /><input disabled={!editable} value={item.example} onChange={event => patch(item.id, { example: event.target.value })} /><input disabled={!editable} value={item.description} onChange={event => patch(item.id, { description: event.target.value })} />{editable ? <button className="danger" onClick={() => setParameters(items => items.filter(value => value.id !== item.id))}><Trash2 size={13} /></button> : <span>—</span>}</div>)}</div><div className="tools-schema-grid"><label>请求 Schema (JSON)<textarea disabled={!editable} value={request} onChange={event => setRequest(event.target.value)} /></label><label>响应 Schema (JSON)<textarea disabled={!editable} value={response} onChange={event => setResponse(event.target.value)} /></label></div><dl className="tools-detail-list"><div><dt>幂等性</dt><dd>{tool.contract.idempotency}</dd></div><div><dt>错误码</dt><dd>{tool.contract.errorCodes}</dd></div></dl>{error && <p className="tools-error">{error}</p>}</section>;
}

function EnvironmentTab({ tool, editable, update }: { tool: ToolRecord; editable: boolean; update: (record: ToolRecord, message: string) => void }) {
  const [environments, setEnvironments] = useState(tool.environments);
  const patch = (name: ToolEnvironment['name'], next: Partial<ToolEnvironment>) => setEnvironments(items => items.map(item => item.name === name ? { ...item, ...next } : item));
  return <section className="tools-panel"><header><div><h3>认证与环境</h3><p>凭据仅保存 Secret 引用 ID，不展示或存储明文。</p></div>{editable && <button className="tools-primary" onClick={() => update({ ...tool, environments }, '已更新认证引用与环境范围')}><Save size={14} />保存环境</button>}</header><div className="tools-environment-cards">{environments.map(item => <article key={item.name}><header><strong>{item.name}环境</strong><i className={item.enabled ? 'enabled' : ''}>{item.enabled ? '已启用' : '未启用'}</i></header><label>Endpoint<input disabled={!editable} value={item.endpoint} onChange={event => patch(item.name, { endpoint: event.target.value })} /></label><label>Secret 引用 ID<input disabled={!editable} value={item.secretRef} onChange={event => patch(item.name, { secretRef: event.target.value })} placeholder="SECRET-ENV-TOOL-01" /></label><label>网络范围<input disabled={!editable} value={item.networkScope} onChange={event => patch(item.name, { networkScope: event.target.value })} /></label>{editable && <label className="tools-switch"><input type="checkbox" checked={item.enabled} onChange={event => patch(item.name, { enabled: event.target.checked })} />允许该环境调用</label>}</article>)}</div><div className="tools-security-note"><ShieldAlert size={16} /><span><strong>安全约束</strong><p>生产 Secret 变更、数据库写入和代码执行权限均写入审计；当前原型不包含真实密钥。</p></span></div></section>;
}

function DebugTab({ tool, role, update }: { tool: ToolRecord; role: RoleId; update: (record: ToolRecord, message: string) => void }) {
  const registry = useToolRegistry();
  const [environment, setEnvironment] = useState<ToolTestRun['environment']>('测试');
  const [payload, setPayload] = useState('{\n  "tenant_id": "TENANT-AIMP",\n  "payload": { "sample": true }\n}');
  const [error, setError] = useState('');
  const [selectedLog, setSelectedLog] = useState(tool.calls[0]?.id || '');
  const writable = ['trainer', 'admin', 'superadmin'].includes(role);
  const run = (mode: 'success' | 'timeout' | 'rate') => { try { JSON.parse(payload); } catch { return setError('请求参数不是合法 JSON，无法运行测试。'); } if (!payload.trim()) return setError('请求参数不能为空。'); const now = Date.now(); const result: ToolTestRun['result'] = mode === 'timeout' ? '失败' : mode === 'rate' ? '限流' : '通过'; const run: ToolTestRun = { id: `TOOL-TEST-${now}`, time: '刚刚', environment, result, latency: mode === 'timeout' ? `${tool.timeoutMs}ms` : mode === 'rate' ? '8ms' : '94ms', retries: mode === 'timeout' ? tool.retries : 0, request: payload, response: result === '通过' ? '{"success":true,"trace_id":"TRACE-TOOL-NEW"}' : '{}', error: result === '通过' ? undefined : mode === 'rate' ? `超过 ${tool.qpsLimit} QPS 限流` : '上游连接超时，已执行重试与熔断判断' }; const resultMessage = registry.addTestRun(tool.id, run, actorByRole[role]); setError(resultMessage.message); };
  const selected = tool.calls.find(item => item.id === selectedLog);
  return <div className="tools-debug-layout"><section className="tools-panel"><header><div><h3>模拟调用</h3><p>验证连接、认证、请求 Schema、限流与熔断行为。</p></div></header><div className="tools-debug-controls"><label>环境<select value={environment} onChange={event => setEnvironment(event.target.value as ToolTestRun['environment'])}><option>开发</option><option>测试</option><option disabled>生产</option></select></label><label>请求参数 (JSON)<textarea value={payload} disabled={!writable} onChange={event => setPayload(event.target.value)} /></label>{writable && <div><button className="tools-primary" onClick={() => run('success')}><Play size={14} />运行测试</button><button onClick={() => run('timeout')}>模拟超时</button><button onClick={() => run('rate')}>模拟限流</button></div>}{error && <p className={error.includes('通过') ? 'tools-success' : 'tools-error'}>{error}</p>}</div></section><section className="tools-panel"><header><div><h3>健康与治理</h3><p>健康状态按该 Tool 的 SLO 独立判定。</p></div></header><div className="tools-health-grid"><Metric label="成功率" value={`${tool.successRate}%`} /><Metric label="P95" value={tool.p95Latency} /><Metric label="QPS 限流" value={`${tool.qpsLimit}`} /><Metric label="超时 / 重试" value={`${tool.timeoutMs}ms / ${tool.retries}`} /></div><dl className="tools-detail-list"><div><dt>熔断策略</dt><dd>{tool.circuitBreaker}</dd></div><div><dt>最近测试</dt><dd>{tool.tests[0] ? `${tool.tests[0].time} · ${tool.tests[0].result} · ${tool.tests[0].latency}` : '尚未运行'}</dd></div></dl></section><section className="tools-panel span-2"><header><div><h3>调用日志与异常详情</h3><p>点击日志查看 Trace、调用方、结果与治理证据。</p></div></header><div className="tools-log-layout"><div className="tools-log-list">{tool.calls.map(item => <button className={selectedLog === item.id ? 'active' : ''} key={item.id} onClick={() => setSelectedLog(item.id)}><span>{item.time}</span><b>{item.caller}</b><i className={`is-${item.result}`}>{item.result}</i><small>{item.latency}</small></button>)}{!tool.calls.length && <p>暂无生产调用日志。</p>}</div>{selected && <dl className="tools-detail-list"><div><dt>Trace ID</dt><dd>{selected.traceId}</dd></div><div><dt>调用方</dt><dd>{selected.caller}</dd></div><div><dt>结果 / 延迟</dt><dd>{selected.result} / {selected.latency}</dd></div><div><dt>处置建议</dt><dd>{selected.result === '成功' ? '无需处理' : '检查限流、熔断与上游依赖，必要时创建 M12 异常工单'}</dd></div></dl>}</div></section></div>;
}

function DependencyTab({ tool, role, notice }: { tool: ToolRecord; role: RoleId; notice: (message: string) => void }) {
  const registry = useToolRegistry();
  const editable = ['trainer', 'admin', 'superadmin'].includes(role) && tool.lifecycle !== '已归档';
  const [kind, setKind] = useState<ToolDependency['type']>('Agent');
  const [target, setTarget] = useState('线索诊断 Agent');
  const add = () => { const id = `${kind.toUpperCase()}-${Date.now().toString().slice(-5)}`; registry.addDependency(tool.id, { id, type: kind, name: target, scope: kind === '角色' || kind === '部门' ? '授权调用' : '生产依赖' }); notice(`已新增 ${kind} 依赖：${target}`); };
  return <section className="tools-panel"><header><div><h3>依赖与权限</h3><p>停用、归档或版本变更前必须评估这些生产消费者。</p></div>{editable && <div className="tools-inline-create"><select value={kind} onChange={event => setKind(event.target.value as ToolDependency['type'])}>{['Agent', '工作流', 'Skill', '运行实例', '部门', '角色'].map(item => <option key={item}>{item}</option>)}</select><input value={target} onChange={event => setTarget(event.target.value)} /><button className="tools-primary" onClick={add}><Plus size={14} />授权 / 绑定</button></div>}</header><div className="tools-dependency-table"><div><span>对象类型</span><span>名称 / ID</span><span>版本</span><span>作用范围</span><span>状态</span><span>操作</span></div>{tool.dependencies.map(item => <div key={item.id}><span><i>{item.type}</i></span><span><b>{item.name}</b><small>{item.id}</small></span><span>{item.version || '—'}</span><span>{item.scope}</span><span className="tools-success">有效</span><span>{editable ? <button onClick={() => { registry.removeDependency(tool.id, item.id); notice(`已回收 ${item.name} 的调用权限`); }}>回收 / 解绑</button> : <button onClick={() => notice(`依赖详情：${item.id} · ${item.scope}`)}><Eye size={13} />查看</button>}</span></div>)}{!tool.dependencies.length && <p className="tools-empty-row">暂无依赖；无依赖草稿可安全删除。</p>}</div></section>;
}

function VersionTab({ tool, role, copy }: { tool: ToolRecord; role: RoleId; copy: () => void }) {
  const [selected, setSelected] = useState(tool.versions[0]?.version || '');
  const canCopy = ['trainer', 'admin', 'superadmin'].includes(role) && ['已发布', '已归档'].includes(tool.lifecycle);
  const version = tool.versions.find(item => item.version === selected);
  return <div className="tools-version-layout"><section className="tools-panel"><header><div><h3>版本历史</h3><p>已发布版本不可变，恢复只生成新草稿。</p></div>{canCopy && <button className="tools-primary" onClick={copy}><Copy size={14} />{tool.lifecycle === '已归档' ? '恢复为新草稿' : '复制为新草稿'}</button>}</header><div className="tools-version-list">{tool.versions.map(item => <button key={item.version} className={selected === item.version ? 'active' : ''} onClick={() => setSelected(item.version)}><b>{item.version}</b><i className={`tools-life is-${item.status}`}>{item.status}</i><span>{item.author} · {item.time}</span><small>{item.change}</small></button>)}</div></section><section className="tools-panel"><header><div><h3>版本差异</h3><p>{version ? `${version.version} 与当前配置的差异摘要` : '选择一个版本'}</p></div></header>{version && <dl className="tools-detail-list"><div><dt>连接</dt><dd>{version.status === '已发布' ? '与当前生产一致' : '连接治理参数有变更'}</dd></div><div><dt>契约</dt><dd>{version.change}</dd></div><div><dt>依赖影响</dt><dd>{tool.dependencies.length} 项依赖需要回归测试</dd></div><div><dt>发布证据</dt><dd>{tool.tests[0]?.id || '无测试证据'}</dd></div></dl>}</section><section className="tools-panel span-2"><header><div><h3>操作审计</h3><p>记录配置、测试、授权和生命周期事件。</p></div></header><div className="tools-audit-list">{tool.audit.map(item => <article key={item.id}><time>{item.time}</time><b>{item.actor}</b><span>{item.action}</span><small>{item.evidence}</small></article>)}</div></section></div>;
}

function lifecycleActions(tool: ToolRecord, role: RoleId) {
  const trainer = ['trainer', 'admin', 'superadmin'].includes(role); const admin = ['admin', 'superadmin'].includes(role);
  const actions: { id: string; label: string; icon: React.ReactNode; primary?: boolean; danger?: boolean }[] = [];
  if (trainer && ['草稿', '测试中'].includes(tool.lifecycle)) actions.push({ id: 'submit', label: '提交审核', icon: <Send size={14} />, primary: true });
  if (trainer && tool.lifecycle === '待审核') actions.push({ id: 'withdraw', label: '撤回', icon: <RotateCcw size={14} /> });
  if (admin && tool.lifecycle === '待审核') actions.push({ id: 'reject', label: '驳回', icon: <XCircle size={14} />, danger: true }, { id: 'publish', label: '发布', icon: <CheckCircle2 size={14} />, primary: true });
  if (trainer && tool.lifecycle === '已发布') actions.push({ id: 'copy-draft', label: '复制新草稿', icon: <Copy size={14} /> });
  if (admin && tool.lifecycle === '已发布') actions.push({ id: 'disable', label: '停用', icon: <PauseCircle size={14} />, danger: true });
  if (admin && tool.lifecycle === '已停用') actions.push({ id: 'restore', label: '恢复调用', icon: <Play size={14} />, primary: true }, { id: 'archive', label: '归档', icon: <Archive size={14} /> });
  if (trainer && tool.lifecycle === '已归档') actions.push({ id: 'restore-draft', label: '恢复为新草稿', icon: <RotateCcw size={14} /> });
  if (trainer && tool.lifecycle === '草稿') actions.push({ id: 'delete', label: '删除草稿', icon: <Trash2 size={14} />, danger: true });
  return actions;
}

function ReasonDialog({ title, onClose, onConfirm }: { title: string; onClose: () => void; onConfirm: (reason: string) => void }) { const [reason, setReason] = useState('连接稳定性或权限范围未达到发布要求'); return <div className="tools-modal-mask"><section className="tools-reason-dialog"><header><h2>{title}</h2><button onClick={onClose}><X /></button></header><label>原因 *<textarea value={reason} onChange={event => setReason(event.target.value)} /></label><footer><button onClick={onClose}>取消</button><button className="danger" disabled={!reason.trim()} onClick={() => onConfirm(reason)}>确认驳回</button></footer></section></div>; }
function connectionLabel(key: string) { return ({ baseUrl: 'Base URL', method: 'Method', path: 'Path', headers: 'Headers', serverUrl: 'MCP 地址', transport: 'Transport', capabilities: '能力清单', protocolVersion: '协议版本', sourceRef: '数据源引用', accessMode: '读写范围', queryTemplate: '查询模板', rowPolicy: '行级权限', provider: '服务商', channel: '通道', capability: '模板能力', sendScope: '发送范围', pathScope: '路径范围', formats: '允许格式', runtime: '运行时', packages: '依赖白名单', resources: '资源上限', networkPolicy: '网络策略' } as Record<string, string>)[key] || key; }
