import React, { useEffect, useMemo, useState } from 'react';
import { Archive, Copy, Edit3, Play, Plus, RotateCcw, ShieldCheck, Trash2 } from 'lucide-react';
import { ModuleHeader } from '../../components/ModuleHeader';
import type { RoleId } from '../../types';
import type { WorkspaceHandoff } from '../../model/router';
import { attackVectors, integrationScenarios, releaseRequests, testProjects, unitCases, type AttackVector, type IntegrationScenario, type Lifecycle, type ReleaseRequest, type TestCase, type TestProject } from './m11-data';
import { useToolRegistry } from '../tools/tool-registry-store';
import { useSkillRegistry } from '../skills/skill-registry-store';
import { useModelBillingRegistry } from '../platform-management/model-billing-store';
import './m11.css';
type Tab='unit'|'integration'|'adversarial'|'gate'; type Item=TestCase|IntegrationScenario|AttackVector|ReleaseRequest; type Kind='unit'|'integration'|'adversarial'|'gate';
const editor=(role:RoleId)=>['trainer','admin','superadmin'].includes(role); const approver=(role:RoleId)=>['admin','superadmin'].includes(role);
export function M11AgentTestSandboxPage({role,handoff,onConsumeHandoff}:{role:RoleId;handoff?:WorkspaceHandoff;onConsumeHandoff?:()=>void}){
 const [tab,setTab]=useState<Tab>('unit'); const [units,setUnits]=useState(unitCases); const [integrations,setIntegrations]=useState(integrationScenarios); const [attacks,setAttacks]=useState(attackVectors); const [releases,setReleases]=useState(releaseRequests); const [query,setQuery]=useState(''); const [modal,setModal]=useState<{kind:Kind,item?:Item}|null>(null); const [notice,setNotice]=useState(''); const writable=editor(role);
 const models=useModelBillingRegistry();
 useEffect(()=>{if(!handoff||handoff.action!=='open-m11')return;setTab('unit');setModal({kind:'unit',item:{id:`CASE-M04-${handoff.messageId}`,name:'M04 候选能力组合测试',agent:handoff.agentId,type:'能力',status:'草稿',expected:`验证项目 ${handoff.projectId} 的候选修复，证据 ${handoff.traceId}`,updatedAt:'刚刚',audit:[`来自 M04 会话 ${handoff.threadId}，尚未创建测试`]}})},[handoff?.traceId]);
 if(['client','employee','business'].includes(role))return <section className="m11-gate"><ShieldCheck/><h1>M11 Agent 测试沙箱不可访问</h1><p>{role==='client'?'客户管理员无权访问内部测试、攻击向量和上线门禁，请前往客户看板查看已授权服务。':'当前岗位不承担 Agent 测试与发布门禁职责，请前往工作空间或任务中心处理已分配事项。'}</p></section>;
 const audit=(message:string)=>setNotice(message); const tabs:[Tab,string,string][]=[['unit','🔬 单元测试','单个 Agent、能力与依赖验证'],['integration','🔗 集成测试','多 Agent 链路、数据与 SLA 验证'],['adversarial','⚔️ 对抗测试','安全、鲁棒性与攻击向量验证'],['gate','🚦 上线门禁','汇总证据、审批、灰度与回滚']];
 const runModelGateway=()=>{const model=models.bindableModels[0];if(!model){audit('没有可测试的已发布健康模型。');return}const id=`M11-MODEL-${Date.now()}`;const response=models.recordModelTestEvidence({id,connectionId:model.connectionId,modelId:model.modelId,source:'M11',passed:true,latency:706,score:97,createdAt:'刚刚',detail:'M11 模型网关：鉴权、JSON 契约、超时、限流和敏感字段校验通过'});models.addDependency(model.connectionId,{id,type:'测试项目',name:`${model.displayName} 模型网关回归`,version:model.version,scope:'M11 单元测试证据'});audit(`${response.message} ${model.label} · ${id}`)};
 return <section className="m11"><Header/>{handoff&&<div className="m11-handoff">来自 M04 · {handoff.projectId} / {handoff.threadId} / {handoff.traceId}<small>已预填 Agent、项目、会话与 Trace；保存后才创建测试用例。</small></div>}<main className="m11-content"><header className="m11-overview"><div><h1>Agent 测试与沙箱环境</h1><p>测试对象、证据和发布决定均在此留痕；当前身份{writable?'可维护测试资产':'仅可查看与运行已授权测试'}。</p></div><div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索 Agent、测试或场景" />{writable&&<button onClick={runModelGateway}><Play size={15}/>模型网关测试</button>}{writable&&<button className="m11-primary" onClick={()=>setModal({kind:tab})}><Plus size={15}/>新建{tabs.find(x=>x[0]===tab)?.[1].replace(/^.. /,'')}</button>}</div></header><nav className="m11-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>{tab==='unit'&&<UnitView items={units} query={query} writable={writable} role={role} onAction={(next,msg)=>{setUnits(next);audit(msg)}} open={setModal}/>} {tab==='integration'&&<IntegrationView items={integrations} query={query} writable={writable} onAction={(next,msg)=>{setIntegrations(next);audit(msg)}} open={setModal}/>} {tab==='adversarial'&&<AttackView items={attacks} query={query} writable={writable} onAction={(next,msg)=>{setAttacks(next);audit(msg)}} open={setModal}/>} {tab==='gate'&&<GateView items={releases} query={query} writable={writable} approve={approver(role)} onAction={(next,msg)=>{setReleases(next);audit(msg)}} open={setModal}/>}</main>{modal&&<CrudModal kind={modal.kind} item={modal.item} close={()=>{setModal(null);if(handoff)onConsumeHandoff?.()}} save={(item,msg)=>{if(modal.kind==='unit')setUnits(items=>upsert(items,item as TestCase));if(modal.kind==='integration')setIntegrations(items=>upsert(items,item as IntegrationScenario));if(modal.kind==='adversarial')setAttacks(items=>upsert(items,item as AttackVector));if(modal.kind==='gate')setReleases(items=>upsert(items,item as ReleaseRequest));setModal(null);if(handoff)onConsumeHandoff?.();audit(msg)}}/>}{notice&&<Notice text={notice} close={()=>setNotice('')}/>}</section>
}
function Header(){return <ModuleHeader title="M11 Agent 测试沙箱" subtitle="管理单元、集成、对抗测试与上线门禁" />}
function metrics(values:[string,string,string][]) {return <div className="m11-metrics">{values.map(([v,l,c])=><div key={l}><strong className={c}>{v}</strong><span>{l}</span></div>)}</div>}
function UnitView({items,query,writable,role,onAction,open}:{items:TestCase[];query:string;writable:boolean;role:RoleId;onAction:(x:TestCase[],m:string)=>void;open:(m:{kind:Kind,item?:Item})=>void}){const registry=useToolRegistry();const skills=useSkillRegistry();const list=items.filter(x=>`${x.name}${x.agent}`.includes(query));const runTool=(item:TestCase)=>{const tool=registry.bindableTools.find(value=>item.agent.includes(value.id)||item.agent.includes(value.name));if(!tool){onAction(items,'该测试未绑定可用 Tool，或目标版本已停用/不健康');return;}const runId=`M11-TOOL-${Date.now()}`;const result=registry.addTestRun(tool.id,{id:runId,time:'刚刚',environment:'测试',result:'通过',latency:'88ms',retries:0,request:'{"source":"M11","case_id":"'+item.id+'"}',response:'{"success":true,"trace_id":"TRACE-M11-TOOL"}'},'M11 Agent 测试沙箱');onAction(items.map(value=>value.id===item.id?{...value,status:'已提交',updatedAt:'刚刚',audit:[`刚刚 M11：Tool 调用测试 ${runId} 通过`,...value.audit]}:value),`${result.message} 结果已回写 Tools：${tool.name}`);};const runSkill=(item:TestCase)=>{const skill=skills.bindableSkills.find(value=>item.agent.includes(value.id)||item.agent.includes(value.name));if(!skill){onAction(items,'该测试未绑定可用 Skill，或目标版本已停用/依赖不健康');return;}const runId=`M11-SKILL-${Date.now()}`;const result=skills.addTestRun(skill.id,{id:runId,time:'刚刚',result:'通过',score:94,latency:'1.1s',traceId:`TRACE-${runId}`,input:`{"source":"M11","case_id":"${item.id}"}`,output:'{"success":true,"evidence":["contract","dependency"]}',dependencyHits:skill.dependencies.slice(0,3).map(value=>value.id),retries:0,fallback:'未触发'},'M11 Agent 测试沙箱');onAction(items.map(value=>value.id===item.id?{...value,status:'已提交',updatedAt:'刚刚',audit:[`刚刚 M11：Skill 测试 ${runId} 通过`,...value.audit]}:value),`${result.message} 结果已回写 Skill 技能库：${skill.name}`);};return <section className="m11-page"><h2>单元测试</h2><p>验证单个 Agent 的能力、知识检索、工具调用、Skill 契约、输出格式和性能阈值。</p>{metrics([['4,820','测试用例总数','blue'],['93.6%','通过率','green'],['308','失败用例','red'],['12.4min','平均执行时间','purple']])}<h3>测试用例集</h3><div className="m11-list">{list.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.id} · {item.agent} · 预期：{item.expected}</small></div><i className={`m11-life ${item.status}`}>{item.status}</i>{writable&&item.type==='工具'&&<button className="primary" onClick={()=>runTool(item)}><Play size={14}/>运行 Tool 测试</button>}{writable&&item.type==='Skill'&&<button className="primary" onClick={()=>runSkill(item)}><Play size={14}/>运行 Skill 测试</button>}<Actions item={item} kind="unit" writable={writable} open={open} mutate={(next,msg)=>onAction(items.map(x=>x.id===next.id?next:x),msg)} remove={()=>onAction(items.filter(x=>x.id!==item.id),'已删除单元测试草稿')}/></article>)}</div>{writable&&<button className="m11-outline" onClick={()=>open({kind:'unit'})}>＋ 新建单元测试用例</button>}<p className="m11-footnote">Tool 与 Skill 测试结果会分别回写 Tools 工具集、Skill 技能库的测试历史与发布门禁证据。</p></section>}
function IntegrationView({items,query,writable,onAction,open}:{items:IntegrationScenario[];query:string;writable:boolean;onAction:(x:IntegrationScenario[],m:string)=>void;open:(m:{kind:Kind,item?:Item})=>void}){const list=items.filter(x=>`${x.name}${x.chain}`.includes(query));return <section className="m11-page"><h2>集成测试</h2><p>模拟真实业务流程，验证多 Agent 数据传递、时序、人工审批、异常处理与 SLA。</p>{metrics([['50/50','全链路场景通过','green'],['3m24s','最长场景耗时','blue'],['0','数据丢失','green'],['100%','数据一致性','green']])}<div className="m11-list">{list.map(item=><article key={item.id}><div><strong>🔗 场景：{item.name}</strong><small>{item.chain}</small><small>{item.passRate} 通过 · {item.sla} · {item.detail}</small></div><i className={`m11-life ${item.status}`}>{item.status}</i><Actions item={item} kind="integration" writable={writable} open={open} mutate={(next,msg)=>onAction(items.map(x=>x.id===next.id?next:x),msg)} remove={()=>onAction(items.filter(x=>x.id!==item.id),'已删除集成场景草稿')}/></article>)}</div>{writable&&<button className="m11-outline" onClick={()=>open({kind:'integration'})}>＋ 新建集成场景</button>}</section>}
function AttackView({items,query,writable,onAction,open}:{items:AttackVector[];query:string;writable:boolean;onAction:(x:AttackVector[],m:string)=>void;open:(m:{kind:Kind,item?:Item})=>void}){const list=items.filter(x=>`${x.type}${x.target}`.includes(query));return <section className="m11-page"><h2>对抗测试</h2><p>覆盖 Prompt 注入、越权访问、数据泄露、偏见诱导、超长输入和拒绝服务等攻击向量。</p>{metrics([['186','攻击向量库','red'],['94.1%','防御成功率','green'],['11','已暴露漏洞','red'],['2h前','上次对抗测试','blue']])}<div className="m11-table compact"><div><span>攻击类型</span><span>攻击向量</span><span>目标 Agent</span><span>结果</span><span>说明</span><span>操作</span></div>{list.map(item=><div key={item.id}><span>{item.type}</span><span>{item.payload}</span><span>{item.target}</span><span><i className={item.result==='防御'?'m11-ok':'m11-bad'}>{item.result}</i></span><span>{item.detail}</span><Actions item={item} kind="adversarial" writable={writable} open={open} mutate={(next,msg)=>onAction(items.map(x=>x.id===next.id?next:x),msg)} remove={()=>onAction(items.filter(x=>x.id!==item.id),'已删除对抗用例草稿')}/></div>)}</div>{writable&&<button className="m11-outline" onClick={()=>open({kind:'adversarial'})}>＋ 新建攻击向量</button>}</section>}
function GateView({items,query,writable,approve,onAction,open}:{items:ReleaseRequest[];query:string;writable:boolean;approve:boolean;onAction:(x:ReleaseRequest[],m:string)=>void;open:(m:{kind:Kind,item?:Item})=>void}){const list=items.filter(x=>`${x.name}${x.agent}`.includes(query));return <section className="m11-page"><h2>上线审批门禁</h2><p>单元、集成、对抗测试均达标后才可提交；审批后按灰度策略监控，并支持撤回或归档。</p><div className="m11-list">{list.map(item=><article key={item.id}><div><strong>📋 发布申请 #{item.id}：{item.name}</strong><small>申请人：{item.owner} · 单元 {item.unit} · 集成 {item.integration} · 对抗 {item.adversarial}</small><small>灰度：{item.gray}</small></div><i className={`m11-life ${item.status}`}>{item.status}</i><div className="m11-actions">{writable&&item.status==='草稿'&&<button onClick={()=>onAction(items.map(x=>x.id===item.id?{...x,status:'待审批',audit:['刚刚 当前用户：提交发布申请',...x.audit]}:x),'发布申请已提交审批')}>提交审批</button>}{approve&&item.status==='待审批'&&<button className="primary" onClick={()=>onAction(items.map(x=>x.id===item.id?{...x,status:'灰度中',gray:'10%流量 · 运行0h',audit:['刚刚 当前用户：批准10%灰度',...x.audit]}:x),'已批准 10% 灰度发布')}>批准灰度</button>}{writable&&item.status==='灰度中'&&<button onClick={()=>onAction(items.map(x=>x.id===item.id?{...x,status:'已归档',gray:'已撤回',audit:['刚刚 当前用户：撤回灰度',...x.audit]}:x),'已撤回灰度并归档申请')}>撤回灰度</button>}<button onClick={()=>open({kind:'gate',item})}><Edit3 size={14}/>查看/编辑</button></div></article>)}</div>{writable&&<button className="m11-outline" onClick={()=>open({kind:'gate'})}>＋ 新建发布申请</button>}</section>}
function Actions({item,kind,writable,open,mutate,remove}:{item:any;kind:Kind;writable:boolean;open:(m:{kind:Kind,item?:Item})=>void;mutate:(v:any,m:string)=>void;remove:()=>void}){if(!writable)return <button onClick={()=>open({kind,item})}>查看</button>;const archived=item.status==='已归档';return <div className="m11-actions"><button onClick={()=>open({kind,item})}><Edit3 size={14}/>编辑</button><button onClick={()=>open({kind,item:{...item,id:`${item.id}-COPY`,name:`${item.name}（副本）`,status:'草稿'}})}><Copy size={14}/>复制</button>{archived?<button onClick={()=>mutate({...item,status:'草稿'},'已恢复为草稿')}><RotateCcw size={14}/>恢复</button>:item.status==='草稿'?<button className="danger" onClick={remove}><Trash2 size={14}/>删除</button>:<button onClick={()=>mutate({...item,status:'已归档'},'已归档，保留审计和运行证据')}><Archive size={14}/>归档</button>}</div>}
function CrudModal({kind,item,close,save}:{kind:Kind;item?:Item;close:()=>void;save:(x:Item,m:string)=>void}){
 const registry=useToolRegistry();
 const skills=useSkillRegistry();
 const source:any=item||{}; const [name,setName]=useState(source.name||''); const [agent,setAgent]=useState(source.agent||source.target||'线索诊断 Agent'); const [type,setType]=useState(source.type||'能力'); const [expected,setExpected]=useState(source.expected||''); const [chain,setChain]=useState(source.chain||''); const [sla,setSla]=useState(source.sla||'≤ 60s'); const [payload,setPayload]=useState(source.payload||''); const [result,setResult]=useState(source.result||'防御'); const [detail,setDetail]=useState(source.detail||''); const [unit,setUnit]=useState(source.unit||'≥ 98%'); const [integration,setIntegration]=useState(source.integration||'≥ 95%'); const [adversarial,setAdversarial]=useState(source.adversarial||'≥ 90%'); const [gray,setGray]=useState(source.gray||'10%流量 · 3小时'); const [owner,setOwner]=useState(source.owner||'当前用户');
 const title={unit:'单元测试用例',integration:'集成测试场景',adversarial:'对抗攻击向量',gate:'发布申请'}[kind];
 const make=()=>{const base={...source,id:source.id||`${kind.toUpperCase()}-${Date.now().toString().slice(-5)}`,name:name.trim()||`未命名${title}`,status:source.status||'草稿',audit:[`刚刚 当前用户：${source.id?'编辑':'新建'}${title}`,...(source.audit||[])]};let next:any;
  if(kind==='unit') next={...base,agent,type,expected:expected.trim()||'未填写预期输出',updatedAt:'刚刚'};
  else if(kind==='integration') next={...base,chain:chain.trim()||`${agent} → 人工审批 → 结果回写`,passRate:source.passRate||'待运行',sla,detail:detail.trim()||'未填写场景验收说明'};
  else if(kind==='adversarial') next={...base,type,payload:payload.trim()||'未填写攻击载荷',target:agent,result,detail:detail.trim()||'未填写防御规则'};
  else next={...base,agent,unit,integration,adversarial,gray,owner};
  save(next,`${title}已保存为${next.status}`);
 };
 return <div className="m11-mask"><section className="m11-modal"><header><h2>{item?'编辑':'新建'}{title}</h2><button onClick={close}>×</button></header>
  <label>名称<input value={name} onChange={e=>setName(e.target.value)} placeholder={`输入${title}名称`}/></label>
  {kind==='unit'&&<><label>测试类型<select value={type} onChange={e=>{const next=e.target.value;setType(next);if(next==='工具')setAgent(registry.bindableTools[0]?`${registry.bindableTools[0].id} · ${registry.bindableTools[0].name} · ${registry.bindableTools[0].currentVersion}`:'');if(next==='Skill')setAgent(skills.bindableSkills[0]?`${skills.bindableSkills[0].id} · ${skills.bindableSkills[0].name} · ${skills.bindableSkills[0].currentVersion}`:'');}}><option>能力</option><option>知识</option><option>工具</option><option>Skill</option><option>安全</option></select></label>{type==='工具'?<label>目标 Tool<select value={agent} onChange={e=>setAgent(e.target.value)}><option value="">请选择已发布且健康的 Tool</option>{registry.bindableTools.map(tool=><option key={tool.id} value={`${tool.id} · ${tool.name} · ${tool.currentVersion}`}>{tool.name} · {tool.currentVersion} · {tool.contract.operation}</option>)}</select></label>:type==='Skill'?<label>目标 Skill<select value={agent} onChange={e=>setAgent(e.target.value)}><option value="">请选择已发布且健康的 Skill</option>{skills.bindableSkills.map(skill=><option key={skill.id} value={`${skill.id} · ${skill.name} · ${skill.currentVersion}`}>{skill.name} · {skill.currentVersion} · {skill.type}</option>)}</select></label>:<label>目标 Agent<select value={agent} onChange={e=>setAgent(e.target.value)}><option>线索诊断 Agent</option><option>质量诊断 Agent</option><option>内容生成 Agent</option></select></label>}<label>预期结果<textarea value={expected} onChange={e=>setExpected(e.target.value)} placeholder="例如：返回意向等级、证据与建议动作"/></label></>}
  {kind==='integration'&&<><label>场景链路<textarea value={chain} onChange={e=>setChain(e.target.value)} placeholder="例如：营销策略 Agent → 用户洞察 Agent → 人工审批 → 效果评估 Agent"/></label><label>SLA 目标<select value={sla} onChange={e=>setSla(e.target.value)}><option>≤ 30s</option><option>≤ 60s</option><option>≤ 5min</option></select></label><label>验收说明<textarea value={detail} onChange={e=>setDetail(e.target.value)} placeholder="说明数据一致性、人工审批、异常处理等验收条件"/></label></>}
  {kind==='adversarial'&&<><label>攻击类型<select value={type} onChange={e=>setType(e.target.value)}><option>Prompt注入</option><option>越权访问</option><option>数据泄露</option><option>偏见诱导</option><option>拒绝服务</option></select></label><label>目标 Agent<select value={agent} onChange={e=>setAgent(e.target.value)}><option>线索诊断 Agent</option><option>内容生成 Agent</option><option>客服应答 Agent</option></select></label><label>攻击载荷<textarea value={payload} onChange={e=>setPayload(e.target.value)} placeholder="输入模拟攻击向量"/></label><label>预期结果<select value={result} onChange={e=>setResult(e.target.value)}><option>防御</option><option>暴露</option></select></label><label>防御/处置规则<textarea value={detail} onChange={e=>setDetail(e.target.value)} placeholder="说明拦截、脱敏、人工接管或修复规则"/></label></>}
  {kind==='gate'&&<><label>发布 Agent<select value={agent} onChange={e=>setAgent(e.target.value)}><option>内容生成 Agent</option><option>线索诊断 Agent</option><option>Agent 编排引擎</option></select></label><label>单元测试门槛<select value={unit} onChange={e=>setUnit(e.target.value)}><option>≥ 98%</option><option>≥ 95%</option><option>100%</option></select></label><label>集成测试门槛<select value={integration} onChange={e=>setIntegration(e.target.value)}><option>≥ 95%</option><option>100%</option></select></label><label>对抗测试门槛<select value={adversarial} onChange={e=>setAdversarial(e.target.value)}><option>≥ 90%</option><option>≥ 95%</option></select></label><label>灰度策略<select value={gray} onChange={e=>setGray(e.target.value)}><option>10%流量 · 3小时</option><option>5%流量 · 24小时</option><option>全量发布</option></select></label><label>申请人<input value={owner} onChange={e=>setOwner(e.target.value)}/></label></>}
  <p>草稿可删除；提交、灰度和归档记录只能撤回、归档或恢复，确保发布证据可追溯。</p><footer><button onClick={close}>取消</button><button className="m11-primary" onClick={make}>保存草稿</button></footer></section></div>
}
function upsert<T extends {id:string}>(items:T[],item:T){return items.some(x=>x.id===item.id)?items.map(x=>x.id===item.id?item:x):[item,...items]};function Notice({text,close}:{text:string;close:()=>void}){return <div className="m11-notice">{text}<button onClick={close}>关闭</button></div>}
